### ISSUE TITLE
Some errors are not catched sometimes in the validate_only mode

### ISSUE THREAD

**Issue by ivallesp** [googleads/googleads-python-lib#100]
Hi,

I need to upload campaigns in my work using the AdWords API and I am facing with an problem related to the Error Handling. I developed my tool by starting from the examples I found in the googleads (Python) github. The problem is that, when I try to mutate a bunch of operations (2000 or less, as the documentation says) using the validate_only method, sometimes, one or more errors are not raised and then I don't solve/remove these problematic operations. When I solve the raised operations and try to perform a mutate now without the validate_only method, it raises an error.

I think it is caused by a bug in the library or by something that I am passing over. With the aim of showing you where the error is happening, I wrote a easily reproducible example where I try to mutate an "illegal" operation 10000 times. I found that about 1 out of 10000 times the operation is not marked as "illegal" and it makes me think that something bad happens. 

I am using the last version of the googleads library with Python 2.7 installed from the Anaconda Environment.

```
adgroup_id = # The Adgroup Id of an existing Adgroup
client = # Your client object

keyword = "test protos"
operations= []

op = {
'xsi_type': 'BiddableAdGroupCriterion',
'adGroupId': adgroup_id,
'biddingStrategyConfiguration': {
    'bids': [{
            'xsi_type': 'CpcBid',
            'bid': {
                'microAmount': '300000'},
        }
    ]
},
'criterion': {
    'xsi_type': 'Keyword',
    'matchType': 'BROAD',
    'text': keyword
}
}

operations.append({
'operator': 'ADD',
'operand': op
})

number_of_errors=[]
ERRORS=[]
ad_group_criterion_service = _client.GetService('AdGroupCriterionService', version='v201509')

# Let's try to repeat the same operation a lot of times
client.validate_only = True
for i in range(10000):
    errors=[]
    try:
        ad_group_criterion_service.mutate(operations)
    except suds.WebFault, e:
        errors = e.fault.detail.ApiExceptionFault.errors if type(
            e.fault.detail.ApiExceptionFault.errors) == list else [e.fault.detail.ApiExceptionFault.errors]
    number_of_errors.append(len(errors))
    ERRORS.append(e)
```

**Comment by msaniscalchi** [comment]
Thanks, we'll look into it and see if we can reproduce the issue.

**Comment by msaniscalchi** [comment]
Hello. Sorry it took so long to get around to this. I've investigated and have verified that, at least as of the current library version, I can not reproduce the issue you're describing. I've run your script a few times, and have verified that it consistently produces 10,000 errors with validate_only applied.

If something like this happens, it is generally more likely that it is an issue with the API rather than this library. With that in mind, if you do see this again going forward, please report it to the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark
