### ISSUE TITLE
AdGroupLabelOperation not working (BatchJob)

### ISSUE THREAD

**Issue by howach** [googleads/googleads-python-lib#102]
I use following code to add labels but get an error:
adgroup_operations = [{'operand': {'adGroupId': id_1, 'labelId': lbl_id1}, 'operator': 'ADD', 'xsi_type': 'AdGroupLabelOperation'}, {'operand': {'adGroupId': id_2, 'labelId': lbl_id2}, 'operator': 'ADD', 'xsi_type': 'AdGroupLabelOperation'}]

batch_job_helper.UploadOperations(upload_url, adgroup_operations)

The error I get: "GoogleAdsValueError: Unrecognized service for the AdWords API. Service given: AdGroupLabelService"

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! We're already looking into this one and anticipate that the fix will go out along with some others later this week.

Regards,
Mark Saniscalchi
