### ISSUE TITLE
Money fields in reports

### ISSUE THREAD

**Issue by gaurav3ansal** [googleads/googleads-python-lib#107]
Hello Team,

So, first of all I'd like to state that this is not an issue. This is regarding Money related fields in reports. Fields of type Money are returned in micro currency units (micros), e.g.: $1.23 will come back as 1230000 (1.23 x 1,000,000). Do we've any provision to calculate these fields in Report Query itself?

Thanks,
Gaurav B

**Comment by nicholaschen** [comment]
They're all micro-units, so you could write your own helper method to divide by float 1,000,000?

This is probably more of product API question, so you'd want to ask on the API forums:

https://groups.google.com/forum/#!forum/adwords-api
https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api
