### ISSUE TITLE
Unable to import googleads (syntax error line 519) googleads 3.13.0, python 2.6.6

### ISSUE THREAD

**Issue by DavidRohde** [googleads/googleads-python-lib#109]
I hope this is the right place to do this.  I did search to see if anybody else has this issue but I didn't find anything - although I wouldn't be shocked if I missed something.

I am experiencing a show stopper bug where I can't execute:

import googleads  

File "/home/drohde/.local/lib/python2.6/site-packages/googleads/adwords.py", line 519
    for op in (
      ^
SyntaxError: invalid syntax

Some further detail:

pip show googleads
You are using pip version 7.1.0, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Metadata-Version: 1.0
Name: googleads
Version: 3.13.0
Summary: Google Ads Python Client Library
Home-page: https://github.com/googleads/googleads-python-lib
Author: Mark Saniscalchi
Author-email: msaniscalchi@google.com
License: Apache License 2.0
Location: /home/drohde/.local/lib/python2.6/site-packages
Requires: httplib2, oauth2client, suds-jurko, pysocks, pytz, PyYAML, xmltodict

[drohde@iag.lab.zoot.maroon.334]$ ipython
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import googleads
  File "/home/drohde/.local/lib/python2.6/site-packages/googleads/adwords.py", line 519
    for op in (
      ^
SyntaxError: invalid syntax

**Comment by DavidRohde** [comment]
rolling back to version 3.11.0 fixed the problem for me...

**Comment by msaniscalchi** [comment]
Hello David,

Although things don't always necessarily break in lower versions, the minimum Python 2 version supported by this library is Python 2.7.9. The reason you're seeing an invalid syntax error on that line is because we happened to introduce a [dict comprehension](https://www.python.org/dev/peps/pep-0274/), which is not supported in versions prior to Python 2.7.

To resolve this issue and avoid other potential issues, please upgrade to at least Python 2.7.9.

**Comment by pbx** [comment]
David: If for some reason you are stuck on Python 2.6 for now, as we are with my main project at work, you could try a Python 2.6 fork that I made: https://github.com/coxmediagroup/googleads-python-lib/tree/py26

**Comment by msaniscalchi** [comment]
One point I'd like to mention--one of the critical features pushing our minimum supported Python 2 version to 2.7.9 is the support for certificate validation. I'm not sure if you have done this already in your fork, but you could roll your own support for this if you want to ensure connections are secure.

For more information, check out [PEP-0476](https://www.python.org/dev/peps/pep-0476/).
