### ISSUE TITLE
Passing Proxy Username and Password

### ISSUE THREAD

**Issue by fdosani** [googleads/googleads-python-lib#113]
Hi there,

I'm running into a bit of an issue as I'm behind a corp firewall which requires traffic to go through a proxy and also needs authentication.

I'm just loading a credentials file using the method
`AdWordsClient.LoadFromStorage("/path/to/myfile")`
which will throw the following error:

`HTTPError: (407, 'Proxy Authentication Required')`

I believe the client will call the OAuth library and try and refresh the necessary tokens., but looking at the following code shows that `proxy_user` and `proxy_pass` are never sent to `httplib2.ProxyInfo`

Specifically this line of code: https://github.com/googleads/googleads-python-lib/blob/69369aedffae9be1a3059b62acd7900ddb43df1e/googleads/common.py#L118

I've even tried to imbed the username and password into the URL as such with no luck:
```
# Proxy configurations (optional)
proxy_info:
  host: username:password@myproxy.com
  port: 1234
```

I feel like this would require a new feature as such in `common.py` starting at line 118:
```
    proxy_info = (httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, proxy_data['host'],
                                     proxy_data['port'], proxy_user=proxy_data['user'],
                                     proxy_pass=proxy_data['password'])
                  if proxy_data else None)

    if proxy_info.proxy_user:
      client_kwargs['https_proxy'] = ('%s:%s@%s:%s' % (proxy_info.proxy_user,
                                                      proxy_info.proxy_pass,
                                                      proxy_info.proxy_host,
                                                      proxy_info.proxy_port)
                                      if proxy_info else None)
    else:
      client_kwargs['https_proxy'] = ('%s:%s' % (proxy_info.proxy_host,
                                                proxy_info.proxy_port)
                                      if proxy_info else None)
```

Thanks,
Faisal

**Comment by msaniscalchi** [comment]
Hello Faisal,

Thanks for the report! I was actually actively working on improvements to proxy support, so the good news is that I'm not only aware of the problem and solution, but that most of the work is already done.

This should be released along with some other changes in early-mid April. I'll close this issue when the release goes out.

**Comment by fdosani** [comment]
Thanks!
