### ISSUE TITLE
Doesnt work on python2.6.6 anymore.

### ISSUE THREAD

**Issue by pluto2105** [googleads/googleads-python-lib#116]
Due to the _OPERATION_MAP being generated in adwords:519, the module doesnt work on python2.6.6. Can you please replace the generation with the following:

#Begin
    _OPERATION_MAP = {
        'AdGroupAdOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                    ('AdGroupAdOperation', 'AdGroupAdService', 'mutate'),
        'AdGroupAdLabelOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                        ('AdGroupAdLabelOperation', 'AdGroupAdService', 'mutateLabel'),
        'AdGroupBidModifierOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                        ('AdGroupBidModifierOperation', 'AdGroupBidModifierService', 'mutate'),
        'AdGroupCriterionOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                        ('AdGroupCriterionOperation', 'AdGroupCriterionService', 'mutate'),
        'AdGroupCriterionLabelOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                            ('AdGroupCriterionLabelOperation', 'AdGroupCriterionService', 'mutateLabel'),
        'AdGroupOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                ('AdGroupOperation', 'AdGroupService', 'mutate'),
        'AdGroupLabelOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                    ('AdGroupLabelOperation', 'AdGroupService', 'mutateLabel'),
        'BudgetOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                ('BudgetOperation', 'BudgetService', 'mutate'),
        'CampaignCriterionOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                        ('CampaignCriterionOperation', 'CampaignCriterionService', 'mutate'),
        'CampaignOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                ('CampaignOperation', 'CampaignService', 'mutate'),
        'CampaignLabelOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                        ('CampaignLabelOperation', 'CampaignService', 'mutateLabel'),
        'FeedItemOperation': namedtuple('Operation', ['operation_type', 'service', 'method'])
                                ('FeedItemOperation', 'FeedItemService', 'mutate')
    }        
#End

I tried forking, so i could edit myself and then submit a pull request but it didnt work. Please make the change so that we can continue working with python2.6 (It is a huge effort for us to move to python2.7). 

Thanks in advance.

**Comment by nicholaschen** [comment]
While I certainly understand that upgrading might be a pain-point, our library (this one at least) has never explicitly offered support for < 2.7:

https://pypi.python.org/pypi/googleads

> This library is supported for Python 2 and 3, for versions 2.7+ and 3.4+ respectively. It is recommended that Python 2 users use python 2.7.9+ to take advantage of the SSL Certificate Validation feature that is not included in earlier versions.
