### ISSUE TITLE
Sudden error message for non deprecated version of API

### ISSUE THREAD

**Issue by barnettjacob** [googleads/googleads-python-lib#117]
Hi, 

I've had this script running for some time that gathers the names of our adwords accounts:
```
managed_customer_service = adwords_client.GetService('ManagedCustomerService', version='v201506')
selector = {'fields': ['CustomerId', 'Name'],'predicates' [{'field':'CanManageClients','operator':'EQUALS','values':'FALSE'}]}
graph = managed_customer_service.get(selector)
accounts = graph['entries']
```

I'm suddenly getting an error message:

> 'You are accessing an AdWords API version v201506 that has been discontinued. Calls to this version may fail. Please visit the AdWords API blog for information on migration to the new AdWords API version

However when I change the version to v201603 I get this message:

```
GoogleAdsValueError: Unrecognized version of the AdWords API. Version given: v201603 Supported versions: ['v201502', 'v201506']
```

Any help or advice appreciated.

**Comment by msaniscalchi** [comment]
Hello,

Actually, [AdWords v201506 is deprecated](http://googleadsdeveloper.blogspot.com/2016/03/adwords-api-v201506-sunset-reminder.html). That is why you're seeing that first error message.

As for the second message, it looks like you might not have updated your installation. If you update the installation with the following command, you should be able to use v201603:

```pip install --upgrade googleads```
