### ISSUE TITLE
update on the status of the suds-jurko situation, please

### ISSUE THREAD

**Issue by jononomo** [googleads/googleads-python-lib#125]
Hi.  I'm following this thread: https://bitbucket.org/jurko/suds/issues/81/suds-should-support-an-empty-object

I noticed that the latest version of googleads still depends on suds-jurko 0.6.  Is this a problem?  It seems like it would be.

**Comment by nicholaschen** [comment]
Please see release 3.13:

https://github.com/googleads/googleads-python-lib/blob/master/ChangeLog
