### ISSUE TITLE
Get available customer IDs / accounts

### ISSUE THREAD

**Issue by tejasmanohar** [googleads/googleads-python-lib#127]
Is there any way to find the available client customer IDs / accounts available to a user?

[ref](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L197-L198)

**Comment by msaniscalchi** [comment]
Hello,

This is probably a question better-suited for the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api). You should only post here if you have a library-specific issue.

That said, yes, I believe the Service you are looking for is the [ManagedCustomerService](https://developers.google.com/adwords/api/docs/reference/v201605/ManagedCustomerService).

Regards,
Mark
