### ISSUE TITLE
UnicodeEncodeError in ReportDownloader

### ISSUE THREAD

**Issue by Bobspadger** [googleads/googleads-python-lib#128]
Just recently started getting UnicodeEncodeError in the reportDownloader

Only started in the last couple of weeks, not always the same character or report.

Stack Trace:

```
Traceback (most recent call last):
  File "/Users/alexhellier/Documents/git/google-api-v2/apiv2/adwords_reporting.py", line 88, in <module>
    main(adwords_client)
  File "/Users/alexhellier/Documents/git/google-api-v2/apiv2/adwords_reporting.py", line 73, in main
    skip_report_summary=True, include_zero_impressions=False)
  File "/usr/local/lib/python3.5/site-packages/googleads/adwords.py", line 1142, in DownloadReport
    output, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/googleads/adwords.py", line 1416, in _DownloadReport
    else response.read())
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 322334: ordinal not in range(128)
```

**Comment by Bobspadger** [comment]
Should mention this was with the 4.0.0 release, I've also tried the 4.1.0 and 4.2.0 both give the same issue.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for your report! I've tested the ReportDownloader against Python2 / Python3 with unicode input, including the character causing your issue in the stack trace for good measure. I have not been able to reproduce the issue.

I suspect this may be related to a non-library issue others reported earlier, where their default encoding was set to something other than utf-8. I suggest verifying that your environment's default encoding is set to utf-8. If it isn't, try changing it and see if that resolves the issue.

Otherwise, feel free to provide more specifics about the call you're making and your environment and I'll take a closer look.

Regards,
Mark Saniscalchi

**Comment by Bobspadger** [comment]
Hi @msaniscalchi thanks for the info.

I'm using this in a very basic format - so all the suds etc are installed from the googleads dependancies.

On both machines that are having this issue (both os x) I run the following:

```
In[2]: import sys
In[3]: sys.getdefaultencoding()
Out[3]: 
'utf-8'
```

and get utf-8 for them both.

I'm not sure where else to look?

**Comment by msaniscalchi** [comment]
It is very likely that your terminal is configured with a non-utf-8 locale.

Try running `locale` to see what your current configuration is. You can then see what locales are installed via the `locale -a` command.

If you, for example, had `en_US.US-ASCII` set, you would receive a UnicodeDecodeError as you described. You would resolve this by setting the locale to use utf-8.

Regards,
Mark

**Comment by Bobspadger** [comment]
This shows:

```
➜  ~ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

on both machines on which I have tried this code :(

**Comment by msaniscalchi** [comment]
That's surprising. I can't reproduce the issue, and from what I've seen, your environment _appears_ to be configured correctly.

Can you provide a small snippet of code that you can use to reproduce the issue?

**Comment by Bobspadger** [comment]
@msaniscalchi  Essentially I've used the example files, and just keep putting in a different report template so I get multiple reports.

**Comment by Bobspadger** [comment]
For anyone else that may have this issue I've found the solution.

`f = open('myfile.csv', 'w')`

should be:

`f = open('myfile.csv', mode='w', encoding='utf8')`

The error was being thrown in `adwords.py` as this was where the object was being used

**Comment by msaniscalchi** [comment]
Thanks for clarifying.
