### ISSUE TITLE
QuotaCheckError.INVALID_TOKEN_HEADER. How to check what the issue is?

### ISSUE THREAD

**Issue by manuganji** [googleads/googleads-python-lib#130]
I'm trying to run the `get_campaigns.py` example code. I created the adwords client object using the correct, `client_id`, `client_secret` and `refresh_token`. When I run it however I get the traceback ending with

`Server raised fault: '[QuotaCheckError.INVALID_TOKEN_HEADER @ ; trigger:'6Ji***developer-token****Yg']'`

When I scroll up the logs I see that HEADERS were logged and they don't mention any `developerToken` that should have been, as per [this guide](https://github.com/googleads/googleads-dotnet-lib/wiki/NoClientLibrary#downloading-adwords-api-reports)

`URL: https://adwords.google.com/api/adwords/cm/v201605/CampaignService`
`HEADERS: {'Soapaction': b'""', 'Content-Type': 'text/xml; charset=utf-8', 'Content-type': 'text/xml; charset=utf-8', 'Authorization': 'Bearer ya2***access_token***194f3g', 'SOAPAction': b'""'}`
`MESSAGE:
b'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:tns="https://adwords.google.com/api/adwords/cm/v201605" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201605" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header><tns:RequestHeader><tns:clientCustomerId>659-360-1388</tns:clientCustomerId><tns:developerToken>6Ji***developer-token****Yg</tns:developerToken><tns:userAgent>MYM (AwApi-Python, googleads/4.2.0, Python/3.5.1)</tns:userAgent><tns:validateOnly>false</tns:validateOnly><tns:partialFailure>false</tns:partialFailure></tns:RequestHeader></SOAP-ENV:Header><ns0:Body><ns1:get><ns1:serviceSelector><ns1:fields>Id</ns1:fields><ns1:fields>Name</ns1:fields><ns1:fields>Status</ns1:fields><ns1:paging><ns1:startIndex>0</ns1:startIndex><ns1:numberResults>100</ns1:numberResults></ns1:paging></ns1:serviceSelector></ns1:get></ns0:Body></SOAP-ENV:Envelope>'
`

Also, could you please confirm this: the developer token was granted for _info@mydomain.com_ while the `client_id` and `client_secret` were created with _reporting+testaccount@mydomain.com_ which is a test manager account that I created for testing the API. Does this make a difference? Also, the developer_token is in _test\_account_ status now.

Can you please tell me what I am doing wrong? I can PM you my credentials and script to try it out at your end. I have been struggling to fix this issue for the last 5 days. If this Python lib is not well supported, please tell me what is the recommended platform so that I can I'll switch to it. Thanks in advance for your support!

**Comment by sfontana** [comment]
Hello, your AdWords Account name appears to be "Account 1". Please be careful when sharing valid access tokens with everyone, someone could do much worse :)  

ps: you can edit your message

**Comment by sfontana** [comment]
Ah you probably want to post your question here: https://groups.google.com/forum/#!forum/adwords-api  there you'll definitely get an answer for your problem.

**Comment by manuganji** [comment]
Thanks a lot @sfontana!

**Comment by manuganji** [comment]
It happened due to a mistake in copying the developer token to my code. You can read the discussion over at Google Groups - https://groups.google.com/forum/#!topic/adwords-api/V4oaXBgEm8k
