### ISSUE TITLE
How to get adgroup tree from adgroup Id 

### ISSUE THREAD

**Issue by Ads7** [googleads/googleads-python-lib#132]
I am trying to edit the leaf node of the current shopping campaign and add a new child division.
The [https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201605/shopping/add_product_partition_tree.py](example) creates a new tree and then callsadgroup_criterion_service.mutate.

Is there any way to get the existing divisions/tree so that i could transverse it and add leaf node in it.
In the Java example.

>  ProductPartitionTree.createAdGroupTree(adWordsServices, session,adGroupId);

provides me the current tree and mutate operations are possible on it

**Comment by msaniscalchi** [comment]
Hello,

Sorry for the delay on this. The Java and Python implementation are a bit different in the sense that Java has a full-fledged utility for shopping whereas Python currently only provides a tool specifically intended to be used for the shopping sample. 

At this time, the Python library is not offering a utility that can create a non-empty AdGroup tree. That said, we will consider this feedback when deciding on new library functionality going forward.
