### ISSUE TITLE
Question about wiki page about API access (web-flow)

### ISSUE THREAD

**Issue by Alzakath** [googleads/googleads-python-lib#134]
https://github.com/googleads/googleads-python-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)

I was reading this documentation and I'm not quite sure of something, where does the `developer_token` come from in that code sample

`adwords_client = adwords.AdWordsClient(developer_token, oauth2_client, user_agent, client_customer_id)`

Does it come from the credentials received in earlier step like `refresh_token` ?

**Comment by msaniscalchi** [comment]
Hello,

In the future, please post questions about the API itself to its corresponding [support forum](https://groups.google.com/forum/#!forum/adwords-api). This issue tracker is intended to focus on technical issues with this particular client library.

As for your question, the Developer Token is received after a customer finishes [signing up](https://developers.google.com/adwords/api/docs/guides/signup) for AdWords.

Regards,
Mark
