### ISSUE TITLE
Error when uploading operations using batch job service

### ISSUE THREAD

**Issue by btourtellott** [googleads/googleads-python-lib#138]
The `__init__` of `urllib2.HTTPError` expects six arguments, but `googleads.adwords.UploadOperations` L1030 only passes two:

`raise urllib2.HTTPError(e)`

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! It looks like this shouldn't impact your ability to use BatchJobService, but it does negatively impact error handling. I'll look into it.
