### ISSUE TITLE
Errors when upgrading v201607 API

### ISSUE THREAD

**Issue by yingyingchen** [googleads/googleads-python-lib#139]
This is an issue specific to the AdWords API Python client library.
According to the link: https://github.com/googleads/googleads-python-lib/issues/110
We installed both versions of oauth2client under different names. But then we get a new error:

adwords_sem_job (an instance of ProcessAdwords/GoogleAdwordsFetch) fails when trying to create an AdwordsClient:
  File "/home/hadoop/.pex/code/9ed38668874a20ddfc11cc4b450e4b04ea914778/houzz/streaming/adwords/adwords_utils.py", line 29, in create_adwords_client
    return adwords.AdWordsClient(developer_token, oauth_client, user_agent, account_id)
TypeError: __init__() takes exactly 4 arguments (5 given)

In this case, where shall i specify which account to download the data if the new version doesn't take the account_id?

**Comment by msaniscalchi** [comment]
Hello,

It looks like this is probably an issue in your code; this is the signature for AdWordsClient's __init__:

```
def __init__( self, developer_token, oauth2_client, user_agent, **kwargs):
```

There is no account_id field, but perhaps you're referring to the client_customer_id? If so, keep in mind that it is a keyword argument.

Regards,
Mark

**Comment by yingyingchen** [comment]
Yes，I am referring the client_customer_id. Can you give me more detail what the keywords argument about? So where shall I define the client_customer_id?

**Comment by msaniscalchi** [comment]
If you wanted to instantiate an AdWordsClient with a client_customer_id specified, you would need to include it as a keyword argument. For example:

```
client = googleads.adwords.AdWordsClient(dev_token, oauth2_client, user_agent,
                                         client_customer_id=client_customer_id)
```
