### ISSUE TITLE
Unable to pickle/unpickle AdwordsClient

### ISSUE THREAD

**Issue by suvodhoy** [googleads/googleads-python-lib#140]
With the introduction of proxy_config in the AdwordsClient, I am unable to pickle/unpickle the client. It throws an error `__new__() takes at least 2 arguments (1 given)` while unpickling. This is due to `googleads.common.ProxyConfig()` present in both the **AdwordsClient** and the **GoogleRefreshTokenClient**. Is this an expected behaviour?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! While this _is_ unexpected, we have not prioritized the ability to pickle/unpickle the client(s). It has never been a documented feature of this library, so if it had worked in the past, it was merely a coincidence. Could you clarify what the use-case for this would be? I would have expected loading from a configuration file to be sufficient.

**Comment by suvodhoy** [comment]
Hi,

Thanks for the quick revert. Currently I keep all the clients in cache. The serializer used is **pickle**.

**Comment by msaniscalchi** [comment]
I actually wouldn't have recommended serializing/deserializing the client in this way, as it is more secure and reasonably simple to just instantiate the client. Alternatively, I would expect just modifying the client_customer_id to be sufficient for most uses-cases.

We will not be taking steps to restore pickling at this time.
