### ISSUE TITLE
TypeError: __init__() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by marcel-kfzteile24** [googleads/googleads-python-lib#142]
Just the raw File is rasing this error:

`Traceback (most recent call last):
  File "xxx.py", line 22, in <module>
    main(client_id, client_secret, refresh_token, developer_token, user_agent,client_customer_id)
  File "xxx.py", line 17, in main
    adwords_client = adwords.AdWordsClient(developer_token, oauth2_client, user_agent, client_customer_id)
TypeError: __init__() takes 4 positional arguments but 5 were given`

**Comment by msaniscalchi** [comment]
I suspect that this is related to how you are attempting to instantiate the client. I suggest that you check the signature of the AdWordsClient __init__ and verify that you are passing the expected arguments.

In particular, it appears that you are passing the client_customer_id directly, but it is a keyword argument.
