### ISSUE TITLE
SSL3_GET_RECORD:decryption failed or bad record mac

### ISSUE THREAD

**Issue by nibakai** [googleads/googleads-python-lib#143]
We are using the Python package: googleads==4.1.0 to extract data via the Adwords reporting API. We have the same ETL schedule setup for both of our QA and PROD environment. We saw the following error more often recently. Could you provide some guidance to figure out a solution for that.

ERROR:[Errno 1] _ssl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleads/adwords.py", line 1344, in DownloadReportAsStringWithAwql
    return response.read().decode('utf-8')
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! Could you provide some additional details about the environment you're running this in and the version of OpenSSL you're using?

I can't reproduce this behavior on my end, so I recommend reinstalling OpenSSL / Python to verify whether or not this is an issue with your current installation.

Regards,
Mark

**Comment by msaniscalchi** [comment]
I am not certain, but I suspect this may be related to [this issue reported to the AdWords API Support Forum](https://groups.google.com/forum/#!topic/adwords-api/BXnAVhYe538). My understanding is that the issue has since been resolved, but if you're still experiencing issues with reporting like this, feel free to re-open and provide more details.
