### ISSUE TITLE
"UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b" when using DownloadReportAsString

### ISSUE THREAD

**Issue by arlaneenalra** [googleads/googleads-python-lib#144]
We're seeing this randomly in version 4.3.0 right now:

```
Traceback (most recent call last):
  File "/home/kent/kent_etl/adwords/extract.py", line 211, in <module>
    main(adwords_client)
  File "/home/kent/kent_etl/adwords/extract.py", line 43, in main
    result = runClientReports(client, report_downloader, link['clientCustomerId'])
  File "/home/kent/kent_etl/adwords/extract.py", line 78, in runClientReports
    device_report = getReport(report_downloader, 'device')
  File "/home/kent/kent_etl/adwords/extract.py", line 88, in getReport
    report_definition, skip_report_header=True, skip_column_header=False, skip_report_summary=True
  File "/usr/lib/python2.7/site-packages/googleads/common.py", line 404, in Wrapper
    return utility_method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleads/adwords.py", line 1321, in DownloadReportAsString
    return response.read().decode('utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I've tried a couple of things including adding this trick http://stackoverflow.com/a/21470447/876884 without coming up with a solution. Any suggestions would be helpful.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! This is likely the result of running DownloadReportAsString with an incompatible Report Definition; e.g. with a `downloadFormat` set to `GZIPPED_CSV` rather than `CSV`. I'd suggest that you verify whether your code uses the former, and if so, change it to the latter.

Regards,
Mark

**Comment by arlaneenalra** [comment]
I would agree with you except all of the report definitions we're running are set to CSV and nothing changes that and the error seems to come and go.  I.e. we see the error and almost immediately run the code again and don't see it the next time or have it appear in at a different point in the run.  That would seem to indicate a transient happening upstream to cause the problem.  Unfortunately, the we get the utf8 error rather than an indication of what's actually going on at the http level...

**Comment by msaniscalchi** [comment]
I've looked into this a bit more, and [this thread](https://groups.google.com/forum/#!topic/adwords-api/BXnAVhYe538) indicates that there was an issue with reporting (wrong / corrupt data) that seems consistent with what you're suggesting. As of earlier this morning, it has been resolved.

If you're still experiencing this issue, please post there.
