### ISSUE TITLE
_REQUIRED_INIT_VALUES

### ISSUE THREAD

**Issue by kubber** [googleads/googleads-python-lib#148]
adwords.AdWordsClient.LoadFromStorage()
is returning error message :

googleads.errors.GoogleAdsValueError:
is missing some of the required values. Required values are: developer_token, actual values are ['client_secret', 'developer_token', 'client_id', 'user_agent', 'refresh_token']

it works when I change line 219 in googleads/adwords.py
from : 
_REQUIRED_INIT_VALUES = ('developer_token')
to 
_REQUIRED_INIT_VALUES = ('developer_token', )

**Comment by msaniscalchi** [comment]
Hello, thanks for the report! Yes, I see that this somehow sneaked past our tests prior to release. I'll push out a patch shortly to resolve this issue. I'll resolve this comment when it is out.

**Comment by Olmer1st** [comment]
+1

**Comment by msaniscalchi** [comment]
The issue has been resolved.
