### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by sshevlyagin** [googleads/googleads-python-lib#149]
https://github.com/googleads/googleads-python-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)#step-2---setting-up-the-client-library has a typo. 

The line 
```
 scope=oauth2.GetApiScope('adwords')
```
should be
```
 scope=oauth2.GetAPIScope('adwords')
```

**Comment by msaniscalchi** [comment]
Hello, thanks for the report! Good catch! Ironically, in the comments directly above that line, the method name is written correctly. Not sure how that happened. The typo has since been fixed.
