### ISSUE TITLE
Page needs update

### ISSUE THREAD

**Issue by sshevlyagin** [googleads/googleads-python-lib#150]
https://github.com/googleads/googleads-python-lib/wiki/API-access-using-own-credentials-(installed-application-flow) should be updated to include a reference to https://github.com/googleads/googleads-python-lib/blob/master/examples/dfp/authentication/generate_refresh_token.py and how to use it. I wasted a few hours not knowing that it was available :/

**Comment by msaniscalchi** [comment]
Sorry that you had a bad experience getting started. The wiki page has been updated to point to the relevant DFP documentation and sample.

**Comment by sshevlyagin** [comment]
I appreciate the quick resolution!
