### ISSUE TITLE
Why does AdwordsClient automatically refresh the token in the __init__.py method?

### ISSUE THREAD

**Issue by domino14** [googleads/googleads-python-lib#156]
I'd like to call AdwordsClient with an already valid token and manage token refresh myself close to expiry. The default behavior of AdwordsClient seems to be to refresh every single time it's initialized.

**Comment by msaniscalchi** [comment]
Hello,

The reason for this is that the provided `GoogleOAuth2Client` implementations are expected to be initialized with a refresh token that is used to receive a valid access token. It will also refresh the access token as it gets close to expiry. The access token is short-lived, and the expectation is that most users will be using the library for an extended period, so they would benefit from an automatic refresh mechanism.

That said, if you would prefer to handle OAuth 2.0 differently, you are free to create a subclass of `GoogleOAuth2Client` that better meets your specifications.

Regards,
Mark

**Comment by domino14** [comment]
Thanks. I subclassed `GoogleRefreshTokenClient` instead like this:

```python
class GoogleCredentialsClient(GoogleRefreshTokenClient):
    def __init__(self, creds):
        """Initializes a GoogleAccessTokenClient. """
        self.oauth2credentials = creds
        self.proxy_config = ProxyConfig()

    def Refresh(self):
        # The default behavior of AdwordsClient seems to be to call
        # its OAuth2 client's `Refresh` function on initialization.
        # We override it here and only call Refresh if the token has
        # expired. In production use, even that shouldn't happen,
        # because we will refresh access tokens periodically.

        if (self.oauth2credentials.token_expiry is not None and
                self.oauth2credentials.token_expiry <
                datetime.datetime.utcnow()):
            logger.debug('Force refreshing credentials, since they have '
                         'expired.')
            super(GoogleCredentialsClient, self).Refresh()
```

and I use it like

```python
creds = OAuth2Credentials.from_json(credential_json)
oauth2_client = GoogleCredentialsClient(creds)
client = AdWordsClient(developer_token, oauth2_client, user_agent_str)
client.GetReportDownloader(... etc)
```
