### ISSUE TITLE
AssetCreativeTemplateVariableValue sample does not match with doc specs

### ISSUE THREAD

**Issue by jmheist** [googleads/googleads-python-lib#166]
googleads-python-lib/examples/dfp/v201608/creative_service/create_creative_from_template.py

This seems to be outdated as it does not match the doc specs...
https://developers.google.com/doubleclick-publishers/docs/reference/v201608/CreativeService.AssetCreativeTemplateVariableValue

`'creativeTemplateVariableValues': [
          {
              'xsi_type': 'AssetCreativeTemplateVariableValue',
              'uniqueName': 'Imagefile',
              'assetByteArray': image_data,
              'fileName': 'image%s.jpg' % uuid.uuid4()
          }, ...`

**Comment by msaniscalchi** [comment]
Thanks for the report, we'll look into this.

**Comment by thangduo** [comment]
Resolved in 5.1.0 release
