### ISSUE TITLE
     oauth2client.client.SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by CrabbyPete** [googleads/googleads-python-lib#168]
This in the oauth2 file, but oauth2client no longer has it as an attribute

**Comment by msaniscalchi** [comment]
Please see [Issue #110](https://github.com/googleads/googleads-python-lib/issues/110).

**Comment by CrabbyPete** [comment]
As it is the library is broken. Not only is oauth2client at 4.0, but suds has not been updated in 3 years, and I have had problems working
with python3 and multiprocessing. I know that the fix has not been released, but we would be happy to try out any attempt at fixing it
