### ISSUE TITLE
suds.MethodNotFound: Method not found: 'CustomerService.CustomerServiceInterfacePort.get'

### ISSUE THREAD

**Issue by papaben** [googleads/googleads-python-lib#169]
The WSDL for version https://adwords.google.com/api/adwords/mcm/v201609/CustomerService?wsdl does not define a `get` method. The example code found in the releases https://github.com/googleads/googleads-python-lib/releases/tag/4.8.0 --> `adwords_python2_examples/create_adwords_client_without_yaml.py` makes a call to that method on line 50, which results in a suds exception.

```
suds.MethodNotFound: Method not found: 'CustomerService.CustomerServiceInterfacePort.get'
```

I searched through the service binding, but didn't find a suitable substitute method. =/ Maybe `getCustomers()`?

**Comment by msaniscalchi** [comment]
Thanks for the report! It looks like we missed this sample when updating samples using the CustomerService back when v201607 was introduced. We'll fix this in the next release.

**Comment by NabeelahB** [comment]
Could you tell what is the work around for this now? 

Regards,
nabeelah

**Comment by papaben** [comment]
Hi @NabeelahB, you can just select a different method off of the WSDL. For example, instead of `get()`, you can call `getCutomers()`.

**Comment by NabeelahB** [comment]
Thank You :)
