### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by zgelp** [googleads/googleads-python-lib#171]
Hello, i followed everything in tutorial and deployed my app, but when i come to write in credentials, i write everything right (it works manualy from my IDE - it returns campaigns and accounts), it just stops, cleans the Client maneger ID field and nothing happens ( i also tried in chrome incognito mode - results are the same). Here is a pic for more details :
![adwordsproblems](https://cloud.githubusercontent.com/assets/18194862/21765896/cd5a9fd6-d66b-11e6-916f-1b641f088a96.PNG)

This happens when I insert all my credentials, Mananger account ID becomes empty and nothing happens.

**Comment by msaniscalchi** [comment]
Thanks for the report, I'll see if I can reproduce.

**Comment by thangduo** [comment]
Hi @zgelp, could you please provide a link to the tutorial that you followed?

Thanks

**Comment by zgelp** [comment]
Hey @thangduo , i was following [this](https://github.com/googleads/googleads-python-lib/tree/master/examples/adwords/adwords_appengine_demo) tutorial, it all worked when i did it for test purposes in August 2016, but when i tried again in December/Januar it didn't. I will try again tommorow and let you know.

**Comment by thangduo** [comment]
Thanks for clarifying and retrying. Please let me know tomorrow whether you would be able to get it to work.

Thanks

**Comment by zgelp** [comment]
Hello again @thangduo , I tried once again today and it still doesn't work, it's the same issue than before, i come to write in credentials (developer token, id ...), i write it in correcty but when i click "Update credentials", field with "Adwords Maneger Account Id" becomes empty and nothing happens.

**Comment by msaniscalchi** [comment]
As an FYI, I can reproduce the problem. As reported, no error output or anything.

If I had to guess, it's probably some sort of failure to save the credentials. The way the app works, failing to load credentials will bring you to this screen. So if the credentials aren't saved properly, it makes sense that you'd get brought back to this page.

**Comment by msaniscalchi** [comment]
This will be resolved in the next release.
