### ISSUE TITLE
SSL Cerificate Verify Failed

### ISSUE THREAD

**Issue by neil90** [googleads/googleads-python-lib#172]
Hey all,

So I have setup my production manager account along with test manager account and have created a customer as well as a campaign. Now I can run the get_campaign.py script fine on my laptop at home. However when I try to run the script at work I get this error -

  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\htt
plib2-0.9.2-py3.5.egg\httplib2\__init__.py", line 987, in _conn_request
    conn.connect()
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\http\client.py",
line 1260, in connect
    server_hostname=server_hostname)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\ssl.py", line 377
, in wrap_socket
    _context=self)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\ssl.py", line 752
, in __init__
    self.do_handshake()
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\ssl.py", line 988
, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\ssl.py", line 633
, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:645)

Is something I fix as a local admin on my desktop? Or is this an enterprise network issue?

**Comment by msaniscalchi** [comment]
Hello,

There are a few potential explanations for why you're seeing this. If I had to make an educated guess, I'd say that it likely stems from your installation at work not having access to cafiles needed for SSL certificate validation.

While I'm admittedly not certain, this [bug on the Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues/137) seems highly suspicious, even if it is a bit dated. I don't think the core issue is directly related to this library; I suggest verifying that your Python installation can make secure connections. If this error is only reproducible with this library, feel free to report back.

Regards,
Mark

**Comment by neil90** [comment]
@msaniscalchi I have had to do other API requests with python requests module and I have had to disable the SSL verification on it.

**Comment by msaniscalchi** [comment]
Thanks, that confirms my earlier guess. It sounds like your workstation is configured such that SSL certificate validation that was introduced in Python 3 will fail. Based on the stacktrace, it seems like this is related to the library being unable to load ca files.

As far as our library is concerned, I'm pretty confident that it is working as intended. You could disable SSL certificate validation via the googleads.yaml file, but it is not recommended.

**Comment by neil90** [comment]
@msaniscalchi Awesome thanks. Out of curiosity do you know what Key:value I need to put in the yaml file? Im looking at the default one and I can't see what value I'm supposed to put.

**Comment by msaniscalchi** [comment]
It was mostly intended for users of [proxy config](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml#L70), which is where it can be found in the googleads.yaml file. You should be able to ignore the other proxy settings and just set the disable_certificate_validation field.

**Comment by neil90** [comment]
@msaniscalchi I set disable_certificate_validation to True. However now i get this error - 
python get_campaigns.py

C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\googleads-4
.8.0-py3.5.egg\googleads\adwords.py:270: UserWarning: Could not recognize the fo
llowing keys: {'application_name': 'INSERT_APPLICATION_NAME_HERE'}. They were ig
nored.
INFO:oauth2client.client:Refreshing access_token
Traceback (most recent call last):
  File "get_campaigns.py", line 73, in <module>
    adwords_client = adwords.AdWordsClient.LoadFromStorage()
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\goo
gleads-4.8.0-py3.5.egg\googleads\adwords.py", line 270, in LoadFromStorage
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\goo
gleads-4.8.0-py3.5.egg\googleads\adwords.py", line 312, in __init__
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\goo
gleads-4.8.0-py3.5.egg\googleads\oauth2.py", line 158, in Refresh
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\oau
th2client\client.py", line 633, in refresh
    self._refresh(http.request)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\oau
th2client\client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\oau
th2client\client.py", line 874, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\htt
plib2-0.9.2-py3.5.egg\httplib2\__init__.py", line 1196, in request
    self.disable_ssl_certificate_validation)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\site-packages\htt
plib2-0.9.2-py3.5.egg\httplib2\__init__.py", line 850, in __init__
    check_hostname=True)
  File "C:\Users\e659383\AppData\Local\Continuum\Anaconda3\lib\http\client.py",
line 1242, in __init__
    raise ValueError("check_hostname needs a SSL context with "
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT
_REQUIRED

**Comment by msaniscalchi** [comment]
This sounds related to an [httplib2 bug](https://github.com/jcgregorio/httplib2/issues/173) that was resolved a while back. Try updating your installation of httplib2 to a more recent version.
