### ISSUE TITLE
Unmarshalling Error  in GoogleLeads 5.0.0

### ISSUE THREAD

**Issue by nickmetal** [googleads/googleads-python-lib#179]
Hello!
Trying to upload Campaign Location settings (bid adjustment) via CampaignCriterionService( version=v201609, upload single operation without batching processing ) and faced with 500 error. When i read the message from error instance i have this:
`'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unmarshalling Error:  </faultstring></soap:Fault></soap:Body></soap:Envelope>'`
How can i get more informative text about error?

googleads==5.0.0
oauth2client==2.2.0
python==2.7.10

**Comment by thangduo** [comment]
For work arounds, please see: https://github.com/googleads/googleads-python-lib/issues/176

Otherwise, we're putting in a fix so that the actual error is surfaced and not an HTTP 500 error for cases like this.

**Comment by thangduo** [comment]
Resolved in 5.1.0 release
