### ISSUE TITLE
Can't download campaigns

### ISSUE THREAD

**Issue by Arudan** [googleads/googleads-python-lib#189]
we are currently having some issues with the adwords apis.

Using the python library, we’re able to instantiate a client, using a refresh token (with the correct scope) and our developer token.

However, we’re unable to fetch the list of campaigns. The list always returns empty. We’re, however, able to retrive only one ad group and only one ad.

**Comment by msaniscalchi** [comment]
Hello Arudan,

This issue tracker is better suited to answering questions or resolving issues related to the library itself. We provide some limited product support to the extent that it is necessary for troubleshooting certain library behavior, but the issue tracker isn't a support alias for these products.

Given that you are making successful API calls--albeit with some unexpected results--it seems very unlikely that this is a client library issue. Fortunately, there are [AdWords API support forums](https://groups.google.com/forum/#!forum/adwords-api) that can better assist you with these sorts of questions. Please report your issue there.

Regards,
Mark
