### ISSUE TITLE
Uploading operations using batch job service - question

### ISSUE THREAD

**Issue by Olmer1st** [googleads/googleads-python-lib#193]
Hi,

We are using batch job service in order to create full campaigns in Google.
When we do upload operations sometime it take 30 minutes.
For example: 
we have 7k operations: 
1. create budget
2. create many campaigns
3. create many adgroups
4. create ads in adgroups
Everything OK until we start upload. We are look into network monitor and see very small activity for entire 20-25 minutes and after that we see 5 minutes of good progress until the job succeed without errors.
What is the problem? Is it on google side? Or something related to library?
Thanks

**Comment by sfontana** [comment]
Hi @Olmer1st,

It seems a problem on google side, https://groups.google.com/forum/#!searchin/adwords-api/slowjob%7Csort:relevance/adwords-api/Cigj68QDPM8/8fdknhBMDQAJ  (there are other similar threads in that forum)
It seems a chronic problem on google's side.
You can report it there (they will ask for your job ids)

My strategy is to cancel the job is no operations have been executed after x minutes, then I re submit the job and try again, this usually works for me. Of course if you have a lot of operations (>100k) resubmitting may take a long time. but for 7k I think you could try this workaround.

**Comment by msaniscalchi** [comment]
Hello,

Right, although we can assist with issues relating to the implementation of the BatchJobHelper, issues relating to the underlying API are out-of-scope here. Please report these kinds of issues to the [AdWords API support forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark
