### ISSUE TITLE
'[EntityNotFound.INVALID_ID @ operations[0].operand.adGroupId; trigger:'AdGroupId: 42841010522']'

### ISSUE THREAD

**Issue by dnfodjo** [googleads/googleads-python-lib#194]
I can create campaigns and ad groups, but when I attempt to create an ad I receive this error. I have already validate that the adGroupId is correct.

**Comment by msaniscalchi** [comment]
Hello,

I can confirm that an AdGroup with that ID does exist, so it does seem like a potential issue. That said, this issue tracker is only intended to handle issues or questions relating to this library. Based on that error response, I can confirm that this client library did correctly send an API request and parse the API's error response. The core issue here seems to be that the API did something unexpected--i.e. failing to add a creative when provided what appears to be a valid AdGroup ID.

For issues related to the API, please post to the [AdWords API support forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark
