### ISSUE TITLE
Problematic shebangs in example files.

### ISSUE THREAD

**Issue by mpaolino** [googleads/googleads-python-lib#198]
`#!/usr/bin/python` does not work well with virtualenvs. You could use `#!/usr/bin/env python`.

To reproduce, create a fresh virtualenv, source it, do a `python setup.py build install`, try to run any example, you'll see that googleads package can't be found. Thats because its using the system's python interpreter instead of the virtualenv one. My suggestion is either change it or remove execution permissions on the files and force people to call it with `python <path_to_example.py` so it would use the correct python interpreter.

**Comment by msaniscalchi** [comment]
Thanks Miguel, we'll look into this.
