### ISSUE TITLE
CLIENT_CUSTOMER_ID is required

### ISSUE THREAD

**Issue by gjainumbs** [googleads/googleads-python-lib#201]
I'm testing the following script:

https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201702/basic_operations/get_campaigns.py

it errors out with the message 
CLIENT_CUSTOMER_ID_IS_REQUIRED

Seems the error happens at line 42:
campaign_service = client.GetService('CampaignService', version='v201702')

Will appreciate any pointers

**Comment by msaniscalchi** [comment]
Thanks for the report! It seems like the error you're receiving is [produced by the API](https://developers.google.com/adwords/api/docs/common-errors#AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED); i.e. the client library is making an API call and the API responds with that error message.

Generally speaking, you need to specify a client customer ID for most AdWords API calls. This client library allows you to specify that via a [configuration file](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml) that initializes your `AdWordsClient` via the `LoadFromStorage` method. By default, this will attempt to load a configuration file named **googleads.yaml** from your home directory.

As a first step, I suggest that you verify that the `client_customer_id` optional field under `adwords` has been set.

Regards,
Mark

**Comment by gjainumbs** [comment]
setting client_customer_id solved it
