### ISSUE TITLE
How to get the authorization code in the response as a query string in the python code 

### ISSUE THREAD

**Issue by R-Sila** [googleads/googleads-python-lib#202]

**Comment by msaniscalchi** [comment]
Hello,

We offer code samples stepping through the authorization process for [AdWords](https://github.com/googleads/googleads-python-lib/tree/master/examples/adwords/authentication) and [DFP](https://github.com/googleads/googleads-python-lib/tree/master/examples/dfp/authentication). You can use these as a reference for stepping through the Installed Application OAuth 2.0 flow.

Regards,
Mark
