### ISSUE TITLE
How to get the client_customer_id tied to the credentials after authenticating to adwords 

### ISSUE THREAD

**Issue by R-Sila** [googleads/googleads-python-lib#204]

**Comment by msaniscalchi** [comment]
Hello,

The `clientCustomerId` is not tied to your credentials; if it is provided, it is sent along in the SOAP headers in your API requests.

You can use the [`LoadFromStorage`](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L250) method to load a [configuration file](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml#L10), by default it will load from your home directory. As you may have noticed, the configuration file allows you to set a `client_customer_id` field. Of course, if you're configuring the client manually, it is also possible to provide this as a [keyword argument](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L289).

Regards,
Mark

**Comment by dklimkin** [comment]
I understand it's more of a question how to obtain a CID if only OAuth data is available.

@R-Sila, you can use [CustomerService](https://developers.google.com/adwords/api/docs/reference/v201702/CustomerService) for it. It doesn't require CID and returns array of CIDs directly for the account. If it's an MCC account, you can then use [ManagedCustomerService](https://developers.google.com/adwords/api/docs/reference/v201702/ManagedCustomerService) to explore the hierarchy further.

As this is not library-specific, please refer to the [support forum](https://groups.google.com/forum/#!forum/adwords-api) with similar questions in the future.
