### ISSUE TITLE
"xsi_type: Platform" is not valid anymore for AdgroupBidModifier operations

### ISSUE THREAD

**Issue by ArrowsX** [googleads/googleads-python-lib#207]
Not really sure what happened here, but `advanced_operations/add_ad_group_bid_modifier.py` is not working at all. Might need to check if this is an API problem.

EDIT: I couldn't edit my comments before because my browser addons made some weird things, but I showed the error in my next message.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! I'm actually pretty stumped on this, as the example works fine on my end and Platform should still be valid. I suspect this is an API issue as well, but it might not be a bad idea for me to see the error output if you want me to investigate.

At any rate, I recommend reporting API issues to the [AdWords Support Forum](https://groups.google.com/forum/#!forum/adwords-api). We only focus on issues with the client library here.

**Comment by jradcliff** [comment]
Hi,

I just tried this example for v201607 and v201702, and in both cases it ran successfully. Could you let me know the versions you're using for the AdWords API and the Python client library?

Thanks,
Josh, AdWords API Team

**Comment by ArrowsX** [comment]
Just realized I was using the wrong service this whole time. I had two functions `update_bids(operations)` and `update_bid_modifiers(operations)` and didn't realize it for 2 months. Well, money was spent/saved badly....

Both Adwords API and the Python Client are working wonderfully now.
