### ISSUE TITLE
is it possible to have geoperformance and age range performance per Ad ?

### ISSUE THREAD

**Issue by R-Sila** [googleads/googleads-python-lib#209]
I was seraching in the doc and i found that in this types of report only the AdGroupId and CampaignId can be specified, i wonder if there is a way to have the Ad Id ?

**Comment by msaniscalchi** [comment]
Hello,

Please direct your product-specific questions to the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api). This issue tracker is better suited to resolving issues specifically related to the Python client library.

Regards,
Mark
