### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Rawkeyzer** [googleads/googleads-python-lib#211]
I'm currently authenticating without the googleads.yaml file.
While trying to retrieve a report (which was working just fine) I suddenly got the
following error:  
**urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>**

I changed absolutely nothing in the code, and while trying to find the issue I found out this piece of code is causing the issue:

    oauth2_client = oauth2.GoogleRefreshTokenClient(client_id, client_secret, refresh_token)

    adwords_client = adwords.AdWordsClient(
        developer_token, oauth2_client, user_agent,
        client_customer_id=client_customer_id)

    customer_service = adwords_client.GetService('CustomerService', version='v201702')

    customers = customer_service.getCustomers()

    print ('You are logged in as a user with access to the following customers:')

    for customer in customers:
        print ('\t%s' % customer['customerId'])
    return adwords_client`

Does anybody know how to fix this?

Note: while trying to look for the issue I tried to update the client by doing: 
`pip install googleads --upgrade`
After that I did get an update for a newer version of oauthclient.. could this have something to do with it?

**Comment by msaniscalchi** [comment]
Hello,

You appear to be referencing the [create_adwords_client_without_yaml.py](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/authentication/create_adwords_client_without_yaml.py#L41) example. Something like a stacktrace might give more insight for your issue.

That said, I can't reproduce your issue on my end with that same example--both with legacy (1.4.12) and current (4.0.0+) versions of oauth2client. I occasionally see similar reports when users install or upgrade oauth2client. A clean reinstall usually resolves the issue. Could you give that a try?

Regards,
Mark

**Comment by Rawkeyzer** [comment]
Hi Mark, 

Thanks for the reply.
I am indeed referencing to te example code.
The stack trace can be found here: [https://pastebin.com/mB7FMMqM](url)

For the second time, I did a clean install but no luck..still getting the error.
Could it be that I'm missing the adwords certificate?

**Comment by msaniscalchi** [comment]
Looking at that stacktrace, it doesn't seem to be related to oauth2client at all. The client is making the GetService call, but then fails to get the WSDL because urllib raises the URLError with the "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed" message.

Although you haven't changed the underlying code, is it possible that your environment has changed in some way since you last successfully ran this? Given that this seems like an environment issue, it might not be a bad idea to go a step further and try again with a fresh installation of Python.

**Comment by Rawkeyzer** [comment]
I dare to say I'm 1000 percent sure nothing in my environment changed.
I was only coding and refreshed my browser to see the changes and there came the error.
Two seconds before everything was fine!
Like you suggested, I reinstalled python two times now with no luck.

**Comment by dklimkin** [comment]
Hi Rawkeyzer,

What environment are you running, OS, python version?

**Comment by Rawkeyzer** [comment]
I got it to work! Don't exactly know how..reinstalled everything again,
updated anything I could possibly find to update. Even updated windows 10.
It's working fine now, the issue can be closed.
Though I find it very strange this happened out of nowhere.
Thanks for helping out

**Comment by msaniscalchi** [comment]
I'm glad you got it working again. Although pinpointing the precise cause for an issue like this is tough. I don't think it is directly related to our library, but it sounds like your environment quietly changed in some way that broke things.

Feel free to report again if you encounter future instances of this.
