### ISSUE TITLE
suds.WebFault not inidcating error when thrown

### ISSUE THREAD

**Issue by mthoma5** [googleads/googleads-python-lib#215]
Hi, 

I am trying to generate an AdExchange creative, but when the createCrearitive method is called, I am receiving the following error:

suds.WebFault: Server raised fault: '[ServerError.SERVER_ERROR @ ]'.

Usually, i can trck down the error via the @ ..., but I am not sure whats wrong here. Maybe it is in the json i am sending? 

size = {
        "width":width,
        "height":height
    }
adx_creative_asset = {
        "xsi_type" : "AdExchangeCreative",
        "name":creative_name,
        "advertiserId":advertiser_id,
        "size":size,
    }

Any help would be appreciated.

**Comment by grivescorbett** [comment]
Hello,

This looks like an API issue as opposed a client library problem. Feel free to get in touch with us at dfpapi-support@google.com. Please include full soap logs from your request and we'll figure out your issue.

Thanks!
Gabe

**Comment by hunterli** [comment]
Meet same issue. Any progress can be sharing?

**Comment by christopherseeley** [comment]
For help with server errors, please post in the [Ad Manager API forum](https://groups.google.com/g/google-doubleclick-for-publishers-api).

**Comment by hunterli** [comment]
Thanks a lot, I found the answer in the [Ad Manager API forum](https://groups.google.com/g/google-doubleclick-for-publishers-api): "codeSnippet" can not be empty!
```
size = {
"width":width,
"height":height
}
adx_creative_asset = {
"xsi_type" : "AdExchangeCreative",
"name":creative_name,
"advertiserId":advertiser_id,
"size":size,
"codeSnippet": "// Just a comment",
}
```
