### ISSUE TITLE
adwords/api/docs/clientlibraries: PyPI link needs review

### ISSUE THREAD

**Issue by ncouture** [googleads/googleads-python-lib#221]
The link on https://developers.google.com/adwords/api/docs/clientlibraries named PyPI should likely point to https://github.com/googleads/googleads-python-lib#getting-started as intended.

**Comment by msaniscalchi** [comment]
Thanks for the report!

You're right that the link seems to be wrong, although I disagree about it linking to the getting started guide. The PyPI link is intended to link to the [PyPI repository](https://pypi.python.org/pypi/googleads). We'll fix that.

Regards,
Mark
