### ISSUE TITLE
AttributeError: 'module' object has no attribute 'StatementBuilder'

### ISSUE THREAD

**Issue by MDG2600** [googleads/googleads-python-lib#225]
I'm just starting out in python and running into this error when I try to run the activate_line_items.py. I'm sure it's super basic but any help is appreciated.

**Comment by grivescorbett** [comment]
Hello! Please try upgrading the version of the library you are using:

`$ pip install --upgrade googleads`

StatementBuilder is a recent addition and you may not have it in the version currently on your machine.
