### ISSUE TITLE
Migrate to google.auth

### ISSUE THREAD

**Issue by dymov** [googleads/googleads-python-lib#226]
Hi,

We are trying to migrate from the deprecated oauth2client. This is one of the libraries that explicitly requires it. Would you consider making the dependency optional or even migrating outright?

**Comment by msaniscalchi** [comment]
Sure, we're exploring options for migrating off of oauth2client right now, actually. I can't make any promises on google.auth *right now*, but it's one of the options we're looking at.

On a side note, although we don't explicitly support other libraries such as google.auth at the moment, you can make your own implementation(s) of GoogleOAuth2Client to work around this.

**Comment by msaniscalchi** [comment]
As an FYI, this is now prioritized. We plan on removing support for oauth2client and migrating to google-auth in an upcoming release.

**Comment by msaniscalchi** [comment]
The migration is complete.
