### ISSUE TITLE
OfflineDataUploadService doesn't seem to be implemented.

### ISSUE THREAD

**Issue by stevewilhelm** [googleads/googleads-python-lib#228]
The OfflineDataUploadService and OfflineData do not seem to be implemented.

See the following for details:
https://developers.google.com/adwords/api/docs/reference/v201708/OfflineDataUploadService

**Comment by msaniscalchi** [comment]
Hello Steve,

The linked docs indicate this is a whitelist-only feature. It's possible that you're not included in that whitelist, which would explain why you're having trouble making API calls.

It's not unusual for the library to include whitelisted services like this, so I think this is working as intended.

Regards,
Mark

**Comment by stevewilhelm** [comment]
I am aware this is a whitelisted feature. 

If you look at the implementation, there is only one reference to OfflineDataUploadService in the code base, namely in the _SERVICE_MAP. 

There doesn't seem to be any other code to implement the service or any code implementing the argument to necessary to make the calls to the service, e.g. OfflineData.

I notice some of the other API implementations, PHP and Java for example, seem to have more complete support for OfflineDataUploadService.

**Comment by msaniscalchi** [comment]
> If you look at the implementation, there is only one reference to OfflineDataUploadService in the code base, namely in the _SERVICE_MAP.

Yes, this doesn't sound unusual. This library isn't generated like the Java client library, it downloads the wsdl (or retrieves it from cache) and creates the service dynamically. Consequently, this library also doesn't have generated DTOs for API objects like OfflineData. This library uses suds, which does offer some factories to produce these, we discuss this a bit [here](https://github.com/googleads/googleads-python-lib#im-familiar-with-suds-can-i-use-suds-features-with-this-library).

**Comment by stevewilhelm** [comment]
We get the following error:

```
    offline_data_upload_service = adwords_client.GetService('OfflineDataUploadService', version=constants.VERSION)
  File "build/bdist.macosx-10.11-x86_64/egg/googleads/adwords.py", line 402, in GetService
  File "build/bdist.macosx-10.11-x86_64/egg/suds/client.py", line 115, in __init__
  File "build/bdist.macosx-10.11-x86_64/egg/suds/reader.py", line 150, in open
  File "build/bdist.macosx-10.11-x86_64/egg/suds/wsdl.py", line 136, in __init__
  File "build/bdist.macosx-10.11-x86_64/egg/suds/reader.py", line 74, in open
  File "build/bdist.macosx-10.11-x86_64/egg/suds/reader.py", line 92, in download
  File "build/bdist.macosx-10.11-x86_64/egg/suds/transport/http.py", line 69, in open
suds.transport.TransportError: HTTP Error 404: Not Found
```
Is this what we should expect if we are not correctly accessing our whitelisted account?

**Comment by msaniscalchi** [comment]
Thanks for following up Steve. It looks like you uncovered an issue that I'm surprised wasn't uncovered earlier.

This is the actual wsdl URL:
https://adwords.google.com/api/adwords/rm/v201708/OfflineDataUploadService?wsdl

This is the wsdl URL being used:
https://adwords.google.com/api/adwords/cm/v201708/OfflineDataUploadService?wsdl

It appears that an error was made when this service was added to `_SERVICE_MAP`. As a temporary work-around, you can modify the value associated with this service to `rm`.

We're going to be releasing a new AdWords version soon, so we'll include the fix in that release.

Regards,
Mark

**Comment by stevewilhelm** [comment]
Patching the wsdl URL works!

```WARNING:root:<googleads.common.SudsServiceProxy object at 0x109afc750>
WARNING:root:
Suds ( https://fedorahosted.org/suds/ )  version: 0.6

Service ( OfflineDataUploadService ) tns="https://adwords.google.com/api/adwords/rm/v201708"
   Prefixes (2)
      ns0 = "https://adwords.google.com/api/adwords/cm/v201708"
      ns1 = "https://adwords.google.com/api/adwords/rm/v201708"
   Ports (1):
      (OfflineDataUploadServiceInterfacePort)
         Methods (2):
            get(ns0:Selector serviceSelector)
            mutate(OfflineDataUploadOperation[] operations)
         Types (92):
            ns0:ApiError
            ns0:ApiException
```

Now I just need to bone up on suds. Thanks.
