### ISSUE TITLE
Typo in add_keywords_using_incremental_batch_job.py

### ISSUE THREAD

**Issue by ReptilianBrain** [googleads/googleads-python-lib#229]
This seems to affect all api versions in the adwords/examples/v2017*/campaign_management directory 

The comment on line 19 are not accurately describing what this python file actually does. It looks more like the description for add_complete_campaigns_using_batch_job.

```python
"""This uses the BatchJobService to incrementally create a complete Campaign.

The complete Campaign created by this example also includes AdGroups and
KeyWords.

"""
```

**Comment by msaniscalchi** [comment]
Thanks for the report! I suppose there may have been some duplication due to the similar structure for those examples. It looks like the comments didn't get properly refactored. Sure, we'll fix this in an upcoming release.
