### ISSUE TITLE
Results from last soap request are stored indefinitely on the service object

### ISSUE THREAD

**Issue by tterrace** [googleads/googleads-python-lib#233]
Hi, I'm not sure if this was intended but once a service object has been built and a request issued, the results are stored in memory through the service object even if the application `del`s the returned data structure:

```python
import suds.cache
from googleads.adwords import AdWordsClient
from googleads.oauth2 import GoogleRefreshTokenClient

client = AdWordsClient(
    developer_token,
    GoogleRefreshTokenClient(
        client_id,
        client_secret,
        refresh_token,
    ),
    user_agent,
    cache=suds.cache.ObjectCache(
        location=suds_cache_path,
        **suds_cache_duration
    )
)

client.SetClientCustomerId(customer_id)

service = client.GetService(service_name, version=service_version, server=server)
service.get(predicates) # note that the result is dropped on the floor here

for child in service._method_proxies['get'].__closure__[1].cell_contents.method.binding['input'].multiref.nodes[0].children[0].children:
    print(child) # prints out the results of the previous service.get call
```

I'm finding this to be a problem because in my application I frequently keep the service objects around to avoid the overhead of loading the WSDL. The memory from 25 cached soap services, all holding their latest result set, can eat up a lot of resources on my servers. I'm running `googleads==6.1.0` in production, but I'm able to reproduce the same behavior on `googleads==8.1.0`.

Here's a snippet of my objgraph output, if it helps any:

![image](https://user-images.githubusercontent.com/6719894/32250531-478fa46a-be63-11e7-9dd0-ac770d4189d8.png)

Thanks!

**Comment by tterrace** [comment]
As a side note, I was going to ditch my service caching in favor of using the ObjectCache to reduce the impact of loading the WSDL repeatedly, but it seems like the `AdWordsClient.GetService` method needs to provide `cachingpolicy=1` as a kwarg to `suds.client.Client` for the cache to work. Otherwise this bit in the `suds.reader.DefinitionReader` class will override the passed-in cache and set it to NoCache:

```
    def cache(self):
        """
        Get the cache.
        @return: The I{cache} when I{cachingpolicy} = B{1}.
        @rtype: L{Cache}
        """
        if self.options.cachingpolicy == 1:
            return self.options.cache
        return NoCache()
```

Here's the piece in adwords.py that i think needs the extra kwarg:

https://github.com/googleads/googleads-python-lib/blob/18c083ca1c7657dd13c8f67c120ad550d5964dd5/googleads/adwords.py#L443-L453

If you agree I'd be happy to provide a PR

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! This issue sounds more directly related to the **suds-jurko** project, but I think it is probably intended behavior because storing and returning the last sent request and last received response [has been a feature of suds for a while](https://jortel.fedorapeople.org/suds/doc/suds.client-pysrc.html#Client.last_received).

If this were really problematic for you, one option could be to modify your client to remove the stored messages. I think doing that would be out of scope for this library though.

Regards,
Mark

**Comment by tterrace** [comment]
Thanks Mark! I'll mention it over there and see what they say.

**Comment by topher200** [comment]
Link to the discussion in the suds repo: https://bitbucket.org/jurko/suds/issues/134/multiref-in-sudsbinding-retains-last-soap
