### ISSUE TITLE
DFP API in GAE

### ISSUE THREAD

**Issue by rororo12** [googleads/googleads-python-lib#234]
How to use DFP API in GAE?

I get a error because pyopenssl is not available.

```
NotImplementedError: 
This library only implements PKCS#12 support via the pyOpenSSL library.
Either install pyOpenSSL, or please convert the .p12 file
```

**Comment by grivescorbett** [comment]
Hello!

Thanks for writing in. Are you using a p12 file for authentication? We recommend you use a JSON service account file, please take a look at the python directions in the [getting started guide](https://developers.google.com/doubleclick-publishers/docs/start).

If you're using App Engine Flex, this is all you should need to do. If you're using App Engine standard, be sure to vendor your dependencies.

In the future, GitHub issues are best for reporting bugs in the library. For support, please use the [DFP API forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) or send an email to dfpapi-support@google.com

Best,
Gabe
