### ISSUE TITLE
JS SDK?

### ISSUE THREAD

**Issue by cameronroe** [googleads/googleads-python-lib#235]
Nice to see we have this in python. Any redirect to comment regarding a JS SDK for Browser/Node?

**Comment by msaniscalchi** [comment]
Hello Cameron,

You can find our supported languages on the [Client Libraries page in our documentation](https://developers.google.com/adwords/api/docs/clientlibraries). At this time, there is no officially supported JS library for AdWords or DFP. In the event that we do create one in the future, we would announce its release on the [Google Ads Developer Blog](http://googleadsdeveloper.blogspot.com/). That said, there are no imminent plans for this right now.

Perhaps [AdWords Scripts](https://developers.google.com/adwords/scripts/)--assuming you're an AdWords user--would be closer to what you're looking for.

Regards,
Mark
