### ISSUE TITLE
AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED raised when adding members to CRM-based user list

### ISSUE THREAD

**Issue by ursan** [googleads/googleads-python-lib#240]
API version: `v201710`
output of `pip show googleads`:

```
Name: googleads
Version: 9.0.0
Summary: Google Ads Python Client Library
Home-page: https://github.com/googleads/googleads-python-lib
Author: Mark Saniscalchi
Author-email: api.msaniscalchi@gmail.com
License: Apache License 2.0
```

I am trying to add hashed emails to a CRM-based user list, calling mutateMembers in a loop to upload by chunks, but some of the chunks do not get uploaded and for those the following message is returned:

> Server raised fault: '[AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>']'

I tried a few times, and it doesn't seem to follow any particular pattern.
I also tried adding a delay between each chunk, but same result.

Am I missing something? Could it possibly be a connection problem from our server?

**Comment by msaniscalchi** [comment]
It is odd that there's no trigger specified in that error. Have you checked the logs to verify whether the `clientCustomerId` was specified for these requests?

**Comment by ursan** [comment]
I hadn't set the `clientCustomerId` up in the `googleads.yaml` as the field is described as optional, but it seems that specifying it fixed the issue. thanks!
