### ISSUE TITLE
Not clear guide on how to manage my customers AdWords Campaigns.

### ISSUE THREAD

**Issue by EnyMan** [googleads/googleads-python-lib#245]
Hello, we are developing web application that would automate some campaign management task. But I have trouble figuring out how to do this. We use django and django-allauth to auth our customers, and with django-allauth i get access-token and refresh-token, but with only these two I am unable to access the customers AdWords account. I followed the guide but to no avail as it's not really good in my opinion. I made developer token, and have my client-id and my client-secret. But even with these five things, I am still unable to access the users AdWords account. What do I need to do to access the customers AdWords account?

Many thanks for any help or guidance.

**Comment by msaniscalchi** [comment]
Hello,

Sorry to hear you found one of the guides unhelpful. Provided that you are using an access token that was authorized by a customer's Google Account (which is associated to the AdWords account), I would expect you would be able to access the customer's account with those credentials.

This seems to be more of an API support question concerning AdWords, as opposed to a client library issue. I'd recommend reaching out to the API support team for guidance on this; you can reach out to them via the [AdWords API Support Forum](https://groups.google.com/forum/#!forum/adwords-api). Also, feel free to identify the specific guide that you found lacking, as the AdWords team can take a look and potentially improve on it.

Regards,
Mark

**Comment by msaniscalchi** [comment]
This seems to have been resolved, feel free to reopen if there's more I can do to help regarding this issue.
