### ISSUE TITLE
DFP API Proxy Configuration setup error

### ISSUE THREAD

**Issue by nareshdacha** [googleads/googleads-python-lib#247]
Hi, 
I have used the below code to call DFP API and it's working fine without proxy configuration. But when I use proxy config its throwing errors. Could you please take a look and suggest on this? Thanks in advance

Code:
import tempfile
import os
import datetime
import time
import gzip
import logging
import googleads
from datetime import date
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from googleads import dfp
from googleads import oauth2
from googleads import errors
from googleads import common

client_id = 'XXXXXXXXXXXXXXXX'
client_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
refresh_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
networkCode='XXX'
		
application_name = 'XXXX'

logtimestr = time.strftime("%Y%m%d-%H%M%S")
LOG_FILENAME = "NGPFiscalForecast" + str(logtimestr) + ".log"
logging.basicConfig(filename=LOG_FILENAME,level=logging.INFO)
logging.info('STEP 001 : Started ----- NGPFiscalForecast DFP Report Service -----')	

def dfp_api_client_authorization():
  logging.info('STEP 002 : Checking DFP Authraization - Executing dfp_api_client_authorization')	
  **https_proxy = common.ProxyConfig.Proxy(host='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', port='XXXXXX')
  proxy = common.ProxyConfig(https_proxy=https_proxy, http_proxy=https_proxy)
  oauth2_client = oauth2.GoogleRefreshTokenClient(
      client_id, client_secret, refresh_token,proxy_config=proxy)**
  dfp_client = dfp.DfpClient(oauth2_client, application_name,networkCode)
  return dfp_client

def main(client):
 
  network_service = client.GetService('NetworkService', version='v201708')
  networks = network_service.getAllNetworks()
  for network in **networks:**
    print ('Network with network code \'%s\' and display name \'%s\' was found.'
            % (network['networkCode'], network['displayName']))
    print ('\nNumber of results found: %s' % len(networks))
	
if __name__ == '__main__':
  dfp_client = dfp_api_client_authorization()
  main(dfp_client)

Error:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 1279, in connect
    super().connect()
  File "/usr/lib64/python3.4/http/client.py", line 871, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python3.4/socket.py", line 516, in create_connection
    raise err
  File "/usr/lib64/python3.4/socket.py", line 507, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by grivescorbett** [comment]
Hi,

Thanks for writing in! This doesn't immediately look like a bug in the library, so I'd like to kindly direct you to our API forums: https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api

We're happy to support you in your useage of our library over there.

Thanks!
