### ISSUE TITLE
Calling ReportService through a managed NAT resulting in closed connections

### ISSUE THREAD

**Issue by oaustegard** [googleads/googleads-python-lib#250]
We have attempted to utilize both this and the Java lib to download DFP reports from the ReportService through a managed NAT service, whose default timeout is 350 seconds. The absence of a [Keep-Alive header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive) on the http call forces the NAT to drop our connection prematurely.

https://github.com/googleads/googleads-python-lib/blob/master/googleads/common.py#L681 sets the socket timeout of the call to 1 hr, and this allows us to download the report from a public subnet, but our process must run behind the NAT and we're thus stymied with the current code base.

Is it possible to either a) add a Keep-Alive header with a similar timeout as in L681, or b) allow users to pass in the needed headers as part of the call? We'd hate to have to edit and keep synchronized changes to the library. 

Thanks!
Oskar

**Comment by grivescorbett** [comment]
Hey Oskar!

Thanks for writing in, I haven't heard this use case before. Just to be sure I fully understand, you'd like to be able to insert a custom http header in the request to the report download URL that's generated [here](https://github.com/googleads/googleads-python-lib/blob/master/googleads/dfp.py#L804)? Do you have a similar desire to do so with the soap request http headers set [here](https://github.com/googleads/googleads-python-lib/blob/master/googleads/dfp.py#L361)?

Best,
Gabe

**Comment by oaustegard** [comment]
Gabe, thanks for the response. To be honest I tried following the logic in Github between suds and the various googleads classes and got a bit turned around*. Rather than proposing a solution at this point (we may get to that later) I want to simply clarify the problem: while our socket timeout is adequate, the absence of a keep-alive header forces the NAT gateway to drop the connection after 350 seconds. As such we would want the ability to add the keep-alive headers to _any_ connection we find timing out. To date that's happening while asking for a specific report to be generated, and for the download of said report.

*One thought that did occur to me was that perhaps the change in code could happen on the suds code itself in https://github.com/googleads/googleads-python-lib/blob/master/googleads/util.py rather than in the common.py codebase. If we do end up having to monkeypatch the library, that may be the approach we take, but we'd obviously prefer a clean solution.



________________________________

**Comment by oaustegard** [comment]
An update on this - while we would still like the library to handle keep-alives (or allowing us to specify it as a header parameter, without the need for us to alter the library code), one of our intrepid platform engineers came up with a workaround:

```python
import httplib

orig_connect = httplib.HTTPConnection.connect
def monkey_connect(self):
    orig_connect(self)
    self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 30)
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, 10)
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, 6)
httplib.HTTPConnection.connect = monkey_connect
```

Basically we're keeping the NAT Gateway open by sending dummy requests through it with the appropriate header. A hack, but appears to work.

**Comment by grivescorbett** [comment]
Hey Oskar,

Apologies for the delay, but I'm glad you're unblocked. This doesn't look the same as setting an HTTP header to me though, is this really what you were after? Exposing the raw socket is pretty different to exposing support for custom headers.

**Comment by oaustegard** [comment]
Well, as I say above, rather than prescribing a specific solution I wanted a way to successfully download the data through a gateway that enforces a time-out. This lower level hack appears to do the work, but as I also state, ideally this would be settable by the consumer of the SDK. Monkey patching anything is never ideal.

-- Oskar
301.675.2831
________________________________

**Comment by grivescorbett** [comment]
Hey Oskar,

I hear you, I did not know that you could specify socket flags like that using HTTP headers. Again I'm happy that you're unblocked, and we'll explore building this properly into the library.

**Comment by grivescorbett** [comment]
Hi Oskar,

Quick update: we've agreed on an API and I've begun working on this feature.

Cheers!
Gabe

**Comment by oaustegard** [comment]
Excellent! I look forward to being able to strip our hack and replace with the formal library upgrade!

**Comment by msaniscalchi** [comment]
This was fixed in the last release.
