### ISSUE TITLE
Dont gettin refresh_token for WEB offline

### ISSUE THREAD

**Issue by t4r7s** [googleads/googleads-python-lib#258]
I use [this doc](https://github.com/googleads/googleads-python-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)).

The code below:

flow = client.OAuth2WebServerFlow(
    client_id=client_id,
    client_secret=client_secret,
    scope=oauth2.GetAPIScope('adwords'),
    user_agent='Test',
    access_type="offline",
    redirect_uri="http://my_actual_site.com"
)
auth_code = 'got code here'
auth_uri = flow.step1_get_authorize_url()
credentials = flow.step2_exchange(auth_code)
credentials.to_json()

**"refresh_token": null**

What can I do in this situation?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! So just to clarify, you're saying that following the steps in that guide are causing you to receive a null refresh token?

> auth_code = 'got code here'

How do you get `auth_code` before retrieving the authorization URL? If the code weren't valid, that might explain the problem. Do you actually get to the authorization step seen in the guide? Your web app actually needs to redirect the user to that page.

Regards,
Mark

**Comment by t4r7s** [comment]
Yes, of cource, first I go via link, then authorize with my Google account, then I get a callback to http://my_actual_site.com?code=got code here
And copy paste this to code to my python source. Then run:
auth_code = 'got code here'
auth_uri = flow.step1_get_authorize_url()
credentials = flow.step2_exchange(auth_code)
credentials.to_json()

I tryed this prosedure many times. And result the same "refresh_token": null.

**Comment by msaniscalchi** [comment]
I think there may be a misunderstanding here concerning the [**Installed Application**](https://developers.google.com/identity/protocols/OAuth2#installed) vs. [**Web Server**](https://developers.google.com/identity/protocols/OAuth2#webserver) OAuth 2.0 flows.

> ...first I go via link, then authorize with my Google account, then I get a callback to http://my_actual_site.com?code=got code here

So far, this sounds correct for the Web Server flow.

> And copy paste this code to my python source. Then run:
auth_code = 'got code here'
auth_uri = flow.step1_get_authorize_url()
credentials = flow.step2_exchange(auth_code)
credentials.to_json()

The callback URL should redirect your browser to the specified redirect URL for your web application, you shouldn't need to paste this anywhere. Your web app should be configured to handle this step.

> auth_uri = flow.step1_get_authorize_url()

You don't need to call this again after having already retrieved the `auth_code`. Also, I'm curious on how long you have been using the `auth_code`. That is intended to be a very short-lived token, and shouldn't be reused. If you have used it previously, or waited some time before using it, that could explain why you aren't retrieving a refresh token.

**Comment by msaniscalchi** [comment]
I'll close this now with the expectation that you worked through the issue following my last reply. Feel free to reopen if this library has some OAuth 2.0-related issue that's preventing you from progressing.
