### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by santiruffino** [googleads/googleads-python-lib#259]
`WARNING:googleads.common:Your default encoding, cp1252, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.
DEBUG:suds.transport.http:opening (https://adwords.google.com/api/adwords/cm/v201710/CampaignService?wsdl)
INFO:oauth2client.client:Refreshing access_token
INFO:googleads.common:Request summary - {'methodName': get, 'clientCustomerId': 406-736-8627}
DEBUG:suds.transport.http:sending:
URL: https://adwords.google.com/api/adwords/cm/v201710/CampaignService
HEADERS: {'Content-Type': 'text/xml; charset=utf-8', 'SOAPAction': b'""', 'Authorization': 'REDACTED', 'Content-type': 'text/xml; charset=utf-8', 'Soapaction': b'""'}
MESSAGE:
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="https://adwords.google.com/api/adwords/cm/v201710" xmlns:ns0="https://adwords.google.com/api/adwords/cm/v201710" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header><tns:RequestHeader><tns:clientCustomerId>406-736-8627</tns:clientCustomerId><tns:developerToken>REDACTED</tns:developerToken><tns:userAgent>unknown (AwApi-Python, googleads/9.0.0, Python/3.6.2)</tns:userAgent><tns:validateOnly>false</tns:validateOnly><tns:partialFailure>false</tns:partialFailure></tns:RequestHeader></SOAP-ENV:Header><ns1:Body><ns0:get><ns0:serviceSelector><ns0:fields>Id</ns0:fields><ns0:fields>Name</ns0:fields><ns0:fields>Status</ns0:fields><ns0:paging><ns0:startIndex>0</ns0:startIndex><ns0:numberResults>100</ns0:numberResults></ns0:paging></ns0:serviceSelector></ns0:get></ns1:Body></SOAP-ENV:Envelope>
DEBUG:suds.transport.http:received:
CODE: 200
HEADERS: Content-Type: text/xml; charset=UTF-8
Date: Wed, 14 Mar 2018 14:08:54 GMT
Expires: Wed, 14 Mar 2018 14:08:54 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35"
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

MESSAGE:
b'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201710"><requestId>0005675fea4fa7200a37d1cded082532</requestId><serviceName>CampaignService</serviceName><methodName>get</methodName><operations>1</operations><responseTime>199</responseTime></ResponseHeader></soap:Header><soap:Body><getResponse xmlns="https://adwords.google.com/api/adwords/cm/v201710"><rval><totalNumEntries>4</totalNumEntries><Page.Type>CampaignPage</Page.Type><entries><id>1065092148</id><name>Campaign #1</name><status>ENABLED</status><budget></budget></entries><entries><id>1065460303</id><name>Interplanetary Cruise #e8f5dfad-abc7-4fa8-ad2b-c5ae66687031</name><status>PAUSED</status><budget></budget></entries><entries><id>1065460306</id><name>Interplanetary Cruise banner #c9107484-8ef8-4b02-b137-812295a632d1</name><status>PAUSED</status><budget></budget></entries><entries><id>1138428197</id><name>Marketing Digital</name><status>ENABLED</status><budget></budget></entries></rval></getResponse></soap:Body></soap:Envelope>'
INFO:googleads.common:Response summary - {'requestId': 0005675fea4fa7200a37d1cded082532, 'responseTime': 199, 'serviceName': CampaignService, 'methodName': get, 'operations': 1, 'isFault': False}
`

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! Although, this appears to be working as intended. You'll receive this warning when you run on an environment where the the default encoding isn't utf-8. This warning was added way back when we noticed many users encountering issues displaying utf-8 content on OSes where the default encoding was something else. This is an informative warning, meaning it isn't going to prevent you from using the library. However, you may want to change your default encoding even if you aren't having issues right now, because there's a chance you may have utf-8 content in your response at some point.

I'll close this now, but feel free to reopen if there's some other aspect to your report I've not adequately covered.

Regards,
Mark

**Comment by santiruffino** [comment]
I still have the same problem, and check all the configurations that I consider relevant but the warning keeps appearing. Attached capture of my IDE.

![captura](https://user-images.githubusercontent.com/27986940/38039633-0f643bba-3284-11e8-91b9-7a5a8bcc8a93.JPG)

**Comment by sfontana** [comment]
Perhaps this will help you
https://www.jetbrains.com/help/pycharm/configuring-output-encoding.html
