### ISSUE TITLE
httplib2 version 0.11.0

### ISSUE THREAD

**Issue by CIS-python** [googleads/googleads-python-lib#260]
'HTTPsConnectionWithTimeout' object has no attribute 'proxy_info' error with httplib2 version 0.11.0 which is installed as part of googleads install package.  Error impacts adwords_client.GetService().Get() calls.  Reverting httplib2 back to 0.10.3 results in no errors related to httplib2.  Example code that creates errors:

/*load adwords client using yaml*/
adwords_client = adwords.AdWordsClient.LoadFromStorage('filepath\\yamlfile.yaml')
adwords_client.SetClientCustomerId('xxx-xxx-xxxx')
managed_customer_service = adwords_client.GetService('ManagedCustomerService', version='v201802')
page = managed_customer_service.get({'fields': ['CustomerId', 'Name']})

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! It sounds like a breaking change was introduced in a non-major version bump, thwarting our attempt to avoid this very problem by limiting the version installed via the setup.py. That's... unfortunate.

We _could_ hypothetically patch this for the next release (a sunset next week), but as a result of some incoming changes of our own, we will not be using httplib2 following that release. I'll keep this issue open for tracking purposes in the meantime though.

Regards,
Mark

**Comment by msaniscalchi** [comment]
This issue should now be resolved, this library no longer uses httplib2.
