### ISSUE TITLE
httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com

### ISSUE THREAD

**Issue by lalbag** [googleads/googleads-python-lib#263]
Hi,
We're using the client.GetService('OfflineConversionFeedService', version='v201802') service.
We've configured proxy_config in the yaml file, however, we keep getting error httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com.

Can you please assist? 
Let me know if you need any more info from me..

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! This seems potentially related to a breaking change in httplib2 that was brought to our attention in Issue #260. Did this work for you previously and break following an upgrade? Are you able to make API calls without the proxy configured?

Regards,
Mark

**Comment by lalbag** [comment]
Hi Mark,
Thanks for the prompt response. 
So, we are actually using httplib2==0.10.3, so this doesn't seem related to the issue you've mentioned.

We are able to make API calls with the same yaml file (same credentials), from different servers (without the need of the proxy_config there), but not from this specific one from which we need the API requests to run from.
We do have proxy accessible from the server. In addition, other services, like Bing API are successfully executed, that's why we think this is related to the googleads lib...
Could you please provide an example of the proxy configuration in the googleads.yaml file? Maybe we're missing something there...

Anything else that you might think of?
Thank you,
Liron

**Comment by lalbag** [comment]
Hi Mark,

We were able to solve the issue.
Apparently adding the proxy_config in the yaml file isn't sufficient to actually configure the proxy. 
The proxy should also be configured and passed in the oauth_client, in addition to the AdWordsClient.
(In this case, we're just passing all creds as arguments and not using the yaml file).
Please see example below for how we implemented this:

`    prxx = common.ProxyConfig.Proxy('proxy_host', proxy_port)
    proxy_config = common.ProxyConfig(http_proxy=prxx,https_proxy=prxx,disable_certificate_validation=True)

    oauth_client = oauth2.GoogleRefreshTokenClient(client_id='<INSERT_CLIENT_ID_HERE>', client_secret='<INSERT_CLIENT_SERCET_HERE>',refresh_token='<INSERT_REFRESH_TOKEN_HERE>', proxy_config=proxy_config )

    adwords_client = adwords.AdWordsClient("<INSERT_DEVELOPER_TOKEN_HERE>",oauth_client, user_agent='<INSERT_USER_AGENT_HERE>', client_customer_id='<INSERT_CLIENT_CUSTOMER_ID_HERE>', proxy_config=proxy_config)`

Hope the next person that comes across the issue finds this helpful :)
Thanks,
Liron

**Comment by msaniscalchi** [comment]
Hello Liron,

Thanks for following up. I can say that it is [definitely intended](https://github.com/googleads/googleads-python-lib/blob/master/googleads/common.py#L291) for the ProxyConfig to be applied automatically to the GoogleRefreshTokenClient. If that's not the case, it does sound like there's something wrong.

That said, we'll be pushing some changes later today that will change this up a bit.

**Comment by sandipsingha** [comment]
When I am trying to download GSC data from my local machine I am able to do it.
But when I am doing it from remote machine I am experiencing below error.

I tried many things like setting up of proxies 
#set HTTP_PROXY=http://user:"passsword@1234"@proxy-web.micron.com:80
#set HTTPS_PROXY=https://user:""passsword@1234"@proxy-web.micron.com:80
and installation of 
#pip --trusted-host pypi.python.org install -U channels
#pip install --upgrade google-auth-oauthlib
#pip install --upgrade google-api-python-client

but no luck!!

Below is the error message. i need to do it from remote machine only.  If anyone have any info please help me.
C:\ETLROOT\Package\ETLDV_SSINGHA\CPG\GSC>python GSC_History.py  --noauth_local_webserver
C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access webmasters.dat: No such file or direc
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=481482298063-as9asen10brhosglfg1v9humrhe8l2se.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080
oogleapis.com%2Fauth%2Fwebmasters.readonly&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Traceback (most recent call last):
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2\__init__.py", line 1501, in _conn_request
    conn.connect()
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2\__init__.py", line 1270, in connect
    address_info = socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11003] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GSC.py", line 256, in <module>
    main(sys.argv)
  File "GSC.py", line 77, in main
    scope='https://www.googleapis.com/auth/webmasters.readonly')
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\googleapiclient\sample_tools.py", line 93, in init
    credentials = tools.run_flow(flow, storage, flags)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\client.py", line 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2\__init__.py", line 1926, in request
    cachekey,
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2\__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\ssingha\AppData\Local\Programs\Python\Python37-32\lib\site-packages\httplib2\__init__.py", line 1508, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at oauth2.googleapis.com
