### ISSUE TITLE
Problem with importing googleads

### ISSUE THREAD

**Issue by bry888** [googleads/googleads-python-lib#266]
Hi, I am trying to download the python library googleads as it is written here:

https://github.com/googleads/googleads-python-lib/wiki/API-access-using-own-credentials-(server-to-server-flow)#step-2---setting-up-the-client-library

but while importing, I get: 
     18 from pyasn1.type import namedtype
     19 from pyasn1.type import namedval
---> 20 from pyasn1.type import opentype
     21 from pyasn1.type import tag
     22 from pyasn1.type import univ

ImportError: cannot import name 'opentype'

This is a weird behavior. My version is 10.1.0.

**Comment by grivescorbett** [comment]
Hi, thanks for writing in. It looks like this may be related to a downstream dependency [breaking](https://github.com/etingof/pyasn1/issues/108). Could you please provide us with the full stack trace that includes where in our library it is calling down to pyasn1?

Thanks!

**Comment by ptomasroos** [comment]
@bry888 running 
```
pip install --upgrade pyasn1-modules 
```

will solve this

**Comment by grivescorbett** [comment]
Closing this as it's related to a downstream dependency.
