### ISSUE TITLE
errors module has no attribute 'GoogleAdsServerFault'

### ISSUE THREAD

**Issue by godphoenixz** [googleads/googleads-python-lib#268]
I'm getting this error message when running the sample code handle_policy_violation_error.py:

except errors.GoogleAdsServerFault, e:
AttributeError: 'module' object has no attribute 'GoogleAdsServerFault'

**Comment by grivescorbett** [comment]
Hi, thanks for writing in. Are you using the latest version of the library, 11.0.0? The API was changed that release to throw `GoogleAdsServerFault` instead of a suds error.

**Comment by godphoenixz** [comment]
yes, and referring to the code here
https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201802/error_handling/handle_policy_violation_error.py

**Comment by grivescorbett** [comment]
Hmm do you have a naming conflict with the identifier `errors`? Try doing this:

```python
import googleads.errors

# ...

except googleads.errors.GoogleAdsServerFault
```

The exception type definitely exists, it is defined in [errors.py](https://github.com/googleads/googleads-python-lib/blob/master/googleads/errors.py#L32-L39).

**Comment by godphoenixz** [comment]
Sorry my bad. Just realize I didn't update the library. It works now. Thanks!
