### ISSUE TITLE
Running a Query with 'startsWith%' pattern failes

### ISSUE THREAD

**Issue by ptomasroos** [googleads/googleads-python-lib#271]
Python 2.7.13
googleads 11.0.0

report_downloader = dfp_client.GetDataDownloader(version='v201711')

According to the example here it should work using a startWiths pattern.

https://developers.google.com/doubleclick-publishers/docs/pqlreference

```
    report_job = {
        'reportQuery': {
            'dimensions': ['DATE'],
            'adUnitView': "HIERARCHICAL",
            'statement': {'query': "WHERE parent_ad_unit_name LIKE 'startsWith%'},
```

Fails with following code

```
DFP report job failed. The ID of the failed report is: 10125493071
```

but when running fine when

```
    report_job = {
        'reportQuery': {
            'dimensions': ['DATE'],
            'adUnitView': "HIERARCHICAL",
            'statement': {'query': "WHERE parent_ad_unit_name LIKE '%startsWith%'},
```

**Comment by grivescorbett** [comment]
Hi Tomas,

My apologies, that documentation is not correct. Currently the LIKE clause has to start and end with `%`.

Best,
Gabe

**Comment by ptomasroos** [comment]
All right thanks will handle it in code then!
