### ISSUE TITLE
GetService Bug?

### ISSUE THREAD

**Issue by CIS-python** [googleads/googleads-python-lib#274]
Have not debugged fully, but without any changes to the environment receiving errors with a simple GetService request:
adwords_client = adwords.AdWordsClient.LoadFromStorage('FileDirector\YamlFile.yaml')
adwords_client.SetClientCustomerId('xxx-xxx-xxxx')
managed_customer_service = adwords_client.GetService('ManagedCustomerService', version='v201802')

Is this a potential bug?  No changes made to environment and previous code was working.  Strange as all code was working fine yesterday.

Error is traced back to the imp.py module which is being invoked via requests module.
GoogleAds Version: 11.0.1
requests: 2.18.4

Error Detail:
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 271, in find_module
    "not {}".format(type(path)))

RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

_frozen_importlib_external._NamespacePath

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! I'm not able to replicate the issue you're reporting. I suspect it has something to do with your environment; e.g. the incomplete trace you provided appears to indicate that an import failed as a result of an unexpected value passed to `find_module`.

I'm not sure why this would stop working for you overnight, but I'd suggest reinstalling the library and its dependencies, and trying again.

Regards,
Mark

**Comment by CIS-python** [comment]
Thanks for checking...I think it has to do with the IDE that I was using vs. an actual bug.  Production code appears to work using command line as well as Jupyter notebook.  I was developing some new scripts using the Spyder IDE specifically when getting the errors.  I will attempt to trace back the settings in Jupyter to determine how to fix so it is documented for others (assuming I find the proper setting in the IDE)!

**Comment by CIS-python** [comment]
FYI--more details can be found here, but a documented issue with using Spyder IDE related to PYXIMPORT already exists.  I believe it is related to version 11 of googleads now using requests vs. httplib2 which now invokes the PYXIMPORT but did not trace it in its entirety.

At any rate, commenting out the references related to "if HAS_PYXIMPORT:" within the sitcustomize.py for Spyder fixes the issue.  More details can be found here:  https://stackoverflow.com/questions/46422488/get-rid-of-pyximport
