### ISSUE TITLE
GoogleAdsServerFault: [AuthenticationError.CLIENT_CUSTOMER_ID_INVALID 

### ISSUE THREAD

**Issue by cchorn** [googleads/googleads-python-lib#280]
I'm attempting to run the following example Python script ...
"""This example retrieves keyword traffic estimates.""
but I get this error ...
"GoogleAdsServerFault: [AuthenticationError.CLIENT_CUSTOMER_ID_INVALID @ ; trigger:'<null>']"

I have the client_id, client_secret, and refresh_token set in the yaml file

**Comment by msaniscalchi** [comment]
Hello Charles,

Thanks for the report! It sounds a bit like there's some terminology overload going on here. The `client_id`, `client_secret`, and `refresh_token` keys in the configuration file refer to your OAuth 2.0 configuration. In contrast, the `client_customer_id` is a separate concept referred to in AdWords--it is what identifies the AdWords account for which you intend to make the API call. There should be a separate configuration key labeled `client_customer_id` in the configuration file under `adwords`. As an example, it exists in the sample configuration file that can be found [here](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml#L10).

Note that, despite being an optional field, it is required for many API calls.

Regards,
Mark

**Comment by cchorn** [comment]
Hi Mark,
Thank you. I inserted my ID from AdWords but now I'm asked for the Developer token ...
```
GoogleAdsServerFault: [QuotaCheckError.INVALID_TOKEN_HEADER @ ; trigger:'INSERT_DEVELOPER_TOKEN_HERE']
```

**Comment by msaniscalchi** [comment]
Right, as [suggested in the googleads.yaml configuration file](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml#L6), the `developer_token` is a required field. If you're not familiar with what a developer token is, I suggest reading through the [AdWords developer documentation](https://developers.google.com/adwords/api/docs/guides/start); e.g. the [Make Your First API Call guide](https://developers.google.com/adwords/api/docs/guides/first-api-call#request_a_developer_token) can point you in the right direction on this.

That said, this issue tracker is intended to resolve questions or bugs relating to this client library. Topics about AdWords in general are better suited to the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark

**Comment by cchorn** [comment]
Thanks Mark. No problem. I'll do this.
