### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/home/XYZ'

### ISSUE THREAD

**Issue by Cosbgn** [googleads/googleads-python-lib#283]
I have a function which returns me all AdWords account for a user, something like this:

```
oauth2_client = oauth2.GoogleRefreshTokenClient(app.config['GOOGLE_CLIENT_ID'], app.config['GOOGLE_CLIENT_SECRET'], cred['refresh_token'])
adwords_client = adwords.AdWordsClient(app.config['ADWORDS_DEV_TOKEN'], oauth2_client)
customers = adwords_client.GetService('CustomerService').getCustomers()
# do something

```
On my localhost the function works fine however on AWS Lambda it fails because it can't write, this happens on `adwords_client.GetService('CustomerService').getCustomers()` why does it need to write? and is there any way to run this code on a serverless lambda environment?

**Comment by grivescorbett** [comment]
Hi!

Thanks for reaching out. Assuming you're on the latest version of the library, please try modifying your client initialization with the following parameter:

```python
adwords_client = adwords.AdWordsClient(..., cache=googleads.common.ZeepServiceProxy.NO_CACHE)
```

The reason behind this is that by default the library caches the SOAP WSDLs on your local filesystem. It will work just fine serverless if this is disabled.

Best,
Gabe
