### ISSUE TITLE
Issue: Allowing use of file:/ or custom schemes is often unexpected.

### ISSUE THREAD

**Issue by STANAPI** [googleads/googleads-python-lib#289]
Hello, fellow developers! There seem to be a few insecure parts in the Adwords API libraries, as it's allowing 
use of file:/ or custom schemes is often unexpected.

The codes look like this below:
---------------------------------------------
build\lib\googleads\adwords.py
googleads\adwords.py

      # Generate an unpadded request body
      request_body = self._BuildUploadRequestBody(
          operations,
          has_prefix=current_content_length == 0,
          has_suffix=is_last)
      req = urllib2.Request(upload_url)
      req.add_header('Content-Type', 'application/xml')
---------------------------------------------
    # Send an HTTP POST request to the given upload_url
    req = urllib2.Request(upload_url, data={}, headers=headers)
    resp = self._url_opener.open(req)
---------------------------------------------
    request = urllib2.Request(
        self._end_point, post_body,
        self._header_handler.GetReportDownloadHeaders(**kwargs))
---------------------------------------------
build\lib\googleads\util.py

      headers = request.headers
      u2request = urllib2.Request(url, msg, headers)
      self.addcookies(u2request)
---------------------------------------------

What is the potential risk of this? Is there any way to improve?
![image](https://user-images.githubusercontent.com/39898500/40904293-d7a96f2e-680c-11e8-9e3a-c6599db192f2.png)

**Comment by msaniscalchi** [comment]
Hello,

I'd like to address the vulnerabilities you're suggesting exist, but this (automated?) message is sufficiently vague that I'm not quite certain what the issue(s) is. Feel free to clarify and I would be happy to investigate further.

Regards,
Mark

**Comment by msaniscalchi** [comment]
I will be closing this issue as there has not been any follow-up. Feel free to re-open if you have more details to report.

Regards,
Mark
