### ISSUE TITLE
Insecure part in Adwords API libraries

### ISSUE THREAD

**Issue by STANAPI** [googleads/googleads-python-lib#290]
Hello, fellow developers! There seem to be a few insecure parts in the Adwords API libraries. 

It's using xml.etree.ElementTree.fromstring to parse untrusted XML data is known to be vulnerable to XML attacks. Is it ok to replace xml.etree.ELementTree.fromstring with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib<> is called?

The codes look like this below:
---------------------------------------------
build\lib\googleads\adwords.py

    def _GetRawOperationsFromXML(self, raw_request_xml):
      root = ElementTree.fromstring(raw_request_xml)
      return root.find('{http://schemas.xmlsoap.org/soap/envelope/}Body').find(
          './/')
---------------------------------------------
      try:
        tree = ElementTree.fromstring(content)
        return googleads.errors.AdWordsReportBadRequestError(
            tree.find('./ApiError/type').text,
            tree.find('./ApiError/trigger').text,
            tree.find('./ApiError/fieldPath').text,
            error.code, error, content)
      except ElementTree.ParseError:
        pass
---------------------------------------------

What is the potential risk of this? Is there any way to improve?
![image](https://user-images.githubusercontent.com/39898500/40904362-1bce1c36-680d-11e8-8856-b0a79ab1b183.png)

**Comment by msaniscalchi** [comment]
Hello,

In both cases I would consider the source of the XML trusted (e.g. produced by the API or SOAP client), but I will investigate using defusedxml as it doesn't sound like a bad idea to reduce our dependence on ElementTree.

Regards,
Mark

**Comment by wihl** [comment]
Closing this issue as "won't fix" given the future sunset of the AdWords API.
