### ISSUE TITLE
DownloadReport stuck and not complete

### ISSUE THREAD

**Issue by Alonreznik** [googleads/googleads-python-lib#292]
Hi there.
We have some problems lately with `DownloadReport` function, that is not completed and just get stuck. This happening consistently with a specific account and specific dates. This is a very big account, so it looks like the report is reach to it's limit, or something similar, and get the DownloadReport function stuck.

Moreover, It looks like the `DownloadReport` mechanism doesn't have any of timeout to set in order to avoid this stuck. Can you please add it to your mechanism?

The account is 3880962152 and the stuck is made on 4.6.2018 `VIDEO PERFORMANCE` report.

Thank you

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! When you say "stuck" do you mean that the download makes no progress, but continues indefinitely without timing out?

I'll investigate this issue to see if it is reproducible given the account and report type. It may be helpful if you can provide AWQL or a selector that produces the issue for you. Does the issue go away with a more restrictive selector that produces a smaller report?

> Moreover, It looks like the DownloadReport mechanism doesn't have any of timeout to set in order to avoid this stuck. Can you please add it to your mechanism?

I'll look into this as part of an update that will migrate most of our usage of urllib2 to requests.

Regards,
Mark

**Comment by Alonreznik** [comment]
Hello @msaniscalchi .
Thank you for your quick answer!
By "stuck", I mean that there is no progress in the download, and our code continues running without any timeout. 

This is a python code that represents our selector and running (this is not our original code):
```
from googleads import adwords

adwords_client = adwords.AdWordsClient(developer_token="DeveloperToken",
                                       oauth2_client="oauth2Client",
                                       user_agent="userAgent",
                                       client_customer_id="clientCustomer")
adwords_client.id = 3880962152
adwords_client.name = 'Budweiser'

downloader = adwords_client.GetReportDownloader(version='v201802')
report_def = {
    'reportName': "VIDEO_PERFORMANCE",
    'dateRangeType': "CUSTOM_DATE",
    'reportType': "VIDEO_PERFORMANCE",
    'downloadFormat': "CSV",
    'selector': {
        'fields': ["VideoChannelId", "AccountCurrencyCode", "AccountDescriptiveName", "AccountTimeZone", "AdGroupId",
                   "AdGroupName", "AdGroupStatus", "AdNetworkType1", "AdNetworkType2", "AllConversionRate",
                   "AllConversions", "AllConversionValue", "CampaignId", "CampaignName", "CampaignStatus", "Clicks",
                   "ConversionRate", "ConversionValue", "Cost", "CostPerAllConversion", "CostPerConversion",
                   "CreativeId", "CreativeStatus", "CrossDeviceConversions", "Ctr", "CustomerDescriptiveName", "Date",
                   "DayOfWeek", "Device", "EngagementRate", "Engagements", "ExternalCustomerId", "Impressions", "Month",
                   "MonthOfYear", "Quarter", "ValuePerAllConversion", "VideoDuration", "VideoId",
                   "VideoQuartile100Rate", "VideoQuartile25Rate", "VideoQuartile50Rate", "VideoQuartile75Rate",
                   "VideoTitle", "VideoViewRate", "VideoViews", "ViewThroughConversions", "Week", "Year"]
    }
}

with open('pathToFile', 'a') as file_to_write_:
    downloader.DownloadReport(report_def, file_to_write_,
                              skip_report_header=True,
                              skip_column_header=False,
                              skip_report_summary=True,
                              include_zero_impressions=True)
```

Thanks for your timeout consideration.

Alon

**Comment by Alonreznik** [comment]
Hello @msaniscalchi .
Thank you for your quick answer!
By "stuck", I mean that there is no progress in the download, and our code continues running without any timeout. 

This is a python code that represents our selector and running (this is not our original code):
```
from googleads import adwords

adwords_client = adwords.AdWordsClient(developer_token="DeveloperToken",
                                       oauth2_client="oauth2Client",
                                       user_agent="userAgent",
                                       client_customer_id="clientCustomer")
adwords_client.id = 3880962152
adwords_client.name = 'Budweiser'

downloader = adwords_client.GetReportDownloader(version='v201802')
report_def = {
    'reportName': "VIDEO_PERFORMANCE",
    'dateRangeType': "CUSTOM_DATE",
    'reportType': "VIDEO_PERFORMANCE",
    'downloadFormat': "CSV",
    'selector': {
        'fields': ["VideoChannelId", "AccountCurrencyCode", "AccountDescriptiveName", "AccountTimeZone", "AdGroupId",
                   "AdGroupName", "AdGroupStatus", "AdNetworkType1", "AdNetworkType2", "AllConversionRate",
                   "AllConversions", "AllConversionValue", "CampaignId", "CampaignName", "CampaignStatus", "Clicks",
                   "ConversionRate", "ConversionValue", "Cost", "CostPerAllConversion", "CostPerConversion",
                   "CreativeId", "CreativeStatus", "CrossDeviceConversions", "Ctr", "CustomerDescriptiveName", "Date",
                   "DayOfWeek", "Device", "EngagementRate", "Engagements", "ExternalCustomerId", "Impressions", "Month",
                   "MonthOfYear", "Quarter", "ValuePerAllConversion", "VideoDuration", "VideoId",
                   "VideoQuartile100Rate", "VideoQuartile25Rate", "VideoQuartile50Rate", "VideoQuartile75Rate",
                   "VideoTitle", "VideoViewRate", "VideoViews", "ViewThroughConversions", "Week", "Year"],
        "dateRange": {"min": "20180604",
                      "max": "20180605"}
    }
}

with open('pathToFile', 'a') as file_to_write_:
    downloader.DownloadReport(report_def, file_to_write_,
                              skip_report_header=True,
                              skip_column_header=False,
                              skip_report_summary=True,
                              include_zero_impressions=True)

```

Thanks for your timeout consideration.

Alon

**Comment by msaniscalchi** [comment]
Hey, I just wanted to confirm that the extended time to produce these reports is reproducible on my end for your account. The request is generated and sent to the endpoint, but the endpoint doesn't respond for an extended amount of time. That said, it does eventually download.

I'm pretty confident that you're correct about hitting some sort of API limitation; e.g. the API responds relatively quickly when the number of fields is reduced significantly and slows down as more are added. In the case where the report is "stuck" for you, the time needed to generate the large report with all of those fields is significantly longer. It does complete if given enough time, so I'm not convinced that having a shorter timeout hard-coded into the library is actually desirable here. Does that seem reasonable?

This issue tracker is intended for discussion about this particular client library, but there core issue here--i.e. the delay when generating a large report--appears to be related to the API itself. If you want to go into more detail on that topic, I suggest reaching out on the [AdWords support forum](https://groups.google.com/forum/#!forum/adwords-api).

Regards,
Mark
