### ISSUE TITLE
Is there any way to provide authentication stuff (developer token, refresh token, client id, etc) without using an external file?

### ISSUE THREAD

**Issue by juanmbellini** [googleads/googleads-python-lib#299]
I want to have the credentials injected by the process executing my python script (it pulls all this stuff from a secret store), so I need my script to receive all this as program arguments. How can I set up the library in this case?
Thank you very much!

**Comment by msaniscalchi** [comment]
Hello,

Sure, you could do something like you're suggesting. We actually have [examples](https://github.com/googleads/googleads-python-lib/tree/master/examples/adwords/authentication)  on this very topic. :-)

An alternative way that we perhaps don't point out enough is the AdWordsClient's [LoadFromString class method](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L255). Hypothetically, if you could securely obtain that YAML string from some store, that would also be a viable way of initializing the client without loading from a file.
