### ISSUE TITLE
Connection broken: IncompleteRead(299 bytes read)

### ISSUE THREAD

**Issue by juceberipe** [googleads/googleads-python-lib#300]
I have cloned and deployed the Python App Engine Demo for the AdWords API (from here)
After going through the tutorial multiple time to understand how to retrieve the refresh token I get the following error from the online app:

Error: ('Connection broken: IncompleteRead(299 bytes read)', IncompleteRead(299 bytes read))

with googleads==12.0.0

The example only works on 10.1.0

**Comment by msaniscalchi** [comment]
Hello,

Thanks for report! I'm not able to reproduce, but I think I know why you're seeing this. One of the changes introduced between 10.0.0 and 12.0.0 is the move to google-auth, which uses the requests library. It sounds like this is a duplicate of issue #273, meaning that you may not have been working with the latest library / App Engine code when you encountered this issue.

You can work around the request library's issues with app-engine with the following [work-around](https://toolbelt.readthedocs.io/en/latest/adapters.html#appengineadapter).

Regards,
Mark

**Comment by juceberipe** [comment]
I use google-auth==1.5.0 
now we are getting an error like:

/lib/requests/models.py", line 752, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ('Connection broken: IncompleteRead(22 bytes read)', IncompleteRead(22 bytes read))

**Comment by juceberipe** [comment]
Thanks for the help!
I was able to solve this  issues.

I Forget this

from requests_toolbelt.adapters import appengine
appengine.monkeypatch()
