### ISSUE TITLE
 response from dfp services via API (python) periodically returns is None type

### ISSUE THREAD

**Issue by evgeny-shestakov** [googleads/googleads-python-lib#306]
....
File "/usr/lib/python2.7/dist-packages/googleads/dfp.py", line 830, in DownloadPqlResultToList
self._PageThroughPqlSet(pql_query, results.append, values)
File "/usr/lib/python2.7/dist-packages/googleads/dfp.py", line 917, in _PageThroughPqlSet
if 'rows' in response:
TypeError: argument of type 'NoneType' is not iterable

periodically (infrequently) there are similar problems with the same query/params . please help

python-googleads = 9.0.0-1
API v201711
Ubuntu 14.04.5 x64 LTS

**Comment by grivescorbett** [comment]
Hi, thanks for writing in! Could you please share any additional code, such as the arguments to the download method? If you can't share that here, feel free to post in the [DFP API Forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api).

**Comment by msaniscalchi** [comment]
Hello,

I'm taking ownership of this issue. If you happen to still see this issue, please follow up with the additional information Gabe requested. Otherwise, I'll close this soon with the expectation that it has been resolved elsewhere--e.g. the DFP API Forum.

Regards,
Mark
