### ISSUE TITLE
 Campaign level ADD Platform bidModifier issue

### ISSUE THREAD

**Issue by mbaader** [googleads/googleads-python-lib#311]
Hi,

based on this example:
https://developers.google.com/adwords/api/docs/samples/python/advanced-operations#add-an-ad-group-level-bid-modifier
I've tried to add/set platform bid modifiers on campaign level:

```
...
API_VERSION = "v201806"
campaign_bid_modifier_service = client.GetService('CampaignBidModifierService', 
                                                version=API_VERSION)
criterion_id = '30000'
bid_modifier = 1.6
operation = {
  'operator': 'ADD',
  'operand': {
      'campaignId': campaign_id,
      'criterion': {
          'xsi_type': 'Platform',
          'id': criterion_id
      },
      'bidModifier': bid_modifier
  }
}
response = campaign_bid_modifier_service.mutate([operation])
...
```
But unfortunately this results in a strange error message:

```
    response = campaign_bid_modifier_service.mutate([operation])
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1370, in MakeSoapRequest
    packed_args = self._PackArguments(method_name, args)
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1228, in _PackArguments
    for ((_, param), param_data) in izip(op_params, args)]
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1283, in _PackArgumentsHelper
    for item in data]
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1273, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1340, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1340, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1273, in _PackArgumentsHelper
    elem_type, type_override is not None, data_formatted, set_type_attrs)
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1340, in _CreateComplexTypeFromData
    for k, v in data if k != 'xsi_type'}
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1340, in <dictcomp>
    for k, v in data if k != 'xsi_type'}
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1267, in _PackArgumentsHelper
    elem_type = self._DiscoverElementTypeFromLocalname(type_override)
  File "/home/skripte/.local/lib/python2.7/site-packages/googleads/common.py", line 1317, in _DiscoverElementTypeFromLocalname
    raise last_exception
zeep.exceptions.LookupError: No type 'Platform' in namespace http://www.w3.org/2001/XMLSchema. Available types are: {http://www.w3.org/2001/XMLSchema}int, {http://www.w3.org/2001/XMLSchema}unsignedShort, {http://www.w3.org/2001/XMLSchema}unsignedByte, {http://www.w3.org/2001/XMLSchema}NMTOKENS, {http://www.w3.org/2001/XMLSchema}nonNegativeInteger, {http://www.w3.org/2001/XMLSchema}negativeInteger, {http://www.w3.org/2001/XMLSchema}gMonth, {http://www.w3.org/2001/XMLSchema}normalizedString, {http://www.w3.org/2001/XMLSchema}ENTITIES, {http://www.w3.org/2001/XMLSchema}gYearMonth, {http://www.w3.org/2001/XMLSchema}nonPositiveInteger, {http://www.w3.org/2001/XMLSchema}token, {http://www.w3.org/2001/XMLSchema}anyType, {http://www.w3.org/2001/XMLSchema}IDREFS, {http://www.w3.org/2001/XMLSchema}time, {http://www.w3.org/2001/XMLSchema}QName, {http://www.w3.org/2001/XMLSchema}unsignedLong, {http://www.w3.org/2001/XMLSchema}NCName, {http://www.w3.org/2001/XMLSchema}date, {http://www.w3.org/2001/XMLSchema}string, {http://www.w3.org/2001/XMLSchema}ID, {http://www.w3.org/2001/XMLSchema}positiveInteger, {http://www.w3.org/2001/XMLSchema}ENTITY, {http://www.w3.org/2001/XMLSchema}byte, {http://www.w3.org/2001/XMLSchema}gDay, {http://www.w3.org/2001/XMLSchema}language, {http://www.w3.org/2001/XMLSchema}IDREF, {http://www.w3.org/2001/XMLSchema}anyURI, {http://www.w3.org/2001/XMLSchema}NOTATION, {http://www.w3.org/2001/XMLSchema}float, {http://www.w3.org/2001/XMLSchema}base64Binary, {http://www.w3.org/2001/XMLSchema}dateTime, {http://www.w3.org/2001/XMLSchema}hexBinary, {http://www.w3.org/2001/XMLSchema}Name, {http://www.w3.org/2001/XMLSchema}boolean, {http://www.w3.org/2001/XMLSchema}duration, {http://www.w3.org/2001/XMLSchema}gYear, {http://www.w3.org/2001/XMLSchema}unsignedInt, {http://www.w3.org/2001/XMLSchema}anySimpleType, {http://www.w3.org/2001/XMLSchema}integer, {http://www.w3.org/2001/XMLSchema}gMonthDay, {http://www.w3.org/2001/XMLSchema}decimal, {http://www.w3.org/2001/XMLSchema}double, {http://www.w3.org/2001/XMLSchema}long, {http://www.w3.org/2001/XMLSchema}short, {http://www.w3.org/2001/XMLSchema}NMTOKEN

```

When I googled this error message, I found this similar issue
https://github.com/googleads/googleads-python-lib/issues/270
... where zeep apparently was not looking in the right namespace.

So I wonder whether the problem is on my side or yours.
Could you please look into it?

Best regards
Matthias

**Comment by msaniscalchi** [comment]
Hello Matthias,

Thanks for the report! I've not been able to reproduce this issue in the [add_ad_group_bid_modifier.py](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201806/advanced_operations/add_ad_group_bid_modifier.py) example. I suspect the underlying cause is that you're using the **CampaignBidModifierService** in your code snippet.

The AdGroupBidModifierService has a [Platform](https://developers.google.com/adwords/api/docs/reference/v201806/AdGroupBidModifierService.Platform) criterion, whereas CampaignBidModifierService [does not](https://developers.google.com/adwords/api/docs/reference/v201806/CampaignBidModifierService.Criterion).

Regards,
Mark

**Comment by mbaader** [comment]
Hi Mark,

Thank you for the answer.
But... the "Platform Criterion Type" is very well listed at the CampaignBidModifierService:
here:
https://developers.google.com/adwords/api/docs/reference/v201806/CampaignBidModifierService.Criterion
and here:
https://developers.google.com/adwords/api/docs/reference/v201806/CampaignBidModifierService.Criterion.Type

Besides: Attempting to adjust the "Location" Bid Modifier (which is also listed there) using the CampaignBidModifierService results in the same error.

I can hardly believe that these basic services should not be available via the API.

Please have a closer look.

Best regards
Matthias

**Comment by msaniscalchi** [comment]
What you're seeing on that page is a potential enum value for `Criterion.Type`--i.e. Criterion is used across several services, and supported types appear in the side-bar under **Criterion** for the associated service. For the `CampaignBidModifierService`, the only supported Criterion type is [InteractionType](https://developers.google.com/adwords/api/docs/reference/v201806/CampaignBidModifierService.InteractionType).

That said, there may be other ways to attempt what you're trying to do. I recommend reaching out to the [Google Ads API Support Forum](https://groups.google.com/forum/#!forum/adwords-api) for more insight on how to proceed.

Regards,
Mark

**Comment by mbaader** [comment]
Hi Mark,

Thank you very much for your further explanations.
I have now found out that the code posted above works perfectly when you use the "CampaignCriterionService" instead of the "CampaignBidModifierService". For whatever reason.

And there is even an example here on github:
https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201806/campaign_management/set_criterion_bid_modifier.py

Regards
Matthias

**Comment by msaniscalchi** [comment]
Great, glad to hear you got it working! Of course, feel free to reach out to the API support forum if you have further questions about Criterion, as API support specialists have more insight into the API and can provide more context for why it is organized as it is. :-)
