### ISSUE TITLE
CampaignBidModifierOperation not in _OPERATION_MAP

### ISSUE THREAD

**Issue by wtemmerman** [googleads/googleads-python-lib#320]
Hi,

I tried to create a call bid adjustment with the API. 
The problem is : 
I create my add operation but the CampaignBidModifierService doesn't have his CampaignBidModifierOperation present in _OPERATION_MAP (line 641) of googleads/adwords.py. 
So that raise a KeyError.

Stack error : 
```
~/projects/tool/lib/python3.5/site-packages/googleads/adwords.py in _GenerateRawRequestXML(self, operations)
    891         KeyError: If the given operation type is not supported.
    892       """
--> 893       operation = self._OPERATION_MAP[operations[0]['xsi_type']]
    894       service = self.client.GetService(operation.service, self._version)
    895       return service.GetRequestXML(operation.method, operations)

KeyError: 'CampaignBidModifierOperation'
```

Do you have an idea why this operation is not present in _OPERATION_MAP ?

Regards,

Wilfried

**Comment by msaniscalchi** [comment]
Hello Wilfried,

Thanks for the report! The reason CampaignBidModifierService doesn't appear in `_OPERATION_MAP` is that it is [not a service currently supported by the BatchJobService](https://developers.google.com/adwords/api/docs/guides/batch-jobs#supported_operations). In fact, even if we added it in to `_OPERATION_MAP`, the jobs for that service wouldn't work!

As a result, from a client library perspective, this is working as intended. Of course, I could understand why one might want BatchJobService to cover a larger number of services. It may make sense to describe your use-case that benefits from CampaignBidModifierService compatibility with BatchJobService on the [Google Ads Support Forum](https://groups.google.com/forum/#!forum/adwords-api), as the support specialists there are more directly involved with the product itself and can better advocate for new features.

Regards,
Mark
