### ISSUE TITLE
API certificate verify issue

### ISSUE THREAD

**Issue by jeasenrys** [googleads/googleads-python-lib#323]
I had been using API to manage campaigns for a while, but recently I ran into a connection issue while pulling data from Adwords with the error message below:

urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

One thing is tried is to turn on "disable_certificate_validation" in Googleads.yaml file, but still it didn't work. 

Any help on this would be appreciated!

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! What version of Python are you using? What sort of environment are you running it on?

One unusual issue we've noticed is that certain changes to the environment cause Python to "forget" the location of CA files used in the certificate verification step. This appears to be more common on Windows devices; e.g. this behavior is occasionally reported after a system update. Typically, either the classic reboot solution or re-installation of Python do the trick. I'd first give those a try. :-)

Regards,
Mark

**Comment by jeasenrys** [comment]
Thanks a lot, Mark, for the response! 

 I am using Python 2.7.11 and had the same issue by running the script from both unix server and local computer(my Mac, just for testing purpose).  The thing is that we can not really reboot/reinstall on the unix server. Is there any other thing you would suggest to try....? Thanks again!!

JIe

**Comment by wihl** [comment]
Closing issue as stale.
