### ISSUE TITLE
DFP key called instead of AdWords when LoadFromStorage

### ISSUE THREAD

**Issue by NilsOle93** [googleads/googleads-python-lib#324]
I wrote a script that on my machine runs with googleads 13.0.0 and copied the script to a colleague's PC where it rans on googleads 14.0.0.
On my machine it works fine but on his we get the following error.
```
Traceback (most recent call last):
 File "C:\Users\Juniqe\AppData\Local\Programs\Python\Python37\lib\site-packages\googleads\common.py", line 289, in LoadFromStorage
   optional_product_values)
 File "C:\Users\Juniqe\AppData\Local\Programs\Python\Python37\lib\site-packages\googleads\common.py", line 189, in LoadFromString
   'Please replace the "dfp" key in the configuration YAML string with'
googleads.errors.GoogleAdsValueError: Please replace the "dfp" key in the configuration YAML string with"ad_manager" to fix this issue.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "Evergreen_script.py", line 415, in <module>
   r"C:\Users\Juniqe\Desktop\evergreen script\googleads.yaml")
 File "C:\Users\Juniqe\AppData\Local\Programs\Python\Python37\lib\site-packages\googleads\adwords.py", line 243, in LoadFromStorage
   cls._OPTIONAL_INIT_VALUES))
 File "C:\Users\Juniqe\AppData\Local\Programs\Python\Python37\lib\site-packages\googleads\common.py", line 292, in LoadFromStorage
   'Given yaml file, %s, could not find some keys. %s' % (path, e))
googleads.errors.GoogleAdsValueError: Given yaml file, C:\Users\Juniqe\Desktop\evergreen_script\googleads.yaml, could not find some keys. Please replace the "dfp" key in the configuration YAML string with"ad_manager" to fix this issue.
```
Adding ad_manager to the dfp key in the yaml-file does not fix this and it actually should not matter at all as I don't want to use the dfpclient in my script and call the adwordsclient.
```
adwords_client = adwords.AdWordsClient.LoadFromStorage(
        r"C:\Users\Juniqe\Desktop\evergreen_script\googleads.yaml")
```

In the version history, I did not see a difference in the LoadFromStorage function so I am wondering where this issue could come from.

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! Do you use both AdWords and Ad Manager (previously DFP)? If not, you may remove the dfp key and the related items under it from your configuration file and that should resolve this issue. The underlying cause is the [DFP rebrand to Ad Manager](https://github.com/googleads/googleads-python-lib/wiki/dfp-rebrand).

Regards,
Mark

**Comment by NilsOle93** [comment]
Hej Mark,

thanks, this did the trick!

Regards,
Nils
