### ISSUE TITLE
Slow serialization of cpc bids at the keyword level

### ISSUE THREAD

**Issue by mikeengland** [googleads/googleads-python-lib#325]
I have encountered a slight performance issue when I submit keyword CPC bids via the client's mutate method, especially when submitting a larger number of operations, such as 5000.
Each keyword bid is formatted as follows:
`{
        'xsi_type': 'AdGroupCriterionOperation',
        'operator': 'SET',
        'operand': {
            'xsi_type': 'BiddableAdGroupCriterion',
            'adGroupId': <adgroup id>,
            'criterion': {'xsi_type': 'Keyword', 'id': <keyword id>},
            'biddingStrategyConfiguration': {
                'bids': [
                    {
                        'xsi_type': 'CpcBid', 'bid': {'microAmount': <micro amount>}
                    }
                ]
            }
        }
    }`

When I profile the code, I notice the following timings (hopefully these are not too abstract to be of use):
transports.py:86(post_xml) - 11.4s (I understand there is not much we can do about this, as this is the time the API is processing the bid upload)
soap.py:57(_create) - 2.14 s
common.py:1252 (_PackArgumentsHelper) - 2.75s
indicators.py:573 (parse_xmlelements) - 1.7s
valueobjects.py:70(__init__) 1.91s

I believe that one of the causes of the slow serialization is due to the number of nested dicts in each Operation that I am using above. Is there a more efficient keyword bid message that could be used instead?

Thanks in advance, and let me know if you need more details.

**Comment by msaniscalchi** [comment]
Hello Mike,

Thanks for reaching out!  An early decision made when writing this library was to follow previously established patterns for working with the AdWords API in Python--e.g. defining types via dictionaries. Aside from ease of use, dictionaries act as an abstraction layer that has enabled us to change SOAP clients while minimizing breaking changes for most users. That said, you are correct that their instantiation (and the necessary packing step) can potentially have a non-negligible performance cost.

One recommended subject you may want to look in to for a performance boost would be using the SOAP client directly, as suggested [here](https://github.com/googleads/googleads-python-lib#im-familiar-with-sudszeep-can-i-use-those-features-in-the-library). In this way, you would be able to skip the potentially costly creation of dicts/lists/etc and the packing step.

I think this may warrant something a little more concrete than a suggestion, so I will leave this open as a feature request for further investigation and an update to our library documentation on improving performance.

Regards,
Mark

**Comment by mikeengland** [comment]
Thanks for the reply @msaniscalchi , understood. I'll give it a try.

Maybe this will become irrelevant when users start to switch to the new beta gRPC API?

**Comment by mikeengland** [comment]
@msaniscalchi Do you have an example of using the zeep client directly? The readme only has the old suds method. Thanks!

**Comment by mikeengland** [comment]
I wrote a quick example to update a keyword cpc bid using zeep directly in case anyone else would find it useful:

```python
    adgroup_criterion_service = get_service(client, Service.AD_GROUP_CRITERION_SERVICE)
    zeep_client = service.zeep_client
    factory = zeep_client.type_factory('ns0')
    keyword = factory.Keyword(id=keyword_id)
    cpc_bid = factory.CpcBid(bid={'microAmount': micro_amount})
    bidding_strategy_config = factory.BiddingStrategyConfiguration(bids=[cpc_bid])
    biddable_adgroup_criterion = factory.BiddableAdGroupCriterion(adGroupId=adgroup_id, criterion=keyword,
                                                                  biddingStrategyConfiguration=bidding_strategy_config)
    operation = factory.AdGroupCriterionOperation(operator='SET', operand=biddable_adgroup_criterion)
    return operation
```

@msaniscalchi, I didn't see any performance improvement using zeep directly. Looking deeper into the code, in `_PackArgumentsHelper`, it looks like even if the element is a SOAP object instead of a dict, a new SOAP object will be instantiated even if one is already provided, similar to how it is done for dicts. Is there something I can do to avoid this potentially expensive packing step?

Thanks!

**Comment by wihl** [comment]
Closing issue as "won't fix" due to migration to the Google Ads API (which uses gRPC as alluded to in a [prior comment](https://github.com/googleads/googleads-python-lib/issues/325#issuecomment-422409510))
