### ISSUE TITLE
Problem with zeep library

### ISSUE THREAD

**Issue by MateuszKuba** [googleads/googleads-python-lib#331]
Whenever i run **dfp_client.GetService** i receive the following error ( it happens only on some of jenkins configurations and python 3.5 )

python3.5/site-packages/zeep/cache.py", line 103, in add
15:04:38     cursor.execute("DELETE FROM request WHERE url = ?", (url,))
15:04:38 sqlite3.OperationalError: attempt to write a readonly database
15:04:38 Build step 'Execute shell' marked build as failure
15:04:38 Notifying upstream projects of job completion
15:04:39 Finished: FAILURE

When i set dfp_client.cache = googleads.common.ZeepServiceProxy.NO_CACHE I receive no error 

Is it a problem of system configuration ( maybe some privilages ) or googleads-python-lib ?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! If the environment you're running the library on is restrictive, such that you lack write access to produce a cache, it makes sense that you would see an error like this. Disabling the cache with `ZeepServiceProxy.NO_CACHE` will mitigate this, at the cost of having no cache.

If you could hypothetically modify your environment to gain write access, that would also resolve the problem.

Regards,
Mark

**Comment by MateuszKuba** [comment]
The problem was with write privilages on the server and zeep service having no access throws this error. Having set zeepserviceproxy to NO_CACHE solved the problem
