### ISSUE TITLE
get exchange rate  googleads.errors.GoogleAdsServerFault: [FeatureError.MISSING_FEATURE

### ISSUE THREAD

**Issue by yuyang199226** [googleads/googleads-python-lib#334]
error message:
googleads.errors.GoogleAdsServerFault: [FeatureError.MISSING_FEATURE @ ; trigger:'XFP_MULTI_CURRENCY_EXCHANGE_RATES_CUSTOMIZATION']
my admanger account has no dfp feature?
but my code can get ad units and create adunit by googleads lib

**Comment by christopherseeley** [comment]
The ExchangeRateService was disabled and removed from the Ad Manager API.
