### ISSUE TITLE
error handling behavior

### ISSUE THREAD

**Issue by jaypatrickhoward** [googleads/googleads-python-lib#335]
Hi all.  Hoping to get some clarification on how server faults are handled, since the behavior I'm seeing *seems* like it may contradict the documentation and examples.  I'm currently testing with v201809 of OfflineConversionFeedService.

#### Issue One
When passing many operations to mutate(), the presence of partial errors seems to cause an exception to be raised.  However, this [example](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/error_handling/handle_partial_failures.py) makes it seem as if partial errors should be included with the return value and no exception raised.  Which is the correct behavior?  Or have I misinterpreted what's going on?

#### Issue Two
The [documentation](https://developers.google.com/adwords/api/docs/reference/v201809/OfflineConversionFeedService) states "This bulk operation does not have any transactional guarantees. Some operations can succeed while others fail."  I took that to mean that when multiple operations are passed every operation is attempted, with some succeeding and some failing.  What I'm seeing instead is that certain types of failures cause the bulk operation to "short circuit", with subsequent operations not even being attempted.  Is that expected?

To give more detail, an OfflineConversionError, e.g. EXPIRED_CLICK, seems *not* to short-circuit the bulk operation.  That is, if the operation at index 0 generates EXPIRED_CLICK then the operations at positions 1..N are still be attempted.  However, a RangeError, e.g. TOO_LOW, *does* cause a short-circuit and subsequent operations aren't attempted.  I'm currently not sure whether operations *prior* to the one with the RangeError are executed.

Have I mistaken what the behavior actually is?  Is it documented anywhere which error types cause a short-circuit and which don't?

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
