### ISSUE TITLE
Fetch match tables 

### ISSUE THREAD

**Issue by Aviv-jambari** [googleads/googleads-python-lib#337]
error is 'charmap' codec can't encode characters in position 1-6: character maps to 

getting this error
on the example from the github

https://github.com/googleads/googleads-python-lib/blob/master/examples/ad_manager/v201808/publisher_query_language_service/fetch_match_tables.py

 report_downloader = client.GetDataDownloader(version='v201808')

  line_items_file = tempfile.NamedTemporaryFile(
      prefix='line_items_', suffix='.csv', mode='w', delete=False)
  ad_units_file = tempfile.NamedTemporaryFile(
      prefix='ad_units_', suffix='.csv', mode='w', delete=False)

  line_items_pql_query = ('SELECT Name, Id, Status FROM Line_Item ORDER BY Id '
                          'ASC')
  ad_units_pql_query = 'SELECT Name, Id FROM Ad_Unit ORDER BY Id ASC'

  # Downloads the response from PQL select statement to the specified file
  report_downloader.DownloadPqlResultToCsv(
      line_items_pql_query, line_items_file)
  report_downloader.DownloadPqlResultToCsv(
      ad_units_pql_query, ad_units_file)

  line_items_file.close()
  ad_units_file.close()

i tried to add  encoding="UTF8" to the NamedTemporaryFile function
but the request takes forever and then crashes

**Comment by christopherseeley** [comment]
If this is still an issue, can you capture SOAP logs for the requests that crash and repost in the [Ad Manager API forum](https://groups.google.com/g/google-doubleclick-for-publishers-api)?
