### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by nmylarappa** [googleads/googleads-python-lib#338]
Running into this below issue - any resolution?

 "/usr/local/lib/python2.7/dist-packages/googleads/common.py", line 1385, in MakeSoapRequest
    e.detail, errors=error_list, message=e.message)
googleads.errors.GoogleAdsServerFault: [UserListError.CAN_NOT_MUTATE_SENSITIVE_USERLIST @ operations[0].operand]

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced the Google Ads API:
https://github.com/googleads/google-ads-python
