### ISSUE TITLE
which api should i use

### ISSUE THREAD

**Issue by GoddessLuBoYan** [googleads/googleads-python-lib#339]
I want to know how hot keywords are.
I thick I should read the example "v201809/optimization/estimate_keyword_traffic.py"
and I run it.
But it returns an error, because I don't set "googleads.yaml".
So I go to the developer site of google to get token.

However, there are toooooooo many apis to choose.

Which api should I choose? And then what should I do? Thanks a lot.

(My Chinglish is very bad, so I use Chinese say it again)

我想知道怎么搜索关键词的热度（工具 -> 关键词规划师 -> 获取搜索量和预测数据）
我想我应该阅读例子"v201809/optimization/estimate_keyword_traffic.py", 并且我尝试运行了它
但因为我没有设置"googleads.yaml"，运行并没有成功
所以我去了谷歌的开发者界面去申请api
但是，能申请的api实在是太多了，我不知道该申请哪个
所以我想问一下：我该申请哪个api，然后应该怎么做？感谢解惑！

![666](https://user-images.githubusercontent.com/38455509/47627312-3fe83900-db6a-11e8-8b21-394bf6775f02.PNG)

**Comment by msaniscalchi** [comment]
Hey there,

Thanks for the report, and doing your best with Chinglish! Sadly, my Englinese is not up to par. :-)

So there's a few questions I see here:

> I want to know how hot keywords are.
> I thick I should read the example "v201809/optimization/estimate_keyword_traffic.py"

That seems like the right example to use as a starting point.

> But it returns an error, because I don't set "googleads.yaml".

Right, [googleads.yaml](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml) is the configuration file used by this library to quickly instantiate a client via the [`AdWordsClient.LoadFromStorage`](https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py#L280) method. It may be helpful to use the [generate_refresh_token.py](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/authentication/generate_refresh_token.py) example for this.

> However, there are toooooooo many apis to choose.

Good news then, you don't need to choose any! The AdWords API is a bit different than most other Google APIs, you don't need to enable it. Note that this might not be the case for the newer Google Ads API though.

> Which api should I choose? And then what should I do? Thanks a lot.

Assuming you already have a project, you'll need to find the [Credentials](https://pantheon.corp.google.com/apis/credentials) tab under APIs and Services. You'll need to click the **create credentials** button on that page and select **OAuth client ID**. If you're running this on a local application as opposed to a web app, you should set the **Application type** to **Other**. You can then specify the **client ID** and **client secret** as arguments to the **generate_refresh_token.py** example to step through the OAuth 2.0 flow. When doing so, you should be logged in to a Google account that has access to the AdWords account you're trying to access.

Regards,
Mark

**Comment by wihl** [comment]
closed as "solution offered"
