### ISSUE TITLE
KeyError 'date' when using datetime object as a start/end date for Report Query

### ISSUE THREAD

**Issue by natethegrateful** [googleads/googleads-python-lib#340]
When using a datetime object as a start/end date for a report query with CUSTOM_DATE type there is an error in common.py.  I received a KeyError for 'date' from the function _CreateComplexTypeFromData. 

I used the following code to build my datetime object

`timezone = pytz.timezone('US/Arizona')
start_date = timezone.localize(datetime.strptime(2018-10-28, '%Y-%m-%d'))`

**Comment by christopherseeley** [comment]
Ad Manager reports use the [Date](https://developers.google.com/ad-manager/api/reference/latest/ReportService.Date) object, not a date time. You'll need to extract just the date portion.
