### ISSUE TITLE
Filter non MCC accounts in Adwords hierarchy tree

### ISSUE THREAD

**Issue by mporracindie** [googleads/googleads-python-lib#341]
So im trying to download reports for ALL my adwords accounts and since im at around 500 and i dont want to hardcode each one (since its idead that if a newone is created this one is downloaded too) im taking this aproach.

Access the API as the main MCC account and [build the hierarchy tree](https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/account_management/get_account_hierarchy.py). And i would take the "leafs" of this tree as my non MCC account in order to avoid:

> ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH

But this is clearly not working since im still getting multiple times this error. Is there a better way to check if an account is MCC?

Im using python but any reference would be apreciated.

Thanks!

**Comment by wihl** [comment]
closed as "solution offered"
