### ISSUE TITLE
Request for example

### ISSUE THREAD

**Issue by ron819** [googleads/googleads-python-lib#343]
I want to update users-list and I'm using the "Create and populate a user list" as a guide
https://developers.google.com/adwords/api/docs/samples/python/remarketing

I have a some lists and I want to update the emails on them. Some users will be removed from one list and added to another. The example shows only how to ADD new user to list.

How can I modify existed list? 
Also, is it possible to delete the whole lists and re-create them (meaning doing only ADD) ? Is this recommended ?

**Comment by msaniscalchi** [comment]
Hello,

Thanks for reaching out! So it sounds like you're looking for details on how to modify an existing list? You can add to a list, but the [mutateMembers](https://devsite.googleplex.com/adwords/api/docs/reference/v201809/AdwordsUserListService#mutatemembers) method doesn't support the SET operator, meaning you can't modify a member that was already added. Likewise, [mutate](https://devsite.googleplex.com/adwords/api/docs/reference/v201809/AdwordsUserListService#mutate) doesn't support the REMOVE operator, meaning that you can't delete the list.

[This thread](https://groups.google.com/d/topic/adwords-api/agdAiis4Ep8/discussion) in the AdWords / Google Ads Support Forum might be helpful. If you have additional questions about the workings of UserLists, I recommend you reach out on the [support forum](https://groups.google.com/forum/#!forum/adwords-api)--our focus on this issue tracker is the client library itself.

Regards,
Mark

**Comment by ron819** [comment]
@msaniscalchi  I don't understand. How do people change the lists if there is no way to move user from one list to another.
