### ISSUE TITLE
getUserInterestCriterion problem

### ISSUE THREAD

**Issue by Tahirhan** [googleads/googleads-python-lib#346]
Hi, i am trying to get affinity category criterions. But i think i don't know where or how to pass " userInterestTaxonomyType='BRAND' " part in code. I get error when i execute below code:

def main(client):
  # Initialize appropriate service.
  constant_data_service = client.GetService(
      'ConstantDataService', version='v201809')

  affinities = constant_data_service.getUserInterestCriterion(userInterestTaxonomyType='BRAND')

  # Display results.
  for affinity in affinities:
    print('Affinity with name "%s" and ID "%s" was found.'
          % (affinity['name'], affinity['id']))

**Comment by msaniscalchi** [comment]
Hello,

You don't need to specify the parameter as a keyword argument, meaning that the call would look like:

```
affinities = constant_data_service.getUserInterestCriterion('BRAND')
```

Regards,
Mark
