### ISSUE TITLE
SelectorError.INVALID_PREDICATE_FIELD_NAME @ selector; trigger:'GenderType'

### ISSUE THREAD

**Issue by Tahirhan** [googleads/googleads-python-lib#350]
Hi, i am trying to add different types of criterions to selector and get the reach number according to that criterions. In below code i tried to add gender type criterion to selector but i get error.

Code 
`   def get_reach(client, country_list, gender_list):
    # Initialize appropriate service.
    location_criterion_service = client.GetService(
        'LocationCriterionService', version='v201809')

    # Create the selector.
    selector = {
        'fields': ['Id', 'LocationName', 'DisplayType', 'GenderType', 'CanonicalName', 'Reach', 'TargetingStatus'],
        'predicates': [{
            'field': 'LocationName',
            'operator': 'EQUALS',
            'values': country_list
        },{
            'field': 'GenderType',
            'operator': 'EQUALS',
            'values': gender_list
        }]
    }

    # Make the get request.
    location_criteria = location_criterion_service.get(selector)`

Output 

googleads.errors.GoogleAdsServerFault: [SelectorError.INVALID_FIELD_NAME @ selector; trigger:'GenderType', SelectorError.INVALID_PREDICATE_FIELD_NAME @ selector; trigger:'GenderType']

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! In this case, both the client library behavior and API response seem valid. The `get` method of `LocationCriterionService` returns [`LocationCriterion`](https://devsite.googleplex.com/adwords/api/docs/reference/v201809/LocationCriterionService.LocationCriterion), which doesn't have a `GenderType` field.

If you have questions concerning getting started or best practices with the API, the [AdWords / Google Ads API Support Forum]() would be a good place to get started.

Regards,
Mark
