### ISSUE TITLE
No type 'AgeRange' in namespace https://adwords.google.com/api/adwords/o/v201809.

### ISSUE THREAD

**Issue by Tahirhan** [googleads/googleads-python-lib#351]
Hi, i am trying to get traffic estimates. But error occurs when i add different criteria other than language and location, for example AgeRange like this code below.

Code ;

# Initialize appropriate service.
    traffic_estimator_service = client.GetService(
        'TrafficEstimatorService', version='v201809')

    # Construct selector object and retrieve traffic estimates.
    keywords = [
        {'text': 'mars cruise', 'matchType': 'BROAD'},
        {'text': 'cheap cruise', 'matchType': 'PHRASE'},
        {'text': 'cruise', 'matchType': 'EXACT'}
    ]
    negative_keywords = [
        {'text': 'moon walk', 'matchType': 'BROAD'}
    ]
    keyword_estimate_requests = []
    for keyword in keywords:
        keyword_estimate_requests.append({
            'keyword': {
                'xsi_type': 'Keyword',
                'matchType': keyword['matchType'],
                'text': keyword['text']
            }
        })

    for keyword in negative_keywords:
        keyword_estimate_requests.append({
            'keyword': {
                'xsi_type': 'Keyword',
                'matchType': keyword['matchType'],
                'text': keyword['text']
            },
            'isNegative': 'true'
        })

    # Create ad group estimate requests.
    adgroup_estimate_requests = [{
        'keywordEstimateRequests': keyword_estimate_requests,
        'maxCpc': {
            'xsi_type': 'Money',
            'microAmount': '1000000'
        }
    }]

    # Create campaign estimate requests.
    campaign_estimate_requests = [{
        'adGroupEstimateRequests': adgroup_estimate_requests,
        'criteria': [
            {
                'xsi_type': 'Location',
                'id': '2840'  # United States.
            },
            {
                'xsi_type': 'Language',
                'id': '1000'  # English.
            },
            {
                'xsi_type': 'AgeRange',
                'id': '503001'  # Female
            }
        ],
    }]

    # Create the selector.
    selector = {
        'campaignEstimateRequests': campaign_estimate_requests,
    }

    # Optional: Request a list of campaign-level estimates segmented by
    # platform.
    selector['platformEstimateRequested'] = True

    # Get traffic estimates.
    estimates = traffic_estimator_service.get(selector)

Output ;

zeep.exceptions.LookupError: No type 'AgeRange' in namespace https://adwords.google.com/api/adwords/o/v201809. Available types are: {https://adwords.google.com/api/adwords/o/v201809}CurrencyCodeError, {https://adwords.google.com/api/adwords/o/v201809}Estimate, {https://adwords.google.com/api/adwords/o/v201809}CampaignEstimateRequest, {https://adwords.google.com/api/adwords/o/v201809}TrafficEstimatorSelector, {https://adwords.google.com/api/adwords/o/v201809}TrafficEstimatorError.Reason, {https://adwords.google.com/api/adwords/o/v201809}StatsEstimate, {https://adwords.google.com/api/adwords/o/v201809}CampaignEstimate, {https://adwords.google.com/api/adwords/o/v201809}TrafficEstimatorResult, {https://adwords.google.com/api/adwords/o/v201809}EstimateRequest, {https://adwords.google.com/api/adwords/o/v201809}PlatformCampaignEstimate, {https://adwords.google.com/api/adwords/o/v201809}AdGroupEstimate, {https://adwords.google.com/api/adwords/o/v201809}TrafficEstimatorError, {https://adwords.google.com/api/adwords/o/v201809}AdGroupEstimateRequest, {https://adwords.google.com/api/adwords/o/v201809}CurrencyCodeError.Reason, {https://adwords.google.com/api/adwords/o/v201809}KeywordEstimateRequest, {https://adwords.google.com/api/adwords/o/v201809}KeywordEstimate

**Comment by msaniscalchi** [comment]
Hello,

Thanks for the report! This seems similar to an earlier issue you reported in that the criterion you're attempting to use is not supported; e.g. you can determine this via the [reference documentation](https://devsite.googleplex.com/adwords/api/docs/reference/v201809/TrafficEstimatorService.CampaignEstimateRequest#criteria).

That said, the error output seems to be working as intended. The underlying SOAP client can't find the `AgeRange` type because it doesn't exist.

While I'm not quite certain what it is you're trying to do, I do recommend reaching out to the [API Support Forum](https://groups.google.com/forum/#!forum/adwords-api) if you're not quite sure how to proceed, as they are better suited to guide you on using the API, whereas this issue tracker is more suited to troubleshooting issues with this specific library.

Regards,
Mark
