### ISSUE TITLE
Coudn't extract all the columns from reports using python awql 

### ISSUE THREAD

**Issue by pradyrk** [googleads/googleads-python-lib#360]
I m using the exact code from https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/reporting/download_criteria_report_as_string_with_awql.py

I was able to run the example as is but when I try to include all the columns in report, report comes with blank summary with zeros. My requirement is to pull all column from each report using awql.

I extracted the report fields using https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/reporting/get_report_fields.py

I coudnt understand what I m missing here. Report frequency in my case is 'today'.

**Comment by pradyrk** [comment]
Adding segment columns to attributes and metrics to throwing an exception. Why is that segment columns can't be used in select clause of python api?

**Comment by BenRKarl** [comment]
Hi @pradyrk - thanks for the question. Can you share the exact AWQL query that you're using that's generating errors?
