### ISSUE TITLE
Python 3 error after recent upgrade

### ISSUE THREAD

**Issue by mygreenleaves** [googleads/googleads-python-lib#364]
Hi

I'm currently upgrading to v201809. i'm using Python 3 and I'm getting the following error when running a test script:

ImportError: cannot import name 'izip' - Any thoughts on how I can get past this? Many thanks

Trackback looks like

C:\Users\Simon\Anaconda3\lib\site-packages\googleads\__init__.py in <module>()
     15 """A client library for Google's SOAP Ads APIs."""
     16 
---> 17 from .ad_manager import AdManagerClient
     18 from .adwords import AdWordsClient

C:\Users\Simon\Anaconda3\lib\site-packages\googleads\ad_manager.py in <module>()
     26 import urllib.request, urllib.error, urllib.parse
     27 import pytz
---> 28 import googleads.common
     29 import googleads.errors
     30 

C:\Users\Simon\Anaconda3\lib\site-packages\googleads\common.py in <module>()
     21 import inspect
     22 # from itertools import izip - https://stackoverflow.com/questions/50239706/cannot-import-name-izip
---> 23 from itertools import izip
     24 import locale
     25 import logging

ImportError: cannot import name 'izip'

**Comment by BenRKarl** [comment]
Hi @mygreenleaves - thanks for bringing this up!

Can you share some details about what test script you're trying to run? Is it one of the existing examples in the library, or something else?

**Comment by mygreenleaves** [comment]
Hi @BenRKarl 

Thanks for your follow up.

Ha, you can tell I'm a newbie. First the subject heading is misleading. I've always been using python 3 but am trying to upgrade to adWords api v201809.

When I say test script, sorry this was not an official test but just one of mine.

Essentially when I make a mutate call, example add a keyword or pause an audience I get the above error.

**Comment by mygreenleaves** [comment]
Hi

Just following up to see if anyone can help out here?

**Comment by BenRKarl** [comment]
Hi @mygreenleaves - apologies for the delay! We're still investigating the issue. Based on the link in your stack trace it appears to be an incompatibility with Python 3. Are you able to use Python 2 while we work on the issue?

**Comment by mygreenleaves** [comment]
Thanks for the follow up @BenRKarl . All my scripts are Python V3 but I have a AdWords 06 version safely in a virtual env that I can use.

**Comment by mygreenleaves** [comment]
Hi @BenRKarl 

Any luck?
My version 06 is about to sunset in a few weeks. Starting to get a bit desperate.

**Comment by BenRKarl** [comment]
@mygreenleaves Sorry for the delay in my response. Can I ask how you're installing the library? I noticed in our setup.py file [see here](https://github.com/googleads/googleads-python-lib/blob/master/setup.py#L109) that `2to3` is invoked on the code when built, which should resolve the `izip` compatibility.

**Comment by mygreenleaves** [comment]
To be honest, I'm not really sure how the library was installed. I'm comfortable with if, else statements etc but when it comes to installations etc I'm a bit lost.  What I'll do is try and set up a virtual environment and start again (documenting my steps).

But I can definitely say it is all Python 3

**Comment by mygreenleaves** [comment]
Thanks for your patience @BenRKarl . I haven't been successfully in the installation process I'm afraid. I have one environment working successfully with 09 so will work with that and wait for some head space to have another go at the install process.

**Comment by BenRKarl** [comment]
Ok thanks @mygreenleaves. I'm going to close this for now because it doesn't seem like an issue with this library, but please re-open it and add additional context if you are able to find anything we can fix here.
