### ISSUE TITLE
ADM API SoapPacker AttributeError

### ISSUE THREAD

**Issue by bry8** [googleads/googleads-python-lib#366]
I upgraded the python library googleads, but get an error while making a request:

from googleads import ad_manager
client = ad_manager.AdManagerClient.LoadFromStorage()
network_service = client.GetService('NetworkService', version='v201811')
current_network = network_service.getCurrentNetwork()

print( 'Found network %s (%s)!' % (current_network['displayName'],
                                  current_network['networkCode'])
    )

--> 396 class _AdManagerPacker(googleads.common.SoapPacker):
    397   """A utility applying customized packing logic for Ad Manager."""
    398 

AttributeError: module 'googleads.common' has no attribute 'SoapPacker'

**Comment by christopherseeley** [comment]
I'm not able to reproduce this, feel free to reopen if it's still an issue.
