### ISSUE TITLE
Unrecognised Version (v201809)

### ISSUE THREAD

**Issue by ketaningle80** [googleads/googleads-python-lib#367]
Hi Team, 

I need to use the AdGroupAdService to add "description2" in the "ad" Operand. This key is supported only in v201809.

I have been using v201806 without any errors so far. However, when I change the version GetService call to 'v201809', I get an error.

Code:
    ad_group_ad_service = adwords_client.GetService('AdGroupAdService', version='v201809')

Error:
GoogleAdsValueError: Unrecognized version for the AdWords API. Given: v201809 Supported: ['v201806', 'v201802']

Traceback:
Traceback (most recent call last):

  File "<ipython-input-24-b3cb8ef9573c>", line 1, in <module>
    ad_group_criterion_service = adwords_client.GetService('AdGroupCriterionService', version='v201809')

  File "C:\ProgramData\Anaconda2\lib\site-packages\googleads\adwords.py", line 360, in GetService
    msg_fmt % ('version', version, _SERVICE_MAP.keys()))

GoogleAdsValueError: Unrecognized version for the AdWords API. Given: v201809 Supported: ['v201806', 'v201802']

Here are version specs:
googleads: 15.0.2
PyYAML: 4.2b4
Python: 2.7.14

**Comment by BenRKarl** [comment]
Hi @ketaningle80 - can you verify that the actual module you're running is the appropriate version? You can do this by inserting the below lines somewhere in your script:

```python
import pkg_resources
print(pkg_resources.get_distribution('googleads').version)
```
