### ISSUE TITLE
Creating New Audience Segment in Google AdManager API

### ISSUE THREAD

**Issue by IndiraAnu** [googleads/googleads-python-lib#370]
Hi,

I am trying to run the python create audience segment function through php file, while calling the php function I am getting this issue. Can you please check and tell me the solution.

"Traceback (most recent call last): File "/var/www/html/seloger/application/libraries/pythonadmanagerapi/examples/ad_manager/v201808/audience_segment_service/create_audience_segments.py", line 22, in from googleads import ad_manager File "build/bdist.linux-x86_64/egg/googleads/__init__.py", line 17, in File "build/bdist.linux-x86_64/egg/googleads/ad_manager.py", line 27, in ImportError: No module named pytz"

Thank you.

**Comment by christopherseeley** [comment]
Do you have pytz installed? The client library uses it
