### ISSUE TITLE
Error after migrating the AdWords API from v201806 to v201809

### ISSUE THREAD

**Issue by STANAPI** [googleads/googleads-python-lib#372]
The way I migrate is to download the updated library from "https://github.com/googleads/googleads-python-lib" and replace the entire “google ads” folder since all DFP has been changed to ad_manager. 

However, after the migration, I got this error below:

**"ImportError: No module named lxml.builder"**

**Comment by wihl** [comment]
Could you post a code snippet? Did you try using the supplied samples?
