### ISSUE TITLE
UTF-8 Issue using AdWordsClient.LoadFromStorage()

### ISSUE THREAD

**Issue by rabochoval** [googleads/googleads-python-lib#375]
Hi all,

Coud you please help me how to change my UTF-8 coding using adwords method AdWordsClient.LoadFromStorage()? My code is very simply:

from googleads import adwords
adwords_client = adwords.AdWordsClient.LoadFromStorage()

Error: Your default encoding, cp65001, is not UTF-8. Please run this script with UTF-8 encoding to avoid errors.

If i set locale to UTF-8 using this
import locale

locale.setlocale(locale.LC_ALL, str('en_US.UTF-8'))
print(locale.getdefaultlocale())

I doesn't change anything...

Any ideas please? I'm using windows

thanks a lot lucie

**Comment by rabochoval** [comment]
one mor ask please - is there a way avoiding to use googleads.yaml?

**Comment by rabochoval** [comment]
I found answer myself, this will help

import locale
import sys
import _locale

_locale._getdefaultlocale = (lambda *args: ['en_US', 'UTF-8'])
print(locale.getdefaultlocale())

**Comment by BenRKarl** [comment]
Hi @rabochoval thanks for sharing the resolution! I'm glad you were able to get it figured out.

**Comment by sakesun** [comment]
Meh. This is silly. Monkey-patching _locale._getdefault should not be considered "solution". This is just a workaround. Please re-open the issue and find proper solution to this issue.
