### ISSUE TITLE
Time error in run_saved_query.py 

### ISSUE THREAD

**Issue by BerkanSezer** [googleads/googleads-python-lib#377]
I want to get data with my query id. I can do that for yesterday but i can't get for "Month to date".
I had this error. `The query specified is not compatible with the API version.`
How can i fix it. Please help me! Thanks

**Comment by BenRKarl** [comment]
@BerkanSezer thanks for bringing this up. Are you able to share the exacy query you're attempting? Also are you using the ad-manager or adwords API?

**Comment by BerkanSezer** [comment]
> @BerkanSezer thanks for bringing this up. Are you able to share the exacy query you're attempting? Also are you using the ad-manager or adwords API?

I'm using AdManager's API 
```
{
    'id': 11111111111,
    'name': 'QUERY_NAME',
    'reportQuery': {
        'dimensions': [
            'PROGRAMMATIC_CHANNEL_NAME'
        ],
        'adUnitView': 'TOP_LEVEL',
        'columns': [
            'TOTAL_LINE_ITEM_LEVEL_IMPRESSIONS',
            'TOTAL_INVENTORY_LEVEL_UNFILLED_IMPRESSIONS',
            'TOTAL_LINE_ITEM_LEVEL_CLICKS',
            'TOTAL_LINE_ITEM_LEVEL_ALL_REVENUE'
        ],
        'dimensionAttributes': [],
        'customFieldIds': [],
        'contentMetadataKeyHierarchyCustomTargetingKeyIds': [],
        'startDate': None,
        'endDate': None,
        'dateRangeType': 'YESTERDAY',
        'statement': {
            'query': ' where parent_ad_unit_id in (SOME_ID, ANOTHER_ID ...)',
            'values': []
        },
        'includeZeroSalesRows': False,
        'adxReportCurrency': None,
        'timeZoneType': 'PUBLISHER'
    },
    'isCompatibleWithApiVersion': True
};
```

This is my query's result. I hope, i fixed it. But it's still a bug

```
saved_query['reportQuery']['dateRangeType'] = 'CUSTOM_DATE'
saved_query['reportQuery']['startDate'] = start_date
saved_query['reportQuery']['endDate'] = yesterday
```

**Comment by christopherseeley** [comment]
This is working as intended. The "Month to date" date range type isn't available in the API: https://developers.google.com/ad-manager/api/reference/latest/ReportService.DateRangeType

To run month to date, you can save the query with a supported date range type and then alter it before running as you've done.
