### ISSUE TITLE
Can't install with pipenv

### ISSUE THREAD

**Issue by knyghty** [googleads/googleads-python-lib#381]
Related to #363

pyyaml have finally released version 5.1. They will not be releasing 4.2 at any point: https://github.com/yaml/pyyaml/issues/193#issuecomment-457387449

This means this library doesn't currently work with any version of PyYAML that will ever get a proper release, and cannot be installed via pipenv without the workaround mentioned in #363

Is this library compatible with 5.1? Can it be unpinned, or up the pin to <6.0?

**Comment by BenRKarl** [comment]
Hi @knyghty - thanks for the heads up! We will definitely want to update that dependency. I opened a PR [here](https://github.com/googleads/googleads-python-lib/pull/382) for this.
