### ISSUE TITLE
create_line_items.py - template

### ISSUE THREAD

**Issue by fdradi** [googleads/googleads-python-lib#383]
Hi everybody, 

I have a stupid question regarding your template "[create_line_items.py](https://github.com/googleads/googleads-python-lib/blob/master/examples/ad_manager/v201902/line_item_service/create_line_items.py)". Why having a for loop with xrange(5)? Naively I wouldn't use any xrange if I wanted create a single line_item..Moreover, I understood I would need a unique ID and not a unique name. Why then a unique name?

Thanks in advance. 

F

**Comment by christopherseeley** [comment]
The example is admittedly contrived and not a real world use case. The xrange is just to demonstrate that you can (and ) create multiple line items in a single request. You do actually need a unique name for line items within the same order, so the example appends a unique ID for ease of use.
