### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'py3kwarning'

### ISSUE THREAD

**Issue by ayan-sw** [googleads/googleads-python-lib#385]
While running get_campaigns.py  i found below error. I was seaching py3kwarning module to solve this but unable to rectify.
AttributeError: module 'sys' has no attribute 'py3kwarning'

**Comment by BenRKarl** [comment]
Hi @ayan-sw thanks for submitting this question. The library doesn't access that attribute on the `sys` module anywhere so I believe it's originating elsewhere. Do you have a full stack trace you can share?
