### ISSUE TITLE
New "Discovery" campaigns are not reporting spend

### ISSUE THREAD

**Issue by apurvis** [googleads/googleads-python-lib#388]
Recently Google Ads rolled out a whole new type of inventory - "Discovery" campaigns - which is in beta.

Making basic AWQL queries (spend by campaign) via this package does not seem to return any spend on these new types of campaigns.  Is that expected or am I missing something?

**Comment by BenRKarl** [comment]
Hi @apurvis thanks for the question. My understanding is that those campaign types aren't available via the API yet. I'm working on getting some more information and will follow up as soon as possible.

**Comment by BenRKarl** [comment]
Closing this as it was opening on the new client library.
