### ISSUE TITLE
Is this repository deprecated?

### ISSUE THREAD

**Issue by tector** [googleads/googleads-python-lib#389]
There is a new official GoogleAds python library here:
https://github.com/googleads/google-ads-python

It is really confusing, because the name is so similar and there is no hint in the official documentation that there is a new and an old version!
Anyways the documentation refers to the other repository, so I wonder if this repository here is deprecated or not...

Any hint would be useful!

**Comment by BenRKarl** [comment]
Hi @tector thanks for posting the question! This repository is not deprecated, however you are correct that there is a new Python library to support the Google Ads API. 

This repository supports two different products - the AdWords API and the Ad Manager API. The AdWords API has been [relaunched](https://ads-developers.googleblog.com/2019/03/upgrade-to-new-google-ads-api-to-get.html) as the Google Ads API and will be deprecated at some point in 2020 in favor of the Google Ads API. 

If you use this library for the AdWords API you should plan to migrate to the [new Google Ads client library](https://github.com/googleads/google-ads-python). We've published a number of resources to help migrate [here](https://developers.google.com/google-ads/api/docs/migration/overview) and more should be coming in the near future.

If you use this library for the Ad Manager API you should continue using it.

Hope that helps, let me know if you have any other questions.
