### ISSUE TITLE
AdWords API: Python2 -> Python3 which library to use?

### ISSUE THREAD

**Issue by mbaader** [googleads/googleads-python-lib#391]
Hi, 

a few days ago, you announced the deprecation for Python 2 in both the AdWords/Google Ad Manager and Google Ads Python client libraries soon in 2019:

https://ads-developers.googleblog.com/2019/04/python-2-deprecation-in-ads-api-client.html

In the AdWords-API library linked there, you'll find this information:

> This library supports both Python 2 and 3. To use this library, you will need to have Python 2.7.9 (or higher) or Python 3.4 (or higher) installed.

https://github.com/googleads/googleads-python-lib

But the examples there clearly will only work for Python2, e.g.:

`print 'CustomerId, Name'
`
from here https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/account_management/get_account_hierarchy.py

... and there is no "from __future__ import..." or something to make those examples viable for Python2 and Python3

So my question is: if I install this library with:.

`pip install googleads
`
will Python3 work or do I have to install a different library?

Regards

**Comment by wihl** [comment]
The library will work. We have not yet updated the legacy samples for Python 3 but we anticipate doing so in a future release.

**Comment by wihl** [comment]
Update: The Python 3 examples are available on the [releases](https://github.com/googleads/googleads-python-lib/releases) page. They have been produced using 2to3.
