### ISSUE TITLE
ontent_metadata_key_hierarchy_service.py is not supported on v201902

### ISSUE THREAD

**Issue by vincent851** [googleads/googleads-python-lib#392]
Hi there, 

The below script does not work. I have to switch the version to 2018 version for this to work.

https://github.com/googleads/googleads-python-lib/tree/master/examples/ad_manager/v201902/content_metadata_key_hierarchy_service

**Comment by christopherseeley** [comment]
The content hierarchy service was removed in v201902, this example was mistakenly included and has been removed.
