### ISSUE TITLE
sqlite3 module is required for the SqliteCache

### ISSUE THREAD

**Issue by linusliu** [googleads/googleads-python-lib#394]
The googleads module could run successfully in my local environment: windows , python 3.6.
However, when I deploy this to AWS lambda function, I got error message: sqlite3 module is required for the SqliteCache: RuntimeError

If possible, please advise me how to fix this issue. thanks

**Comment by BenRKarl** [comment]
Hi @linusliu this library doesn't depend on sqlite3 at all, my guess is you're seeing an unrelated error from the AWS lambda environment.
