### ISSUE TITLE
The example about handling partial failures looks inaccurate when using validateOnly

### ISSUE THREAD

**Issue by sklopfenstein** [googleads/googleads-python-lib#395]
I am calling the OfflineConversionFeedService with `partialFailure` set to True in `validateOnly` mode. Because some of my gclids might be invalid I expect the server to return a SOAP fault, and it does return one that looks perfectly normal. My problem is that it returns it with a 500 code. Is that normal ? I can understand that it makes sense to return a 500 code for the Adwords API. However zeep's behavior is set to [raise](https://github.com/mvantellingen/python-zeep/blob/4df383021e31372c111bc26cbf2e4535deaee04e/src/zeep/wsdl/bindings/soap.py#L357) on 500 codes, and inside `googleads.common.ZeepServiceProxy._CreateMethod`, error handling simply consists in [raising a new error](https://github.com/googleads/googleads-python-lib/blob/aa3b1b474b0f9789ca55ca46f4b2b57aeae38874/googleads/common.py#L1395) so that  if zeep raises on a partial failure, then the method raises as well and no result is returned. One could still except on GoogleAdsServerFault, and then handle partial failures this way, but if this is the way to go then the whole [example about handling partial failure](https://developers.google.com/adwords/api/docs/samples/python/error-handling#handle-partial-failures) is inaccurate when using validateOnly.

**Comment by christopherseeley** [comment]
AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
