### ISSUE TITLE
google-api-client has no member/attribute

### ISSUE THREAD

**Issue by Mattiasg94** [googleads/googleads-python-lib#398]
I'm trying to access google api. There is no member nor attribute of build.

from googleapiclient.discovery import build

service= build('plus', 'v1', developerKey=API_KEY)

items = service.event()

AttributeError: 'Resource' object has no attribute 'event'

**Comment by BenRKarl** [comment]
Hi @Mattiasg94 I believe this was posted to the wrong repository, you probably want to submit an issue here: https://github.com/googleapis/google-api-python-client
