### ISSUE TITLE
target custom criteria

### ISSUE THREAD

**Issue by supermancodez** [googleads/googleads-python-lib#405]
IndexError                                Traceback (most recent call last)
<ipython-input-115-1e5f7ca7a0bb> in <module>
     71   ad_manager_client = ad_manager.AdManagerClient.LoadFromStorage()
     72   main(ad_manager_client, LINE_ITEM_ID, KEY_ID1, KEY_ID2, KEY_ID3, VALUE_ID1,
---> 73        VALUE_ID2, VALUE_ID3)

<ipython-input-115-1e5f7ca7a0bb> in main(client, line_item_id, key_id1, key_id2, key_id3, value_id1, value_id2, value_id3)
     52   # Set custom criteria targeting on the line item.
     53   line_item = line_item_service.getLineItemsByStatement(
---> 54       statement.ToStatement())['results'][0]
     55   line_item['targeting']['customTargeting'] = top_set
     56 

IndexError: list index out of range

**Comment by christopherseeley** [comment]
Looks like your filter statement matched 0 line items. Can you check that whatever you're filtering by actually has results?
