### ISSUE TITLE
Which repo should we be using??

### ISSUE THREAD

**Issue by dangell7** [googleads/googleads-python-lib#407]
I noticed you have two repos for python. Which one should I be using..?

**Comment by BenRKarl** [comment]
@dangell7 This library utilizes the SOAP-based Google Ads API and is installed via `pip install googleads`. The [other library](https://github.com/googleads/google-ads-python) utilizes the new gRPC-based Google Ads API and is installed via `pip install google-ads`. If you are new to the Google Ads API you should use the new gRPC-based library as this library will eventually be deprecated.
