### ISSUE TITLE
How to test client?

### ISSUE THREAD

**Issue by zheller** [googleads/googleads-python-lib#409]
Hi, 

I was hoping you could give some thoughts on best practices on testing the grpc client in unittests? I use https://vcrpy.readthedocs.io/en/latest/ to record http fixtures in test for the old SOAP client and really liked that approach. With the new one, it seems the best shot I have is mocking the client and returning a proto response that is expected from that endpoint. Do you have any other thoughts or any testing tooling for grpc that would be helpful?

**Comment by BenRKarl** [comment]
Hi @zheller since you're referring to gRPC you probably want to submit an issue on [this repo](https://github.com/googleads/google-ads-python/issues). Would you mind resubmitting this there? This library uses SOAP as a protocol not gRPC.
