### ISSUE TITLE
v20.0.0 _not_ compatible with Python 2.

### ISSUE THREAD

**Issue by BenRKarl** [googleads/googleads-python-lib#410]
The most recent version of this library, v20.0.0, was released to deprecate the use of Python 2 in order to prepare for the upcoming 2020 [EOL of Python 2](https://www.python.org/dev/peps/pep-0373/#update).

For context see the deprecation timeline on the [Developer Blog](https://ads-developers.googleblog.com/2019/04/python-2-deprecation-in-ads-api-client.html).

If you are running a version of Python less than 3.6 please do not upgrade this library beyond v19.0.1 until after you're able to upgrade your Python version.

**Comment by thatch** [comment]
If you specify `requires_python >= 3.6` in the metadata, old versions should not attempt to use it...

**Comment by wihl** [comment]
Good suggestion. We do this in [Google Ads API](https://github.com/googleads/google-ads-python/blob/105e558478abd1652c9c67c39f590289841bf0fb/setup.py#L51) and should do it here as well.
