### ISSUE TITLE
getting ads whose campaign id contains a string

### ISSUE THREAD

**Issue by raghav071199** [googleads/googleads-python-lib#411]
How to write a SQL query which gets only those campaign ids which contain a particular string

**Comment by BenRKarl** [comment]
Hi @raghav071199 thanks for the question. Take a look at the grammar for AWQL [here](https://developers.google.com/adwords/api/docs/guides/awql#formal_grammar). You probably want to use the `CONTAINS` operator, for example:

```sql
'... WHERE Id CONTAINS "123456"'
```
