### ISSUE TITLE
Create multiple creativeplaceholders 

### ISSUE THREAD

**Issue by supermancodez** [googleads/googleads-python-lib#414]
In the LineItemService, while creating a line item
I'm unable to put a loop in the creativeplaceholders

'creativePlaceholders': [
            {
                
                'size': {
                    'width': '300',
                    'height': '200'
                }
            }
]

Please help how to make this dynamic and create multiple placeholders without manually adding in the code

**Comment by christopherseeley** [comment]
You can create them in a loop and then set the field:
`` line_item['creativePlaceholders'] = my_creative_placeholders``

**Comment by supermancodez** [comment]
This is not creating new sizes rather overwriting the existing size

**Comment by christopherseeley** [comment]
To clarify, the line item is only a local dictionary until you make the API request:
https://github.com/googleads/googleads-python-lib/blob/master/examples/ad_manager/v201905/line_item_service/create_line_items.py#L154

You can construct the local line item in multiple steps. If you prefer, you can also append to the list:
``line_item['creativePlaceholders'].append(my_creative_placeholder)``

**Comment by supermancodez** [comment]
Thanks a lot, buddy!
it worked
