### ISSUE TITLE
Can we copy creatives other than image creatives?

### ISSUE THREAD

**Issue by supermancodez** [googleads/googleads-python-lib#416]
Can we copy creatives other than image creatives?
if yes, please specify how?

**Comment by christopherseeley** [comment]
Yes, you should be able to copy any creative that uses a [CreativeAsset](https://developers.google.com/ad-manager/api/reference/v201902/CreativeService.CreativeAsset).

Are you having problems with a particular creative type?

**Comment by supermancodez** [comment]
I found the copy image creative.py and I was thinking if it only works for Image Creatives?

**Comment by supermancodez** [comment]
Can you tell me which code will enable to copy any creative

**Comment by christopherseeley** [comment]
That code will work for most creatives. The general idea is to retrieve the creative you want to copy, remove the ID, then update any fields that need to be unique, like name.

You can re-use the creative's assets by ID as long as it's the same network.
