### ISSUE TITLE
Update line item - can't add new creativeplaceholders

### ISSUE THREAD

**Issue by supermancodez** [googleads/googleads-python-lib#418]
I'm trying to add new sizes to a line item using updatelineitem

My code:

updated_line_items = []
    for line_item in response['results']:
          if not line_item['isArchived']:
                my_creative_placeholder = {
                'creativePlaceholders': [
                 {
                     'size': {
                                'width' : '970',
                                'height' : '250'
                              },
                     'size': {
                                'width' : '300',
                                'height' : '250'
                              }
                 }
                  ] 
                }
                line_item.append(my_creative_placeholder)
                updated_line_items.append(line_item)
    line_items = line_item_service.updateLineItems(updated_line_items)

I'm unable to add them. Can anyone help?
Thanks

**Comment by christopherseeley** [comment]
You're not appending to the creative placeholders, but to the line item:
`line_item['creativePlaceholders'].append(my_creative_placeholder)`
