### ISSUE TITLE
For Python 2, response['results'] key may not exist when there are no more entities

### ISSUE THREAD

**Issue by arogal** [googleads/googleads-python-lib#42]
For example, https://github.com/googleads/googleads-python-lib/blob/master/examples/dfp/v201411/creative_service/get_creatives_by_statement.py#L55

# ...
creatives = response['results']
if creatives:
# ...

Should be

creatives = response.get('results', None)

**Comment by nicholaschen** [comment]
marking this as obsolete / wontfix since this failure would happen one way or another. seems like in the context of an example, the stack would give just as much useful info as catching it and throwing a generic error.
