### ISSUE TITLE
Googleads API no response and no error

### ISSUE THREAD

**Issue by rightmentor** [googleads/googleads-python-lib#421]
Hello, 
I am using googleads==15.0.2 with python 2.7

`{'cache': None,
 'client_customer_id': None,
 'custom_http_headers': None,
 'developer_token': '4QlWWyFOeV6WPAkK_R3gJA',
 'enable_compression': False,
 'message_plugin': <googleads.common.LoggingMessagePlugin instance at 0x10f667cb0>,
 'oauth2_client': <googleads.oauth2.GoogleRefreshTokenClient object at 0x10f653f50>,
 'partial_failure': False,
 'proxy_config': <googleads.common.ProxyConfig object at 0x10f66e150>,
 'report_download_headers': {},
 'soap_impl': 'zeep',
 'timeout': 3600,
 'user_agent': 'SodaSpace',
 'validate_only': False}
`
This is the adwords client when i print, can't figure out what exactly the issue is. Please help

**Comment by vallard** [comment]
had this happen too.  No response, no error. Just hangs.  Not sure what issue is.

**Comment by nomadicmind** [comment]
@rightmentor @vallard i've encountered the same issue here, have you been able to figure this issue? does upgrading to newer version help? thanks in advance!

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
