### ISSUE TITLE
Campaign IDs and Budget IDs as 64-bit in Google Ads

### ISSUE THREAD

**Issue by van-ess0** [googleads/googleads-python-lib#422]
Will this change https://ads-developers.googleblog.com/2019/07/campaign-ids-and-budget-ids-as-64-bit.html affect this library (including older versions)?
If so, which version is safe-to-use now?

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
