### ISSUE TITLE
Adding an Ad to an AdGroup

### ISSUE THREAD

**Issue by thierryjacoel** [googleads/googleads-python-lib#423]
I am trying to add an Ad to an AdGroup, but I'm having issues doing so.
I am working with UniversalAppCampaign, so maybe there is a different workflow for this. I couldn't find any example showing how to add a new ad to an existing AdGroup.

Before the new version of the adwords API which introduced AdGroups, I used this code to add a new add from a video's `media_id`:
```
    campaign_service = adwords_client.GetService('CampaignService', version=VERSION)

    operations = [{
        'operator': 'SET',
        'operand': {
            'id': campaign_id,
            'settings': [{
                'xsi_type': 'UniversalAppCampaignSetting',
                'youtubeVideoMediaIdsOps': {
                    'operators': ['UPDATE'],
                },
                'youtubeVideoMediaIds': [media_id],
            }],
        }
    }]

    return campaign_service.mutate(operations)
```

What would be the equivalent to add a new video to an existing AdGroup ?

I have tried the following, but without success:
```
    ad_service = adwords_client.GetService('AdGroupAdService', version=VERSION)

    operations = [{
        'operator': 'ADD',
        'operand': {
            'adGroupId': ad_group_id,
            'xsi_type': 'UniversalAppAd',
            'videos': [
                {
                    'asset': {
                        'xsi_type': 'YouTubeVideoAsset',
                        'youTubeVideoId': video_id,
                    },
                },
            ],
        },
    }]

    return ad_service.mutate(operations)
```

I am getting an error stating that `AdGroupId` is not a valid parameter here.
If I remove this parameter, I get another error `googleads.errors.GoogleAdsServerFault: Unmarshalling Error: cvc-elt.4.3: Type 'ns0:UniversalAppAd' is not validly derived from the type definition, 'AdGroupAd', of element 'ns0:operand'.`
If I try using the `AdService` instead of the `AdGroupAdService`, I get another error `[OperatorError.OPERATOR_NOT_SUPPORTED @ operations[0]]` without further details.

Could you please provide a working example showing how one could add an existing Youtube video to an existing AdGroup (be it from the youtube_id or from the media_id of that video in the campaign)?

**Comment by otso** [comment]
I was also struggling with this, [this example helped me](https://developers.google.com/adwords/api/docs/guides/multi-asset-responsive-display-ads#example).

My take on this is that you can’t add videos to an existing `AdGroup` (or create it via the Google Ads campaign manager) but need to have a "fresh" `AdGroup` to be used together with the descriptions and the headlines in one go. The rule seems to be "[Once an ad is created, it cannot be modified.](https://developers.google.com/adwords/api/docs/common-errors#AdError.CANNOT_USE_AD_SUBCLASS_FOR_OPERATOR)" --> it's immutable.

So the steps as per the above example are:

1) Create the `AdGroup` via the `AdGroupAdService` (campaign needs to exist) 
2) Create the `YouTubeVideoAsset` via the `AssetService` and deposit the `assetId`
3) Add to the created `AdGroup` a `UniversalAppAd` which must include the needed descriptions and headlines (`TextAsset`) along with the video.

Hope this helps.

**Comment by thierryjacoel** [comment]
I'll leave it here, if that can help anybody else:

You cannot just add a new video to the Ad, you need to update the whole Ad. So you need to get its content first, then update it.

I'm using the following function:

```
def add_video_asset_to_ad(ad_id, video_id, asset_id):
    ad_service = adwords_client.GetService('AdService', version=VERSION)

    selector = {
        'fields': [
            'Id',
            'UniversalAppAdDescriptions',
            'UniversalAppAdHeadlines',
            'UniversalAppAdImages',
            'UniversalAppAdYouTubeVideos',
            'UniversalAppAdHtml5MediaBundles',
        ],
        'predicates': [
            {
                'field': 'Id',
                'operator': 'EQUALS',
                'values': [ad_id],
            }
        ],
    }

    ad = ad_service.get(selector)['entries'][0]

    ad['videos'] += [
        {
            'asset': {
                'xsi_type': 'YouTubeVideoAsset',
                'assetId': asset_id,
                'youTubeVideoId': video_id,
            },
        },
    ]

    operations = [{
        'operator': 'SET',
        'operand': ad,
    }]

    return ad_service.mutate(operations)```
