### ISSUE TITLE
Problem while creating Universal App Campaign

### ISSUE THREAD

**Issue by ikkhannn** [googleads/googleads-python-lib#424]
I've been creating a universal app campaign using this sample ,
https://github.com/googleads/googleads-python-lib/blob/aa3b1b474b0f9789ca55ca46f4b2b57aeae38874/examples/adwords/v201809/advanced_operations/add_universal_app_campaign.py

but unfortunately, recently the field names and other settings were changed by google adwords.
I've changed the field names as per told, like they changed the field name "UniversalAppCampaignSetting" to "UniversalAppCampaignInfo" but still I'm getting issues in creating a campaign and also don't know how to create an ad inside of that campaign. My error and code is down below.

### **ERROR**
googleads.errors.GoogleAdsServerFault: Unmarshalling Error: cvc-elt.4.3: Type 'ns0:UniversalAppCampaignInfo' is not validly derived from the type definition, 'Setting', of element 'ns0:settings'.

### **CODE**

`campaign_service = client.GetService('CampaignService', version='v201809')

    budget_id = CreateBudget(client)

    # Create the Universal App campaign.
    universal_app_campaign = {
        'name': 'Cruise App #%s' % uuid.uuid4(),
        'status': 'PAUSED',
        'advertisingChannelType': 'MULTI_CHANNEL',
        'advertisingChannelSubType': 'UNIVERSAL_APP_CAMPAIGN',
        # Set the campaign's bidding strategy. Universal app campaigns only
        # support TARGET_CPA bidding strategy.
        'biddingStrategyConfiguration': {
            # Set the target CPA to $1 / app install.
            'biddingScheme': {
                'xsi_type': 'TargetCpaBiddingScheme',
                'targetCpa': {
                    'microAmount': '1000000'
                }
            },
            'biddingStrategyType': 'TARGET_CPA'
        },
        # Note that only the budgetId is required
        'budget': {
            'budgetId': budget_id
        },
        # Optional fields
        'startDate': (datetime.datetime.now() +
                      datetime.timedelta(1)).strftime('%Y%m%d'),
        'endDate': (datetime.datetime.now() +
                    datetime.timedelta(365)).strftime('%Y%m%d'),
    }

    universal_app_campaign['settings'] = [
        # Set the campaign's assets and ad text ideas. These values will
        # be used to generate ads.
        {
            'xsi_type': 'UniversalAppCampaignInfo',
            'appId': 'com.app'
            'appVendor': 'VENDOR_GOOGLE_MARKET',
        }
    ]

    # Construct operations and add campaigns.
    operations = [{
        'operator': 'ADD',
        'operand': universal_app_campaign
    }]

    campaigns = campaign_service.mutate(operations)['value']`

**Comment by otso** [comment]
Instead of:

    universal_app_campaign['settings'] = [
        # Set the campaign's assets and ad text ideas. These values will
        # be used to generate ads.
        {
            'xsi_type': 'UniversalAppCampaignInfo',
            'appId': 'com.app'
            'appVendor': 'VENDOR_GOOGLE_MARKET',
        }
    ]

try with:

    universal_app_campaign['universalAppCampaignInfo'] = [
          {
            'xsi_type': 'UniversalAppCampaignInfo',
            'appId': <YOUR BUNDLE ID>,
            'appVendor': 'VENDOR_GOOGLE_MARKET',
            'biddingStrategyGoalType': 'OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME',
        }
    ]

**Comment by ikkhannn** [comment]
Thank you, the problem was solved two days ago.
Can you please provide me with the details for how to create an Adgroup and UniversalAppAd in the Universal app campaign?

**Comment by ikkhannn** [comment]
> Instead of:
> 
> ```
> universal_app_campaign['settings'] = [
>     # Set the campaign's assets and ad text ideas. These values will
>     # be used to generate ads.
>     {
>         'xsi_type': 'UniversalAppCampaignInfo',
>         'appId': 'com.app'
>         'appVendor': 'VENDOR_GOOGLE_MARKET',
>     }
> ]
> ```
> 
> try with:
> 
> ```
> universal_app_campaign['universalAppCampaignInfo'] = [
>       {
>         'xsi_type': 'UniversalAppCampaignInfo',
>         'appId': <YOUR BUNDLE ID>,
>         'appVendor': 'VENDOR_GOOGLE_MARKET',
>         'biddingStrategyGoalType': 'OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME',
>     }
> ]
> ```

Thank you, the problem was solved two days ago.
Can you please provide me with the details for how to create an Adgroup and UniversalAppAd in the Universal app campaign?

**Comment by haoshuncheng** [comment]
same problem,have you been solved the problem of "create an Adgroup and UniversalAppAd in the Universal app campaign"?

**Comment by ikkhannn** [comment]
> same problem,have you been solved the problem of "create an Adgroup and UniversalAppAd in the Universal app campaign"?
No, I'm still not able to attach an Ad to it.

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
