### ISSUE TITLE
Get the account hierarchy in json or dictionary format

### ISSUE THREAD

**Issue by ikkhannn** [googleads/googleads-python-lib#427]
I want to get the account hierarchy and I've done it but the sample code provided by the client library only prints it. I want to get the hierarchy in a json object or a  dictionary, which I'm not able to do.

i'm using the below code.

https://developers.google.com/adwords/api/docs/samples/python/account-management#get-the-account-hierarchy-under-the-current-account

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
