### ISSUE TITLE
run_saved_query report generates empty response

### ISSUE THREAD

**Issue by wodecki** [googleads/googleads-python-lib#429]
Hi, 

following Your instructions, I've identified a query ID in my GAM and assigned it to SAVED_QUERY_ID variable. Unfortunately, for many different IDs the script generates just empty response variables (no errors displayed). 

Any idea how to fix it? 

Yours, Andy

**Comment by stephaniesansburywalters** [comment]
Hi there,

I'm hitting the same wall. Did you ever find a solution for this?

Thanks,
Stephanie

**Comment by oguzsimm** [comment]
Hi all,

I have same problem. Did you fix this issue? Can you help me?

Thanks,
Oguz

**Comment by christopherseeley** [comment]
This is likely an API issue and not specific to the Python client library. Make sure the report is shared with the Ad Manager user you're authenticating as in your API request. If that doesn't resolve it, please ask this on the [Ad Manager API forum](https://groups.google.com/g/google-doubleclick-for-publishers-api) and provide SOAP logs.
