### ISSUE TITLE
How to attach an Ad to a universalAppCampaign?

### ISSUE THREAD

**Issue by ikkhannn** [googleads/googleads-python-lib#430]
Hello, Since the format is changed for creating a universal app campaign, I'm having difficulties in creating an ad inside a universalappcampaign

`    universal_app_campaign = {
        'name': 'Cruise App #%s' % uuid.uuid4(),
        'status': 'PAUSED',
        'advertisingChannelType': 'MULTI_CHANNEL',
        'advertisingChannelSubType': 'UNIVERSAL_APP_CAMPAIGN',
        # Set the campaign's bidding strategy. Universal app campaigns only
        # support TARGET_CPA bidding strategy.
        'biddingStrategyConfiguration': {
            # Set the target CPA to $1 / app install.
            'biddingScheme': {
                'xsi_type': 'TargetCpaBiddingScheme',
                'targetCpa': {
                    'microAmount': '1000000'
                }
            },
            'biddingStrategyType': 'TARGET_CPA'
        },
        # Note that only the budgetId is required
        'budget': {
            'budgetId': budget_id
        },
        # Optional fields
        'startDate': (datetime.datetime.now() +
                      datetime.timedelta(1)).strftime('%Y%m%d'),
        'endDate': (datetime.datetime.now() +
                    datetime.timedelta(365)).strftime('%Y%m%d'),
        'universalAppCampaignInfo':{
            'biddingStrategyGoalType':('OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME'),
            'appId': 'com.ik',
            'appVendor': 'VENDOR_GOOGLE_MARKET',}}

    # Construct operations and add campaigns.
    operations = [{
        'operator': 'ADD',
        'operand': universal_app_campaign
    }]

    campaigns = campaign_service.mutate(operations)['value']

`

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
