### ISSUE TITLE
Credentials.py not reading values from Googleads.yaml

### ISSUE THREAD

**Issue by deepakshantilalshah** [googleads/googleads-python-lib#434]
Hi, 

I've configured the googleads.yaml as following. 

`adwords:`
`developer_token: xx-xx-xxx`
`client_customer_id: xx-xx-xxx`
`client_id: xxxxx`
`client_secret: xxx`
 `refresh_token: xxxxx`

Then, when I run a sample, get_campaigns.py (a test code), I got the following error

> google.auth.exceptions.RefreshError: The credentials do not contain the necessary fields need to refresh the access token. You must specify refresh_token, token_uri, client_id, and client_secret.

Upon diagnosing the issue, I found that credentials.py **/usr/local/lib/python3.7/site-packages/google/oauth2/credentials.py** wasn't reading the below values, and was taking the value as **None**. 

>self._refresh_token, self._client_id, self._client_secret (However, it was reading the value for token_uri. 

I did read through the list of open and closed issues, and couldn't find a similar one.

**Comment by BenRKarl** [comment]
Hi @deepakshantilalshah are the values under

**Comment by BenRKarl** [comment]
Hi @deepakshantilalshah are the values in your .yaml file indented? For example:

```
adwords:
  developer_token: ...
```

The values under the `adwords` namespace should be indented by two spaces. See [here](https://github.com/googleads/googleads-python-lib/blob/master/googleads.yaml) for a complete example.

**Comment by deepakshantilalshah** [comment]
Hi Ben, yes they are indented as specified in the example. (Apologies for the formatting). 

I've left Ad manager settings unfilled, and have filled only AdWords settings. 

In addition to this, I've not enclosed client id, client_secret etc in quotation mark.

**Comment by deepakshantilalshah** [comment]
Just one small extra detail that might help: I followed this guide:

https://github.com/googleads/googleads-python-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library

and was able to initialize the client using the below code (in a seperate file) 


`from googleads import adwords


adwords_client = adwords.AdWordsClient.LoadFromStorage()`

Also, I used print statements to verify and indeed the values are not passing to the below file

`xxx/google/oauth2/credentials.py",`

**Comment by deepakshantilalshah** [comment]
I found the problem, I had to post googleads.yaml to my home directory (instead of the project directory). It worked. Thanks for your help.
