### ISSUE TITLE
Add Responsive Display Ad Error

### ISSUE THREAD

**Issue by jasperan** [googleads/googleads-python-lib#435]
https://github.com/googleads/googleads-python-lib/blob/master/examples/adwords/v201809/advanced_operations/add_responsive_display_ad.py

In line: 

  image_data = opener.open(url).read().decode('utf-8')

The correct image uploader should be:

  image_data = opener.open(url).read()

For Python 3.

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
