### ISSUE TITLE
Getting right credentials

### ISSUE THREAD

**Issue by webcrawlerBR** [googleads/googleads-python-lib#438]
I follow these steps to getting started with AdWords API
https://github.com/…/API-access-on-behalf-of-your-clients-(…

But I am stucked in Step 3

flow.fetch_token(code=auth_code)
credentials = flow.credentials

Where Can I put this code? in the request or response(flow.redirect_uri) ?

Cause if is in the Response ... the response function doesnt have Flow objected it was created in the request.

**Comment by christopherseeley** [comment]
You instantiate a `google_auth_oauthlib.flow.Flow` on your callback page the same as Step 1. For a complete example using Flask, you can see the OAuth2 documentation here:
https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code
