### ISSUE TITLE
How to pass the 'Initial List Size' in the UserListOperation's 'operand' field to create 'RuleBasedUserList'?

### ISSUE THREAD

**Issue by muhammadzumair** [googleads/googleads-python-lib#440]
I want to create a _RuleBasedUserList_ with _Initial List Size_ of **'include people from the past 30 days'** (see attachment [here](https://i.imgur.com/xW9nyJv.png)), but I didn't find any property in the operand field with all the other properties ([here↑](https://bit.ly/2pVl95t)) to pass in it. 

![](https://i.imgur.com/xW9nyJv.png)

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
