### ISSUE TITLE
OfflineDataUploadService sample: List type not expected in /remarketing/upload_offline_data.py when enumerating partial errors

### ISSUE THREAD

**Issue by brookjim** [googleads/googleads-python-lib#442]
Exception occurs on line 175 in upload_offline_data.py when there are partial errors after mutate(). 

Exception has occurred: TypeError
list indices must be integers or slices, not list
  File "C:\projects\python-bug\googleads-python-lib\examples\adwords\v201809\remarketing\upload_offline_data - Copy.py", line 175, in main
    failed_offline_data_upload = operations[operation_index]['operand']
  File "C:\projects\python-bug\googleads-python-lib\examples\adwords\v201809\remarketing\upload_offline_data - Copy.py", line 260, in <module>
    ADVERTISER_UPLOAD_TIME, BRIDGE_MAP_VERSION_ID, PARTNER_ID)

The "operation_index" is returned from _GetFieldPathElementIndex as a list type, not simple type.
Steps to Repro:
1) Run pip install googleads
2) Clone the Python client library from https://github.com/googleads/googleads-python-lib
3) Configure ../examples/adwords/v201809/remarketing/upload_offline_data.py with your auth info and sample data
4) Change line 89 to omit currency code like this:
              'currencyCode': '',
5) Run
This will cause a partial error to occur on mutate() and exception while enumerating the partial errors.

![image](https://user-images.githubusercontent.com/57731696/68808572-e50f6b80-061e-11ea-9c2c-da8acce2ab2b.png)

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
