### ISSUE TITLE
Invalid campaign name error when using mutate operation on campaigns names with foreign language characters

### ISSUE THREAD

**Issue by math-max** [googleads/googleads-python-lib#445]
I have a python script that reads all campaign names within an account and then performs a "find, replace" function to follow a new naming convention. I'm getting the CampaignError.INVALID_CAMPAIGN_NAME @ operations[].operand.name when the original campaign name contains character in a foreign language (for instance, it happened with Chinese characters and Thai characters). I'm guessing the problem is with the encoding and decoding of these characters. When I download the report containing the campaign names using .DownloadReportWithAwql, I save it in a dataframe using encoding "utf-8". Later this dataframe containing all campaign names is modified using a dictionary with the "find, replace" rules. 

The script works fine if campaign names have standard characters. Thanks!

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python
