### ISSUE TITLE
Broken Documentation Link in README.md

### ISSUE THREAD

**Issue by powderblock** [googleads/googleads-python-lib#446]
In the README, there is the following [section](https://github.com/googleads/googleads-python-lib#where-can-i-find-the-pydocs):

<img width="313" alt="Broken ReadME" src="https://user-images.githubusercontent.com/1458607/71294270-019d7280-2346-11ea-9b58-7ea706ccb8a8.PNG">

That link leads to the following URL: http://googleads.github.io/googleads-python-lib/

which appears to be no longer valid. Here is a screenshot of what I get on that page:
<img width="960" alt="broken_page" src="https://user-images.githubusercontent.com/1458607/71294320-30b3e400-2346-11ea-8140-c667d33e625e.PNG">

Is there an updated page this should point to? Perhaps it's HTTPS and not HTTP in the URL?

Unsure, need some direction. Any help appreciated.

Thanks in advance! :)

**Comment by christopherseeley** [comment]
That URL is functioning for me - does it work in an incognito window with no browser extensions?

**Comment by wihl** [comment]
I can't reproduce this either. I tried both regular and incognito windows. Can you provide your browser / OS and versions?

**Comment by powderblock** [comment]
It does work in an incognito. Thank you.

**Comment by powderblock** [comment]
Closing now because opening in **incognito fixed the issue!**
