### ISSUE TITLE
Can't transform code into tokens | ConnectionError: Max retries exceeded with url: /o/oauth2/token

### ISSUE THREAD

**Issue by InesCV** [googleads/googleads-python-lib#447]
Hello, I've had for 2 days an issue when I was trying to **transform the Google code into the access and refresh tokens**. The following error kept appearing (and disappearing after a while).

`[ERROR] ConnectionError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6544f6cb50>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

I would like to know:
1) Is there a limit for the code to token exchange? If so, what is that limit?
2) Is this error triggered due to a bad connection with Google? 

Beforehand, thank you very much for your attention.

**Comment by wihl** [comment]
This seems like a connectivity problem. You can try reaching the same URL in your browser or via `curl` to see if it is accessible from your current location. Since you never connected to the server, you won't be hitting any exchange limits.

**Comment by InesCV** [comment]
We are grateful for your rapid response. We don't have the connection error now to test it, but if/when it happens again, we will try that and let you know. Thank you.
