### ISSUE TITLE
Write data to AWS S3 using DownloadReportToFile without using tempfile

### ISSUE THREAD

**Issue by prazserendio** [googleads/googleads-python-lib#455]
Write Google Admanger to AWS s3 using DownloadReportToFile without using tempfile.
(or) Export report csv data content to pandas dataframe using python!

**Comment by wihl** [comment]
Is this a feature request? I highly doubt Google will provide these samples but you are welcome to.  Note that we are looking for volunteers to contribute a Google Ads API -> CSV export example in https://github.com/googleads/google-ads-python/issues/235
