### ISSUE TITLE
Significantly increased memory usage in 23.0.1 compared to 15.0.2

### ISSUE THREAD

**Issue by advance512** [googleads/googleads-python-lib#457]
We've updated the library from v15.0.2 to v23.0.1 in one of our microservices. The code has not changed - the only change is this single requirement/dependency. 

_The memory usage has more than tripled following this change._ 

You can clearly see the issue in this graph of memory utilization, deployment was around 23:00-00:00:
![image](https://user-images.githubusercontent.com/3903412/78932115-a5ef2480-7aaf-11ea-9dd7-1a5439d5cdac.png)
The down-ticks in the graph are because of OOM kills of the microservice.

Is this a known issue? Is anyone else experiencing this problem with the latest version? Any suggestions on how to prevent this degradation in library service, or to minimize it?

Is there any new need to "dispose" of objects created via the library, in a new way, or something else that we might have missed?

**Comment by christopherseeley** [comment]
The library removed suds in favor of zeep as the SOAP library between these releases. I'm closing as but if this is still an issue, please reopen.
