### ISSUE TITLE
Issues reading non ascii characters

### ISSUE THREAD

**Issue by caracas1010** [googleads/googleads-python-lib#46]
Hi there

somehow I have problems pasing non- ascii characters via the python lib to Adwords API, i.e. every time I try to request / send keyword information for non ascii characters (Chinese, Japanese, Rusian, Latin, to name a few) I get the following error 'UnicodeDecodeError: 'ascii' codec can't decode byte...'
Please note I am following the pep-0263 instructions to handle UTF8 decoding

**Comment by msaniscalchi** [comment]
Hello, thanks for the report! You can resolve this by using a unicode string when using non-ascii characters. Not doing so will result in the UnicodeDecodeError you are seeing.
