### ISSUE TITLE
AdWordsClient Error : can't pickle SSLContext objects

### ISSUE THREAD

**Issue by scoyne2** [googleads/googleads-python-lib#468]
I am attempting to authenticate to the AdwordsApi and send a test payload, I am following the google provided code example. When I do so I am hitting an error `can't pickle SSLContext objects`

I've attached the full code that I am running I've also included all packages installed. The full error is attached
```

from googleads import adwords
from googleads import oauth2

def upload_test(payload):
    key_file = "test.json"
    application_name = "google_offline_conversions"

    oauth2_client = oauth2.GoogleServiceAccountClient(key_file, oauth2.GetAPIScope('adwords'))
    client = adwords.AdWordsClient(oauth2_client, application_name)
    adwords_client = client.GetService('OfflineConversionFeedService', version='v201809')

    payload = {'operator': 'ADD', 'operand': payload}

    response = adwords_client.mutate([payload])
    print(response)


if __name__ == '__main__':

    payload_mock = {
        'conversionName': 'GoodRxEvent0',
        'conversionTime': '2020-05-06 14:00:00 America/Los_Angeles',
        'conversionValue': '4.33',
        'googleClickId': "ABCD123",

    }

    upload_test(payload_mock)

```
**Package              Version**
- appdirs              1.4.4
- attrs                19.3.0
- cached-property      1.5.1
- cachetools           4.1.1
- certifi              2020.6.20
- chardet              3.0.4
- defusedxml           0.6.0
- google-auth          1.18.0
- google-auth-oauthlib 0.4.1
- googleads            24.0.0
- idna                 2.10
- isodate              0.6.0
- lxml                 4.5.1
- oauthlib             3.1.0
- pip                  10.0.1
- pyasn1               0.4.8
- pyasn1-modules       0.2.8
- pytz                 2020.1
- PyYAML               5.3.1
- requests             2.24.0
- requests-oauthlib    1.3.0
- requests-toolbelt    0.9.1
- rsa                  4.6
- setuptools           49.1.0
- six                  1.15.0
- urllib3              1.25.9
- xmltodict            0.12.0
- zeep                 3.4.0

[full_error.txt](https://github.com/googleads/googleads-python-lib/files/4885937/full_error.txt)

**Comment by jradcliff** [comment]
Hi,

I looked into this and was able to reproduce by running the code you provided. It looks like this error is happening (somewhat counter-intuitively) when you have not specified the delegated account, which is the user in your domain who you want to impersonate using service account credentials. You can fix this via either of the following options:

1. Also pass the `sub` keyword argument set to the delegated account when creating the OAuth2 client.

         oauth2_client = oauth2.GoogleServiceAccountClient(key_file, 
                                                           oauth2.GetAPIScope('adwords'),
                                                           sub='XYZ@example.com')

1. Switch over to putting the service account JSON path and delegated account in a `~/googleads.yaml` file under the keys `path_to_private_key_file` and `delegated_account`, respectively, and then use `LoadFromStorage()` to construct your AdWords client.

        adwords_client = adwords.AdWordsClient.LoadFromStorage()

Please let me know if that resolves the issue for you.

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Sorry, I just realized I had an issue with my test. Option 1 should be modified to pass the *developer token* as the first argument, then the OAuth2 client and application name:

         oauth2_client = oauth2.GoogleServiceAccountClient(key_file, 
                                                           oauth2.GetAPIScope('adwords'),
                                                           sub='XYZ@example.com')
         client = adwords.AdWordsClient('YOUR_DEVELOPER_TOKEN', oauth2_client, application_name)

Thanks,
Josh

**Comment by scoyne2** [comment]
Thank you @jradcliff that got me past the error!
