### ISSUE TITLE
DFP is not working with google-ad-19.0.0 in python 2.7

### ISSUE THREAD

**Issue by developer-bala** [googleads/googleads-python-lib#469]
My Django application has been integrated with Google Ad sense and it's used to work with Google Ad sense version v201902 through googlead-5.0.2 package.

Now, it stops working and throws the following error,
GoogleAdsValueError: Unrecognized version of the DFP API. Version given: v201902 Supported versions: ['v201702', 'v201608', 'v201611', 'v201605']

Google has mentioned that they are providing the support through googlead version 19.0.0 for python 2, but it is not working....

If we use googlead-19.0.0, the dfp package itself is not importing and it stops the application entirely.

Please help me on this as soon as possible. It is very critical for us.

Thanks in advance..

**Comment by christopherseeley** [comment]
The Ad Manager API v201902 was turned down  at the end of February 2020 in accordance with our [deprecation schedule](https://developers.google.com/ad-manager/api/deprecation).

If you still need python 2.7 support, you can fork the client library at v19.0.0 and add support for newer Ad Manager API versions by updating `ad_manager.py`. You can see an example of this in [this commit](https://github.com/googleads/googleads-python-lib/commit/34b15f69719310d4de67a45207c1e7db4994e7fc#diff-64a40f63a0a14ef4b5a6eee0ff11a87f).
