### ISSUE TITLE
High/Wrong ECPM values

### ISSUE THREAD

**Issue by johndpknt** [googleads/googleads-python-lib#476]
Hello team,

I am tryng to pull adx reports using python API, The downloaded report has very high ECPM and revenue value. Below is my jobQuery

  report_job = {
  'reportQuery': {
      'dimensions': ['AD_EXCHANGE_DATE', 'AD_EXCHANGE_COUNTRY_NAME'],
      'columns': ['AD_EXCHANGE_AD_REQUESTS', 'AD_EXCHANGE_IMPRESSIONS',
                  'AD_EXCHANGE_ESTIMATED_REVENUE','AD_EXCHANGE_AD_ECPM'],
      'dateRangeType': 'LAST_WEEK',
      'timeZoneType': 'AD_EXCHANGE',  # Run in pacific time
      'adxReportCurrency': 'USD'
  }
  }
Downloaded report

Dimension.AD_EXCHANGE_DATE | Dimension.AD_EXCHANGE_COUNTRY_NAME | Column.AD_EXCHANGE_AD_REQUESTS | Column.AD_EXCHANGE_IMPRESSIONS | Column.AD_EXCHANGE_ESTIMATED_REVENUE | Column.AD_EXCHANGE_AD_ECPM
-- | -- | -- | -- | -- | --
2020-11-02 | Afghanistan | 24400 | 1934 | 105034 | 54309
2020-11-02 | Albania | 5285 | 1097 | 68326 | 62284
2020-11-02 | Algeria | 20231 | 2472 | 147793 | 59787
2020-11-02 | American Samoa | 198 | 24 | 1883 | 78448
2020-11-02 | Andorra | 1117 | 98 | 8763 | 89414
2020-11-02 | Angola | 14467 | 2876 | 127484 | 44327
2020-11-02 | Anguilla | 755 | 26 | 1225 | 47132

Please hlpe if there is any bug, or i need to adjust some params or doing wrong ?

Thanks in advance

**Comment by christopherseeley** [comment]
If you are using the CSV_DUMP export format, currency values are represented in micro amounts to be more machine readable:
https://developers.google.com/ad-manager/api/reference/v202011/ReportService.ExportFormat

You can either transform this in post-processing (for US dollars, $1 is 1,000,000 micros), or choose a different export format.
