### ISSUE TITLE
TrackingURLTemplate and UrlCustomParameters Columns not being returned by AdWords Reporting API

### ISSUE THREAD

**Issue by sakkammadam** [googleads/googleads-python-lib#482]
When requesting UrlCustomParameters within Keyword Performance report request, the output is returned as '--' 
We are using Python API to pull data. One of our other team using Java API is able to pull data for this field.

We are using googleads==26.0.0

Thanks,
Sooraj

**Comment by christopherseeley** [comment]
The AdWords API has been turned down and replaced by the Google Ads API:
https://github.com/googleads/google-ads-python/
