### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c.1123)a

### ISSUE THREAD

**Issue by I-akshay** [googleads/googleads-python-lib#483]
When i am trying to run 

client =
adwords.AdWordsClient.LoadFromStorage()
report_downloader = client.GetReportDownloader(version='v201809')
# Create report definition.
report = {
'reportName': 'Last 30 days CRITERIA_PERFORMANCE_REPORT',
'dateRangeType': 'LAST_30_DAYS',
'reportType': 'CRITERIA_PERFORMANCE_REPORT',
'downloadFormat': 'CSV',
'selector': {
'fields': ['CampaignId', 'AdGroupId', 'Id', 'CriteriaType',
'Criteria', 'FinalUrls', 'Impressions', 'Clicks', 'Cost']
}
}
# Print out the report as a string
print(report_downloader.DownloadReportAsString(
report, skip_report_header=False, skip_column_header=False,
skip_report_summary=False, include_zero_impressions=True))

I am constantly getting error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c.1123)a
Please help

**Comment by MegandM** [comment]
Facing same error since 16-04-2021 when calling search_stream method.
`response = GoogleAdsClient.load_from_storage().get_service('GoogleAdsService', version=v5).search_stream(my_client_id, my_query)`

GoogleAdsService version : v5
Python version: 3.9
google-ads package version: 7.0.0

**Comment by MegandM** [comment]
Hi @I-akshay!
Are you running the code behind a enterprise proxy? It could be blocking connections to [googleapis.com](url).

**Comment by aleradamantis99** [comment]
I have the exact same problem

**Comment by christopherseeley** [comment]
Closing as obsolete since this is from 2021, but if anyone is experiencing similar issues a good place to start is looking at proxy settings and environment variables as well as corporate firewall settings as MegandM mentioned.
