### ISSUE TITLE
Disambiguation with google-ads-python

### ISSUE THREAD

**Issue by xavier630** [googleads/googleads-python-lib#484]
There should potentially be a link in the readme to https://github.com/googleads/google-ads-python which is very similarly named but may be what users want.

Also flagging that they have very repo names and package names which is somewhat confusing.

ie
`https://github.com/googleads/google-ads-python` 
vs
`https://github.com/googleads/googleads-python-lib`

and
`from google.ads.googleads.client import GoogleAdsClient` 
vs
`from googleads import ad_manager`

**Comment by christopherseeley** [comment]
Thanks for the feedback. We've updated the title and readme to more clearly indicate that this library is for the Ad Manager SOAP API. Unfortunately, changing the package name would be a breaking change for current users. We may consider renaming the repo in the future as this seems to be [backwards compatible](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository)
