### ISSUE TITLE
BrokenPipeError when updating licas

### ISSUE THREAD

**Issue by robertxandr** [googleads/googleads-python-lib#486]
Following the example to update line item creative association service
https://github.com/googleads/googleads-python-lib/blob/master/examples/ad_manager/v202108/line_item_creative_association_service/update_licas.py

I am running into the below error
`{
"error": "('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))",
"status": 422,
"title": "Unprocessable Entity"
}`

Has anyone else experienced this?

**Comment by msaniscalchi** [comment]
This is rather old so I'm closing it out.

The version you were using at the time no longer exists, but the [v202211 version](https://github.com/googleads/googleads-python-lib/blob/main/examples/ad_manager/v202211/line_item_creative_association_service/update_licas.py) works as expected on my end.
