### ISSUE TITLE
How to generate the refresh token?

### ISSUE THREAD

**Issue by Sammion** [googleads/googleads-python-lib#487]
Hi team, how to generate the refresh token with the client id and client Secret?

**Comment by vijal-patel** [comment]
follow this guide - note the video is useless so ignore it
https://developers.google.com/adwords/api/docs/guides/first-api-call#create_test_accounts

**Comment by smkbarbosa** [comment]
@Sammion change this

```
flow = InstalledAppFlow.from_client_config(
    client_config.Build(), scopes=scopes)
```

for this:

```
flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
        'client_secrets.json', scopes=[oauth2.GetAPIScope('adwords')])
```
