### ISSUE TITLE
CampaignBidModifierService: error no type 'Location'.

### ISSUE THREAD

**Issue by Greta991** [googleads/googleads-python-lib#488]
Hi,
this is my code.

```
criteria = []
campaign_id = 123456789
bid = 1.0
location = [1008827, 1008702, 1008311, 1008577]

for value in location:
    criteria.append({'xsi_type': 'Location', 'id': value})

campaign_bid_modifier_service = client.GetService('CampaignBidModifierService', version='v201809')

# Prepare to add a campaign level override.
operation = {
    # Use 'ADD' to add a new modifier and 'SET' to update an existing one. A
    # modifier can be removed with the 'REMOVE' operator.
    'operator': 'ADD',
    'operand': {
        'campaignId': campaign_id,
        'criterion': criteria,
        'bidModifier': bid
    }
}

response = campaign_criterion_service.mutate([operation])
```

I want to apply the same bid on different locations.

It returns this error: 

`No type 'Location' in namespace https://adwords.google.com/api/adwords/cm/v201809`

I checked the documentation and the 'Location' value is present inside criterion type ([https://developers.google.com/adwords/api/docs/reference/v201809/CampaignBidModifierService.Criterion](https://developers.google.com/adwords/api/docs/reference/v201809/CampaignBidModifierService.Criterion)).

What am i doing wrong?
Thank you.

**Comment by msaniscalchi** [comment]
Closing this out because AdWords has been sunset and removed from this library.
