### ISSUE TITLE
Issue when upgrading from 2.0.2 to 3.2.0

### ISSUE THREAD

**Issue by kiranmadhalam** [googleads/googleads-python-lib#49]
Hi,

I am trying to upgrade a few DFP services and have this below issue. I am using a python 2.6.9 install with a virtual environment one for each 2.0.2 and 3.2.0 . I am behind a proxy and that is configured in the yaml file.(Please note credentials are hashed but i know they work for sure with the old library and a newer API version like v210502)
------------------------------------ Error -----
(venv)[pyve320]$ python test_dfp_access.py
https://xxx.xx.xx.xx:xxxx
Traceback (most recent call last):
  File "test_dfp_access.py", line 18, in <module>
    response = order_service.getOrdersByStatement(statement.ToStatement())
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/googleads/common.py", line 294, in MakeSoapRequest
    self._header_handler.SetHeaders(self.suds_client)
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/googleads/dfp.py", line 316, in SetHeaders
    headers=self._dfp_client.oauth2_client.CreateHttpHeader())
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/googleads/oauth2.py", line 150, in CreateHttpHeader
    self.Refresh()
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/googleads/oauth2.py", line 166, in Refresh
    self.disable_ssl_certificate_validation)))
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/oauth2client/client.py", line 577, in refresh
    self._refresh(http.request)
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/oauth2client/client.py", line 748, in _refresh
    self._do_refresh_request(http_request)
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/oauth2client/client.py", line 777, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/u01/processes/dev2/tst_env/pyve320/venv/lib/python2.6/site-packages/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com
(venv)[pyve320]$
--------------------------------------------- Python Packages
PySocks==1.5.0
PyYAML==3.11
googleads==3.2.0
httplib2==0.9
oauth2client==1.4.7
pyasn1==0.1.7
pyasn1-modules==0.0.5
pytz==2014.10
rsa==3.1.4
six==1.9.0
suds-jurko==0.6
---------------------------------------------googleads.yaml---
<Rmove this>adwords:
<Rmove this>  developer_token: INSERT_DEVELOPER_TOKEN_HERE
<Rmove this>  user_agent: INSERT_USER_AGENT_HERE
<Rmove this>  client_id: INSERT_OAUTH_2_CLIENT_ID_HERE
<Rmove this>  client_secret: INSERT_CLIENT_SECRET_HERE
<Rmove this>  refresh_token: INSERT_REFRESH_TOKEN_HERE
<Rmove this># The following values are optional:
<Rmove this>#  client_customer_id: INSERT_CLIENT_CUSTOMER_ID_HERE
<Rmove this>#  partial_failure: True
<Rmove this>#  validate_only: True
<Rmove this>
<Rmove this>dfp:
<Rmove this>  application_name: DFPRreporting
<Rmove this>  client_id: 999999999999-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.apps.googleusercontent.com
<Rmove this>  client_secret: vvvvvvvvvvvv-lllll-1111
<Rmove this>  refresh_token: 7/888888888888888888888888888888888888-rttttt
<Rmove this># The following values are optional:
<Rmove this>  network_code: 1111
<Rmove this>
<Rmove this>dfa:
<Rmove this>  username: INSERT_DFA_USERNAME_HERE
<Rmove this>  application_name: INSERT_APPLICATION_NAME_HERE
<Rmove this>  client_id: INSERT_OAUTH_2_CLIENT_ID_HERE
<Rmove this>  client_secret: INSERT_CLIENT_SECRET_HERE
<Rmove this>  refresh_token: INSERT_REFRESH_TOKEN_HERE
<Rmove this># The following values are optional:
<Rmove this>
<Rmove this># The following are optional settings for using a proxy.
<Rmove this>proxy_info:
<Rmove this>  host: https://xxx.xx.xx.xx
<Rmove this>  port: yyyy
<Rmove this># The following values are optional:
<Rmove this>#  disable_ssl_certificate_validation: False
<Rmove this>#  ca_certs: INSERT_PATH_HERE
<Rmove this>----------------------------------Test Python Script ---
<Rmove this>import googleads
<Rmove this>from googleads import dfp
<Rmove this>dfp_client = dfp.DfpClient.LoadFromStorage('googleads.yaml')
<Rmove this>
<Rmove this>client = dfp_client
<Rmove this>#print(client)
<Rmove this>print(client.https_proxy)
<Rmove this>order_id = '123456789'
<Rmove this>order_service = client.GetService('OrderService', version='v201502')
<Rmove this>#print(order_service.suds_client)
<Rmove this>
<Rmove this># Create statement object to select a single order by an ID.
<Rmove this>values = [{      'key': 'orderId',      'value': {          'xsi_type': 'NumberValue',          'value': order_id      }  }]
<Rmove this>query = 'WHERE id = :orderId'
<Rmove this>
<Rmove this>statement = dfp.FilterStatement(query, values)
<Rmove this>
<Rmove this>response = order_service.getOrdersByStatement(statement.ToStatement())
<Rmove this>
<Rmove this>orders = []
<Rmove this>if 'results' in response:
<Rmove this>    orders = response['results']
<Rmove this>
<Rmove this># Display results.
<Rmove this>for order in orders:
<Rmove this>    print ('Order with id \'%s\' name \'%s\' was found.'
<Rmove this>           % (order['id'], order['name']))
<Rmove this>
<Rmove this>print '\nNumber of results found: %s' % len(orders)
<Rmove this>
<Rmove this>print('Success')
<Rmove this>
<Rmove this>

**Comment by msaniscalchi** [comment]
Hello,

It looks like you're not getting past the OAuth2 refresh step, but I'm not able to replicate this behavior under similar circumstances. Of note, this library only supports Python 2.7 and 3.3+. While I'm not absolutely certain, the issue might be related to the fact that you're using Python 2.6.9.

I'd suggest trying to run this again on a supported version. If you're still seeing this behavior, I'd recommend that you set up some sort of logging on the proxy and verify that it is actually receiving the requests you're sending.

**Comment by msaniscalchi** [comment]
Feel free to reopen this if still relevant.
