### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='ads.google.com', port=443): Max retries exceeded with url: 

### ISSUE THREAD

**Issue by hamasamray** [googleads/googleads-python-lib#494]
Im not sure how to deal with this error. Any suggestions?

ConnectionError: HTTPSConnectionPool(host='ads.google.com', port=443): Max retries exceeded with url: /apis/ads/publisher/v202108/NetworkService?wsdl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E7646FADF0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by christopherseeley** [comment]
If this is still an issue, I'd recommend checking proxy environment variables and settings. Feel free to reopen if that doesn't resolve it.
