### ISSUE TITLE
allow googleads to install alongside google-auth 2.x

### ISSUE THREAD

**Issue by Commod0re** [googleads/googleads-python-lib#496]
currently you have google-auth pinned to be 1.x: 
```
'google-auth>=1.0.0,<2.0.0'
```

google-auth has been stable above 2.0 for 7 months: https://pypi.org/project/google-auth/#history

I have lightly tested googleads 27.0.0 and 31.0.0 with google-auth 2.6.3 and it seems like it works, any chance the version requirement could be widened to allow 2.x as well?

**Comment by christopherseeley** [comment]
Fixed in v35.0+
