### ISSUE TITLE
Unclear google.ads.googleads.errors.GoogleAdsException: StatusCode.INVALID_ARGUMENT

### ISSUE THREAD

**Issue by kanyaparamita** [googleads/googleads-python-lib#497]
Hi Google Ads API Community,

I received this error for one of my create campaign request:
`Response
-------
Headers: {
  "google.ads.googleads.v10.errors.googleadsfailure-bin": "\n\u0001\n\u0003\u0003\u0002\u0012\u0001Indicates that this request would exceed the number of allowed resources for the Google Ads account. The exact resource type and limit being checked can be inferred from accountLimitType.\u001a\u0002*\u0000\"\u0010\u0012\u000e\n\noperations\u0018\u0000*\n*\b\u0010N\u0018\u0001 N\u0012\u0016ZtnmYPWAMZ0mzxMNUKsLrg",
  "grpc-status-details-bin": "\b\u0003\u0012%Request contains an invalid argument.\u001a\u0002\nDtype.googleapis.com/google.ads.googleads.v10.errors.GoogleAdsFailure\u0012\u0002\n\u0001\n\u0003\u0003\u0002\u0012\u0001Indicates that this request would exceed the number of allowed resources for the Google Ads account. The exact resource type and limit being checked can be inferred from accountLimitType.\u001a\u0002*\u0000\"\u0010\u0012\u000e\n\noperations\u0018\u0000*\n*\b\u0010N\u0018\u0001 N\u0012\u0016ZtnmYPWAMZ0mzxMNUKsLrg",
  "request-id": "ZtnmYPWAMZ0mzxMNUKsLrg"
}
Fault: errors {
  error_code {
    resource_count_limit_exceeded_error: ACCOUNT_LIMIT
  }
  message: "Indicates that this request would exceed the number of allowed resources for the Google Ads account. The exact resource type and limit being checked can be inferred from accountLimitType."
  trigger {
    string_value: ""
  }
  location {
    field_path_elements {
      field_name: "operations"
      index: 0
    }
  }
  details {
    resource_count_details {
      limit: 10000
      limit_type: UNKNOWN
      existing_count: 10000
    }
  }
}
request_id: "ZtnmYPWAMZ0mzxMNUKsLrg"`

I can't really debug this error because it seems to me that this error only applied to my create campaign request with a certain name, because my other create campaign requests worked just fine.

Looking forward to hear from you, thanks!

**Comment by christopherseeley** [comment]
This is the library for the Ad Manager SOAP API. For the Google Ads API, see this repo:
https://github.com/googleads/google-ads-python
