### ISSUE TITLE
Pydocs Link is broken

### ISSUE THREAD

**Issue by tiggeymone** [googleads/googleads-python-lib#498]
Hello, it seems that the link to the pydocs is broken:

http://googleads.github.io/googleads-python-lib

I'm getting a 404 page:

![Screenshot 2022-04-27 at 11 26 23](https://user-images.githubusercontent.com/4254655/165487424-32210119-f7c7-464a-ae1e-ebf773bc053b.png)

**Comment by msaniscalchi** [comment]
Hello, this was an intended change on our part. Our old tooling for generating docs was incompatible with our currently supported versions of Python, and could not be made to work with them. As a result, we opted to simply remove the generated documentation given its low usage and the fact that this library is in more of a maintenance mode at this time.
