### ISSUE TITLE
Data missing for previous day in Historical report.

### ISSUE THREAD

**Issue by bakobako** [googleads/googleads-python-lib#503]
Hi I am downloading 3 historical reports (report 1,2, and 3) for the same date range using report_downloader.DownloadReportToFile. But sometimes data from the previous day (current day -1) is missing in the report 3. 

E.g. i have a new AD_UNIT, it is present in the AD_UNIT_ID of report 1 and present in AD_EXCHANGE_DFP_AD_UNIT_ID of report 2. however it is missing from report 3. When downloading data the next day (current day -2) the data is available in all reports. 

Why does report 3 sometimes have a delay in the data?

I have tried to set include_zero_impressions=True and will monitor this, but should the data be not available in all reports then, if there are zero impressions?

---------------
Report 1 : 
Dimensions:  DATE,AD_UNIT_ID,AD_UNIT_NAME
Metrics : TOTAL_AD_REQUESTS, TOTAL_LINE_ITEM_LEVEL_IMPRESSIONS, TOTAL_LINE_ITEM_LEVEL_ALL_REVENUE, TOTAL_LINE_ITEM_LEVEL_CLICKS
------------
Report 2:  
Dimensions : AD_EXCHANGE_DFP_AD_UNIT,AD_EXCHANGE_DFP_AD_UNIT_ID,AD_EXCHANGE_PRICING_RULE_NAME,DATE
Metrics : AD_EXCHANGE_AD_REQUESTS, AD_EXCHANGE_MATCHED_REQUESTS, AD_EXCHANGE_ESTIMATED_REVENUE, AD_EXCHANGE_IMPRESSIONS, AD_EXCHANGE_CLICKS
---------------
Report 3:
Dimensions : DATE,AD_UNIT_ID,AD_UNIT_NAME,LINE_ITEM_TYPE
Metrics : TOTAL_LINE_ITEM_LEVEL_IMPRESSIONS, TOTAL_LINE_ITEM_LEVEL_ALL_REVENUE, TOTAL_LINE_ITEM_LEVEL_CLICKS

**Comment by christopherseeley** [comment]
This is an API issue and not specific to the Python client library. If this issue is still ongoing, can you raise it on the API forum here?
https://groups.google.com/g/google-doubleclick-for-publishers-api
