### ISSUE TITLE
Getting google.api_core.exceptions.Unknown: None Stream removed

### ISSUE THREAD

**Issue by arthii17** [googleads/googleads-python-lib#507]
I am getting the following error for one of my accounts. Please help ! 
Error : 
Request made: ClientCustomerId: 7123341416, Host: googleads.googleapis.com, Method: /google.ads.googleads.v10.services.GoogleAdsService/SearchStream, RequestId: None, IsFault: True, FaultMessage: Stream removed

 raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None Stream removed

**Comment by christopherseeley** [comment]
This is the library for the Ad Manager SOAP API, for the Google Ads API, see this repo:
https://github.com/googleads/google-ads-python
