### ISSUE TITLE
Google Group for the Ads API no longer available

### ISSUE THREAD

**Issue by heyman** [googleads/googleads-python-lib#533]
Hi!

The [Google Group for the Ads API](https://groups.google.com/g/adwords-api/) is no longer accessible. 

From the error message it sounds like it has been closed down (in error) by some automated system:

<img width="941" alt="image" src="https://github.com/googleads/googleads-python-lib/assets/54217/2b949043-af33-4e5d-af58-b1749fb97ba3">

It's been like this for a couple of days.

Sorry that this isn't an issue related to the python library. Don't know the best channel to raise this issue, but I'm guessing this might work?

**Comment by msaniscalchi** [comment]
Hello,

This library hasn't supported Google Ads for quite some time, but my understanding is that you can use the contact form embedded in the [developer documentation support page](https://developers.google.com/google-ads/api/support) to get in touch with somebody who can assist with technical questions as an alternative. They would also probably have better context about the specifics of the situation with the forum. Hope that helps!

Regards,
Mark
