### ISSUE TITLE
Google Ad Manager API - googleads library compatibility

### ISSUE THREAD

**Issue by Morgan-cj** [googleads/googleads-python-lib#534]
I am currently using googleads library https://github.com/googleads/googleads-python-lib version 32.0.0, but I can successfully use 202308 version of GAM API and this is a bit confusing as the 202308 release was in 39.0.0. So how does it actually can work?

Is it some compatibility between googleads library and GAM API or can I just use any non deprecated version of the GAM API on any version on of the googleads library?

**Comment by christopherseeley** [comment]
The library will dynamically generate stubs from the SOAP WSDL based on the version you pass:
https://github.com/googleads/googleads-python-lib/blob/4d40a9eac3dbdb4b73db99b5606e79326a64c78e/googleads/ad_manager.py#L382

Just updating the version number and not the library version may work but there are edge cases that could cause problems for you. I'd recommend updating the library when you update API versions. There are typically no breaking changes outside of removing support for API versions that have been turned down.
