### ISSUE TITLE
When is googleads 36.0.0 python package sunset date?

### ISSUE THREAD

**Issue by HemanthKumar8124** [googleads/googleads-python-lib#535]
Hi Team,

We are currently using googleads 36.0.0 python package for connecting to the ReportService API and in order to fetch data. 

We would like to know when this package is going to be depreciated so that we can make changes according to it.

**Comment by HemanthKumar8124** [comment]
@ msaniscalchi,
FYI

**Comment by christopherseeley** [comment]
Ad Manager API versions are available for ~1 year after release. For example, v202308 was released in August 2023 and will be available through August 2024.

The full deprecation schedule is available here:
https://developers.google.com/ad-manager/api/deprecation

There is a CSV available here if you want to programmatically check API version support:
https://developers.google.com/static/ad-manager/downloads/api-schedule.csv

The Python client library is updated quarterly to add/remove support versions in accordance with this schedule.

**Comment by HemanthKumar8124** [comment]
@christopherseeley , Thanks for the update. But my ask here is about Python package (googleads) depreciation not API version sunset.

https://pypi.org/project/googleads/36.0.0/

**Comment by msaniscalchi** [comment]
Strictly speaking, we don't actively prevent the installation of older versions. You could hypothetically go back to [1.0.0](https://pypi.org/project/googleads/1.0.0/), although that is unlikely to be a great choice for several reasons. The single most significant reason to keep up with the library updates is that the API itself will deprecate and sunset versions. Even if an API version still exists in an older version of the library, it would not function if the underlying API was sunset.

With that context, what Chris is saying above means that regardless of whether you can download and install version 36.0.0 of the library, all of the API versions that exist within that version of the library will be inaccessible some day. It would happen about one year after the latest release introduced in 36.0.0.
