### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]: unable to get local issuer certificate

### ISSUE THREAD

**Issue by divyasri2511** [googleads/googleads-python-lib#543]
I am working on  AD MANAGER API,

when i gave, 
 report_downlaoder = client.GetDataDownloader(version=v202308)
report_job_id = report_downloader.WaitForReport(report_job)
export_format = 'CSV_DUMP'
report_file = tempfile.NamedTemporaryFile(suffix=' .csv.gz', delete=False)
download_file = report_downloader.DownloadReportToFile(report_job_id, export_foramt, report_file).

in download_file getting error.
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]: unable to get local issuer certificate

**Comment by msaniscalchi** [comment]
This error suggests the SSL step that verifies the certificate failed. Lacking context about or access to the device that ran this, it's hard to say what specifically went wrong. Given the lack of a broader report of something quite serious such as our certificate expiring, I would expect this to be more of a local configuration issue. There could be a VPN or proxy issue at play, or perhaps something wrong with the certificate store on your device.

In the context of this library, I don't think this is something we can replicate on our end, so I recommend investigating more generally what configurations in your environment might have led to this error.
