### ISSUE TITLE
Clarification and Example Needed for performCompanyAction on Child Publishers, Specifically EndAgreementAction

### ISSUE THREAD

**Issue by arezitopedia** [googleads/googleads-python-lib#545]
Hello! I am currently working with an account that has thousands of child publishers and need clarification on how to safely perform performCompanyAction for a child publisher, specifically EndAgreementAction.

I have a few concerns and questions:

## Safety of EndAgreementAction:

If an APPROVED child publisher mistakenly gets called with EndAgreementAction, will it indeed end the agreement?
Is this action the same as the "Withdraw Agreement" option available in the UI for Inactive child publishers?
![image](https://github.com/user-attachments/assets/9d4dac1f-12fe-4ef1-80e9-c43a7dc75bab)

## Lack of Examples and Documentation:

There are no examples or detailed documentation on how to apply performCompanyAction for child publishers in any of the Google Ads libraries (I am developing using python). Could you provide an example or more detailed documentation on how to use performCompanyAction for child publishers? Specifically, an example of how to correctly implement EndAgreementAction for an specific child publisher. would be highly appreciated 

Here is the reference for CompanyService.EndAgreementAction: https://developers.google.com/ad-manager/api/reference/v202402/CompanyService.EndAgreementAction

Thank you for your assistance!

**Comment by arezitopedia** [comment]
@msaniscalchi Could you please help me with this issue or refer me where could I get support?

**Comment by msaniscalchi** [comment]
Hello. This sounds like reasonable feedback to me, though the primary goal of support on this issue tracker is to ensure the library itself and existing samples function as intended. I can't guarantee that it is actionable at this time, but I recommend you direct this feedback to the Developer Relations Ad Manager support alias: admanagerapi-support@google.com.
