### ISSUE TITLE
Create Creatives Using Lineitemid

### ISSUE THREAD

**Issue by ssalmans428** [googleads/googleads-python-lib#551]
Hi Team,

I am completely new to the google ads, by going through the available options i understood that first we have to upload the creative to the creative directory, then we need to associate the creative with the line item id.

But what i want to know is is there any python script or any other way available so that we can directly upload the creative to the specific line item id, under the line item id to the specific slot.

By doing this we can reduce the time, if there is any error while uploading the creative api will throw the corresponding error.

Finally, can we upload the creatives like how we will do through Google Ad Manager UI?

The new REST API will support this type of mechanism?

Thanks

**Comment by christopherseeley** [comment]
Yes, you can create creatives and then associate them with the line items.

There are examples of creating different creative types available here:
https://github.com/googleads/googleads-python-lib/tree/main/examples/ad_manager/v202408/creative_service

And here's an example of creating the LineItemCreativeAssociation - this is what links the creative to the line item:
https://github.com/googleads/googleads-python-lib/blob/main/examples/ad_manager/v202408/line_item_creative_association_service/create_licas.py

The REST API doesn't support these feature yet, but it is on the roadmap

**Comment by ssalmans428** [comment]
Hi @christopherseeley 

I dont want to use create the creatives and then associate with line item.

is there any straight forward method/process to create the creative under an line item directly or any road map for that feature?

Thanks

**Comment by christopherseeley** [comment]
You must create a creative and then create the association, there is no way to do this transactionally. This is also what the UI does when you add a creative from the line item page. Creatives are a separate entity, there are no creatives "under" a line item.
