### ISSUE TITLE
Any modifications needed to cope with this depreication http://googleadsdeveloper.blogspot.com/2015/04/sunset-of-v201403-of-dfp-api.html

### ISSUE THREAD

**Issue by auvipy** [googleads/googleads-python-lib#61]
need to know if the library need any modification?

**Comment by auvipy** [comment]
http://googleadsdeveloper.blogspot.com/2015/04/sunset-of-v201403-of-dfp-api.html

**Comment by msaniscalchi** [comment]
No, you shouldn't need to perform any modifications yourself. Well, unless you're using v201403. In that case you'd need to migrate. We keep these libraries up to date with the latest API versions and remove older versions as they are sunset.

**Comment by auvipy** [comment]
i will be using latest API :)

thanks.
