### ISSUE TITLE
v201506 of the AdWords API

### ISSUE THREAD

**Issue by anton-ovinnikov** [googleads/googleads-python-lib#64]
A week ago it [was announced](http://googleadsdeveloper.blogspot.ru/2015/06/announcing-v201506-of-adwords-api.html) that AdWords is moving to the new version. Is there any priority to update the googleads library to support it?

Thanks.

**Comment by msaniscalchi** [comment]
Hello Anton,

Sorry for any confusion on this, the release was pushed to [PyPI](https://pypi.python.org/pypi/googleads/3.5.0) last week. An internal issue disrupted our usual push to GitHub that typically follows our PyPI release.

We'll make the release here a little later today and close this issue when it is out.

**Comment by msaniscalchi** [comment]
We're waiting on an internal fix for this, so the push to GitHub will be delayed a bit longer. As I mentioned earlier, you can grab the latest release from [PyPI](https://pypi.python.org/pypi/googleads/3.5.0) in the meantime.

I will close this issue when we've resolved the issue and pushed the release to GitHub.
