### ISSUE TITLE
Inconsistent partial error handling with Ads Py Google

### ISSUE THREAD

**Issue by btourtellott** [googleads/googleads-python-lib#65]
One difference between Google Ads and Ads Py Google is when sending a mutate operation with the “partial failure” (https://github.com/googleads/googleads-python-lib/blob/master/googleads/adwords.py L190) option set to true. In Ads Py Google, the returned Python dictionary would have the key “value” which is a list of all the successful mutated entities. Any unsuccessful mutated entities are omitted from this list, and included in the list keyed by “partialFailureErrors”. In Google Ads, the returned Python Suds object has the attribute “value”, which returns a list of the successful mutated entities, but includes an empty “suds.sax.text.Text” field as a placeholder for where the entities that did not mutate successfully occurred. Basically in Ads Py Google, they were omitted from “value”, but in Google Ads they have a placeholder in “value”.
 
Are you guys aware of this difference? I am curious if this is expected behavior, and if it is something that we should expect going forward.

**Comment by msaniscalchi** [comment]
Hello, thanks for the report! My impression is that this sounds like a difference in how our SOAP client handles the AdWords response. While we have no commitment to match the adspygoogle behavior, we typically do. I'd be interested in seeing some logs that demonstrate the behavior if you can reproduce.

**Comment by btourtellott** [comment]
This is posting two new campaign feeds. The second one has a bogus feed id.
```python
operands = [{u'operator': u'ADD',
           u'operand': {u'matchingFunction': {u'lhsOperand': [{u'booleanValue': u'false',
                                                               u'type': u'BOOLEAN',
                                                               u'xsi_type': u'ConstantOperand'}],
                                              u'operator': u'IDENTITY'},
                        u'feedId': [REMOVED],
                        u'placeholderTypes': [u'17'],
                        u'campaignId': [REMOVED]},
           u'xsi_type': u'CampaignFeedOperation'},
          {u'operator': u'ADD',
           u'operand': {u'matchingFunction': {u'lhsOperand': [{u'booleanValue': u'false',
                                                               u'type': u'BOOLEAN',
                                                               u'xsi_type': u'ConstantOperand'}],
                                              u'operator': u'IDENTITY'},
                        u'feedId': u'0', # bogus feedId
                        u'placeholderTypes': [u'17'],
                        u'campaignId': [REMOVED]},
           u'xsi_type': u'CampaignFeedOperation'}]

# c_feed_service created with AdWordsClient.partial_failure=True
result = c_feed_service.mutate(operands)
print result
```
The result of the print:
```python
(rval){
   ListReturnValue.Type = "CampaignFeedReturnValue"
   value[] = 
      (value){
         feedId = [REMOVED]
         campaignId = [REMOVED]
         matchingFunction = 
            (matchingFunction){
               operator = "IDENTITY"
               lhsOperand = 
                  (lhsOperand){
                     FunctionArgumentOperand.Type = "ConstantOperand"
                     type = "BOOLEAN"
                     unit = "NONE"
                     booleanValue = "false"
                  }
               functionString = "IDENTITY(false)"
            }
         placeholderTypes = "17"
         status = "ENABLED"
      },
      "", <-- **** This is the inconsistency ****
   partialFailureErrors = 
      (partialFailureErrors){
         fieldPath = "operations[1].operand.feedId.id"
         trigger = ""
         errorString = "RangeError.TOO_LOW"
         ApiError.Type = "RangeError"
         reason = "TOO_LOW"
      }
 }<empty>
```

**Comment by nicholaschen** [comment]
similar to https://github.com/googleads/googleads-python-lib/issues/67, but I'll let Mark comment on the behavioral impacts of this moving forward. I'd be inclined to say that this should be the expectation moving forward.
