### ISSUE TITLE
DownloadReportAsString with GZIPPED_XML format?

### ISSUE THREAD

**Issue by yaghmr** [googleads/googleads-python-lib#69]
Can I use ```DownloadReportAsString``` with ```GZIPPED_XML``` format?

I try to decompress with ```StringIO``` and ```gzip``` but i get this error:

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

What is wrong?

**Comment by msaniscalchi** [comment]
Hello,

DownloadReportAsString is specifically meant to be used when the response is a string. If you are retrieving binary data in the form of a gzipped file, you shouldn't use this convenience method. Instead, you can just use DownloadReport specifying a binary file or BytesIO as the output.
