### ISSUE TITLE
Missing instruction about adding six package in readme.md

### ISSUE THREAD

**Issue by sandeepkoduri** [googleads/googleads-python-lib#71]
Missing instruction about adding six package in readme.md, rest its pretty cool.
Thanks,

**Comment by nicholaschen** [comment]
hi Sandeep,

My guess is that this is for the Google API Python client? (for service accounts?). I'm just trying to track down what the appropriate place to plug in the verbiage should be...

**Comment by nicholaschen** [comment]
So I did some digging, I think this is only specific to the AppEngine AdWords demo right? Even then, I think Six is a secondary dependency of an external lib (which I would hope they would list as a dependency!), so I don't know that this is something we can (or rather, *should*) add on our end. If you have any other concerns with this, please just reopen this issue.
