### ISSUE TITLE
testInitializeWithDefaultApplicationName calls googleads.dfp.DfpClient with wrong arity

### ISSUE THREAD

**Issue by pbx** [googleads/googleads-python-lib#72]
The `assertRaises` call in `testInitializeWithDefaultApplicationName` in `dfp_test.py` passes six non-self arguments to `DfpClient.__init__`, but it only takes five non-self arguments.

I haven't yet determined what was intended here. If I figure that out I'll fix and add a PR. 

```
$ python tests/dfp_test.py 
............E...
======================================================================
ERROR: testInitializeWithDefaultApplicationName (__main__.DfpClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cmg/.virtualenvs/googleads-py27/src/gads/tests/dfp_test.py", line 172, in testInitializeWithDefaultApplicationName
    googleads.dfp.DEFAULT_APPLICATION_NAME)
  File "/usr/lib/python2.7/unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
TypeError: __init__() takes at most 6 arguments (7 given)

----------------------------------------------------------------------
Ran 16 tests in 0.047s

FAILED (errors=1)
```

**Comment by pbx** [comment]
Aha. `assertRaises` doesn't take an error message argument.  PR forthcoming.

https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaises

**Comment by nicholaschen** [comment]
I'm not actually seeing this test fail in the latest release... also, it looks like assertRaises allows for *args no? Which release tag is this for?

**Comment by pbx** [comment]
Sorry, I should have specified.  This is for current master HEAD, aka 8ff151f. Here's a full session showing the output from all the tests, plus environment data: http://dpaste.com/10GFDB1 

As far as I can tell `*args` and `**kwargs` in the `assertRaises` signature are solely for arguments to the callable under test.

**Comment by nicholaschen** [comment]
Heya,

Sorry, haven't forgotten about this! Will take a look in the upcoming week.

Nicholas

**Comment by pbx** [comment]
Thanks! If you have trouble reproducing I'm happy to share any other relevant info.

**Comment by nicholaschen** [comment]
:) this is actually something that I don't think anyone realized was a breaking change (which it's not really I guess, since this is a test), but expect this to be fixed in the next release which should happen later this month!

**Comment by pbx** [comment]
Thanks, @nicholaschen. I look forward to it.
