### ISSUE TITLE
Sitelinks extensions example problem

### ISSUE THREAD

**Issue by gosom** [googleads/googleads-python-lib#75]
I am using v201502 .

According to the docs when you want to create sitelinks extensions we should
change the sitelinkUrl to sitelinkFinalUrls and the value should be an array of urls.

In your example [https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fgoogleads%2Fgoogleads-python-lib%2Fblob%2Fmaster%2Fexamples%2Fadwords%2Fv201502%2Fextensions%2Fadd_site_links.py%23L55&sa=D&sntz=1&usg=AFQjCNGo-RPNJq40T9ePRcSCZV7HF1pQyQ ]

you use sitelinkUrl.

Although I haven't run your example in my code (which is written based on the example) I get an error:

WRITE_ACCESS_DENIED

I found this forum post:
https://groups.google.com/forum/#!topic/adwords-api/iYhpm7Cp1kU%5B1-25%5D
which describes the same problem.

As Josh Radcliff suggested we should change the sitelinksUrl -> sitelinksFinalUrls and put an array instead of a string.

I have tried that and this is the message (from the suds logs) that the library sends:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
    xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201502"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:tns="https://adwords.google.c
om/api/adwords/cm/v201502"
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header>
        <tns:RequestHeader>
            <tns:clientCustomerId>xxxx</tns:clientCustomerId>
            <tns:developerToken>xxxx</tns:developerToken>
            <tns:userAgent>my ua</tns:userAgent>
            <tns:validateOnly>false</tns:validateOnly>
            <tns:partialFailure>false</tns:partialFailure>
        </tns:RequestHeader>
    </SOAP-ENV:Header>
    <ns0:Body>
        <ns1:mutate>
            <ns1:operations>
                <ns1:operator>ADD
                </ns1:operato
r>
                <ns1:operand>
                    <ns1:campaignId>xxxx</ns1:campaignId>
                    <ns1:extensionType>SITELINK</ns1:extensionType>
                    <ns1:extensionSetting>
                        <ns1:extensions xsi:type="ns1:SitelinkFeedItem">
                            <ns1:ExtensionFeedItem.Type>SitelinkFeedItem</ns1:ExtensionFeedItem.Type>
                            <ns1:sitelinkTe
xt>Kontakt
                            </ns1:sitelinkText>
                            <ns1:sitelinkFinalUrls>http://xxxx.de</ns1:sitelinkFinalUrls>
                        </ns1:extensions>
                        <ns1:extensions xsi:type="ns1:SitelinkFeedItem">
                            <ns1:ExtensionFeedItem.Type>SitelinkFeedItem</ns1:ExtensionFeedItem.Type>
                            <ns1:sitelinkTex
t>Dienstleistungen
                            </ns1:sitelinkText>
                            <ns1:sitelinkFinalUrls>http://xxxx.de</ns1:sitelinkFinalUrls>
                        </ns1:extensions>
                        <ns1:extensions xsi:type="ns1:SitelinkFeedItem">
                            <ns1:ExtensionFeedItem.Type>SitelinkFeedItem</ns1:ExtensionFeedItem.Type>
                            <ns1:sit
elinkText>Dienstleister
                            </ns1:sitelinkText>
                            <ns1:sitelinkFinalUrls>http://xxxx.de</ns1:sitelinkFinalUrls>
                        </ns1:extensions>
                        <ns1:extensions xsi:type="ns1:SitelinkFeedItem">
                            <ns1:ExtensionFeedItem.Type>SitelinkFeedItem</ns1:ExtensionFeedItem.Type>
                            <ns1:sitelinkText>Gebäudereinigung
                            </ns1:sitelinkText>
                            <ns1:sitelinkFinalUrls>http://xxxx.de</ns1:sitelinkFinalUrls>
                        </ns1:extensions>
                    </ns1:extensionSetting>
                </ns1:operand>
            </ns1:operations>
        </ns1:mutate>
    </ns0:Body>
</SOAP-ENV:Envelope>

Then I got an exception:

Traceback (most recent call last):
  File ".../app/utils/actions.py", line 110, in perform
    ret = self.callback(self.order, *self.args)
  File ".../app/scheduler/funcs.py", line 80, in do
    d = adw.create_sitelinks(order)
  File ".../app/services/adword_service/adwordwrapper.py", line 235, in create_sitelinks
    response = campaign_extension_setting_service.mutate([operation])
  File ".virtualenvs/adwiz/lib/python2.7/site-packages/googleads/common.py", line 296, in MakeSoapRequest
    for arg in args])
  File "/home/lawalpha9marketi/.virtualenvs/adwiz/lib/python2.7/site-packages/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File virtualenvs/adwiz/lib/python2.7/site-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File ".virtualenvs/adwiz/lib/python2.7/site-packages/suds/client.py", line 649, in send
    result = self.failed(binding, e)
  File ".virtualenvs/adwiz/lib/python2.7/site-packages/suds/client.py", line 702, in failed
    r, p = binding.get_fault(reply)
  File adwiz/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault
    raise WebFault(p, faultroot)
WebFault: Server raised fault: 'Unmarshalling Error: cvc-complex-type.2.3: Element 'ns1:sitelinkFinalUrls' cannot have character [children], because the type's content type is element-only. '

**Comment by msaniscalchi** [comment]
Hello, we resolved this issue a while back. It looks like I neglected to close this bug afterward though, sorry about that.

Thanks for the report!
