### ISSUE TITLE
Example get_account_changes.py is broken

### ISSUE THREAD

**Issue by aaur0** [googleads/googleads-python-lib#85]
examples/adwords/v201509/account_management/get_account_changes.py fails with error 

"'CampaignChangeData' object has no attribute 'get'" 

  if (data['campaignChangeStatus'] != 'NEW' and
            data['campaignChangeStatus'] != 'FIELDS_UNCHANGED'):
           **print '  Removed ad extensions: %s' % data.get('deletedAdExtensions')**

It seems that the data object is fetched wrong.

**Comment by msaniscalchi** [comment]
Hello, this issue was resolved a while back, but it looks like I forgot to close out this issue. Sorry about that, and thanks for the report!
