### ISSUE TITLE
Unable to recognize VIDEO_PERFORMACE_REPORT 

### ISSUE THREAD

**Issue by gaurav3ansal** [googleads/googleads-python-lib#94]
Hi Team,
I got an error while tryin' to fetch/download VIDEO_PERFORMACE_REPORT. It seems that this report is not listed in the library. Could you please take a look into this?

AdWordsReportBadRequestError: Type: ReportDownloadError.INVALID_REPORT_DEFINITION_XML
Trigger: Invalid ReportDefinition Xml: cvc-enumeration-valid: Value 'VIDEO_PERFORMANCE_REPORT' is not facet-valid with respect to enumeration 
'[KEYWORDS_PERFORMANCE_REPORT, 
AD_PERFORMANCE_REPORT, 
URL_PERFORMANCE_REPORT, 
ADGROUP_PERFORMANCE_REPORT, 
CAMPAIGN_PERFORMANCE_REPORT, 
ACCOUNT_PERFORMANCE_REPORT, 
GEO_PERFORMANCE_REPORT, 
SEARCH_QUERY_PERFORMANCE_REPORT, 
AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT, 
CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT, 
CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT, 
DESTINATION_URL_REPORT, 
SHARED_SET_REPORT, 
CAMPAIGN_SHARED_SET_REPORT, 
SHARED_SET_CRITERIA_REPORT, 
CREATIVE_CONVERSION_REPORT, 
CALL_METRICS_CALL_DETAILS_REPORT, 
KEYWORDLESS_QUERY_REPORT, 
KEYWORDLESS_CATEGORY_REPORT, 
CRITERIA_PERFORMANCE_REPORT, 
CLICK_PERFORMANCE_REPORT, 
BUDGET_PERFORMANCE_REPORT, 
BID_GOAL_PERFORMANCE_REPORT, 
DISPLAY_KEYWORD_PERFORMANCE_REPORT, 
PLACEHOLDER_FEED_ITEM_REPORT, 
PLACEMENT_PERFORMANCE_REPORT, 
CAMPAIGN_NEGATIVE_LOCATIONS_REPORT, 
GENDER_PERFORMANCE_REPORT, 
AGE_RANGE_PERFORMANCE_REPORT, 
CAMPAIGN_LOCATION_TARGET_REPORT, 
CAMPAIGN_AD_SCHEDULE_TARGET_REPORT, 
CAMPAIGN_PLATFORM_TARGET_REPORT, 
PAID_ORGANIC_QUERY_REPORT, 
AUDIENCE_PERFORMANCE_REPORT, 
DISPLAY_TOPICS_PERFORMANCE_REPORT, 
USER_AD_DISTANCE_REPORT, 
SHOPPING_PERFORMANCE_REPORT, 
PRODUCT_PARTITION_REPORT, 
PLACEHOLDER_REPORT, 
AD_CUSTOMIZERS_FEED_ITEM_REPORT, 
LABEL_REPORT, 
FINAL_URL_REPORT, 
UNKNOWN]'. It must be a value from the enumeration.
Field Path: None

**Comment by msaniscalchi** [comment]
Hello,

The report you're referencing was added in v201601, so it sounds likely that you attempted to grab the report with an older version. Could you confirm whether you're still experiencing this issue and the version that you're using?

**Comment by gaurav3ansal** [comment]
Hi, 

I changed the version to v201601 and did an upgrade to googleads package and VIDEO_PERFORMACE_REPORT executed perfectly.

Thank you very much for your support. I really appreciate it.
