### ISSUE TITLE
Bug caused by unicode problem of Python in ManagedCustomerService Soap parsing.

### ISSUE THREAD

**Issue by maxsonic** [googleads/googleads-python-lib#95]
Hi,

I have the error as shown in the first pic below. It seems that it is caused by the decoding of the soap xm. The second pic  is my code. However, if I remove the "name" from the selector, everything works fine.
My customers have lots of Chinese Name in their MCC accounts. I think it is caused by the unicode problem of python and both the Chinese. How can I solve this problem to avoid this kind of error?

![image](https://cloud.githubusercontent.com/assets/1520489/12454370/2631792e-bfd2-11e5-80bb-2c2012186590.png)

![image](https://cloud.githubusercontent.com/assets/1520489/12454362/1d1e0906-bfd2-11e5-842e-e0b268e4f43b.png)

**Comment by msaniscalchi** [comment]
This was handled via the AdWords support alias. Looking at the stack trace, it appears that incompatible versions of suds and the sax parser are being used.

This library uses the suds-jurko library that includes its own sax parser. This is likely the cause of the issue, as we were unable to reproduce this with similar code that retrieves account names containing unicode characters.

**Comment by maxsonic** [comment]
@msaniscalchi. SInce I have posted in the adwords community and I guess the issue is an xml generation issue from the adwords backend(I am able to reproduce the issue in the java lib), I will not continue to post here. Thanks :)
