### ISSUE TITLE
__init__() takes at most 4 positional arguments (6 given) raised when using GoogleServiceAccountClient

### ISSUE THREAD

**Issue by mikeengland** [googleads/googleads-python-lib#98]
When you create a GoogleServiceAccountClient object, a warning is logged to stderr like so: __init__() takes at most 4 positional arguments (6 given). This is because there is a positional arguments decorator on the oauth2client.client.SignedJwtAssertionCredentials method which the GoogleServiceAccountClient calls on init.

If the __init__ decorator on the class SignedJwtAssertionCredentials is raised from 4 to 6, this warning will disappear. The other option is to name more arguments that are being passed when calling oauth2client.client.SignedJwtAssertionCredentials in the GoogleServiceAccountClient initialisation.

**Comment by msaniscalchi** [comment]
Hello Mike,

Thanks for the report! It sounds like the oauth2client library may have introduced breaking changes since this was written. If reproducible, I'll see if I can sneak a fix into the next release.

**Comment by mikeengland** [comment]
Great, thanks!
